// Code generated by cmd/clientdtogen from bloem-server internal/diagnostics. DO NOT EDIT.
// Server revision: d66c15d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.diagnostics

import kotlin.jvm.JvmInline
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/diagnostics.AvailabilityStatus`. Direction: response. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class AvailabilityStatus(public val wire: String) {
    public companion object {
        @SerialName("available")
        public val AVAILABLE: AvailabilityStatus = AvailabilityStatus("available")
        @SerialName("disabled")
        public val DISABLED: AvailabilityStatus = AvailabilityStatus("disabled")
        @SerialName("storage_unavailable")
        public val STORAGE_UNAVAILABLE: AvailabilityStatus = AvailabilityStatus("storage_unavailable")
        public val KNOWN: List<AvailabilityStatus> = listOf(AVAILABLE, DISABLED, STORAGE_UNAVAILABLE)
    }
}

/** Wire type `internal/diagnostics.IngestResult`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class IngestResult(
    @SerialName("report_id")
    public val reportId: String = "",
    @SerialName("short_id")
    public val shortId: String = "",
)

/** Wire type `internal/diagnostics.Status`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class Status(
    @SerialName("status")
    public val status: AvailabilityStatus = AvailabilityStatus(""),
    @SerialName("server_instance_id")
    public val serverInstanceId: String = "",
    @SerialName("accepted_schema_versions")
    public val acceptedSchemaVersions: List<Int> = emptyList(),
    @SerialName("max_bundle_bytes")
    public val maxBundleBytes: Long = 0L,
    @SerialName("max_manifest_bytes")
    public val maxManifestBytes: Long = 0L,
    @SerialName("retention_days")
    public val retentionDays: Int = 0,
    @SerialName("consent_notice_version")
    public val consentNoticeVersion: Int = 0,
    @SerialName("upload_chunk_bytes")
    public val uploadChunkBytes: Long = 0L,
)
