// Code generated by cmd/clientdtogen from bloem-server internal/requests. DO NOT EDIT.
// Server revision: f5e92f28caf025a10dbf90ab8082d1375f3ee53a (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.requests

import kotlin.jvm.JvmInline
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/requests.Availability`. Direction: response. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class Availability(public val wire: String) {
    public companion object {
        @SerialName("missing")
        public val MISSING: Availability = Availability("missing")
        @SerialName("available")
        public val AVAILABLE: Availability = Availability("available")
        public val KNOWN: List<Availability> = listOf(MISSING, AVAILABLE)
    }
}

/** Wire type `internal/requests.CreateRequestInput`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class CreateRequestInput(
    @SerialName("media_type")
    public val mediaType: MediaType,
    @SerialName("tmdb_id")
    public val tmdbid: Int,
    @SerialName("tvdb_id")
    public val tvdbid: Int? = null,
    @SerialName("imdb_id")
    public val imdbId: String = "",
    @SerialName("title")
    public val title: String,
    @SerialName("year")
    public val year: Int? = null,
    @SerialName("overview")
    public val overview: String = "",
    @SerialName("poster_path")
    public val posterPath: String = "",
    @SerialName("backdrop_path")
    public val backdropPath: String = "",
)

/** Wire type `internal/requests.DiscoverBrandCard`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class DiscoverBrandCard(
    @SerialName("tmdb_id")
    public val tmdbid: Int = 0,
    @SerialName("slug")
    public val slug: String = "",
    @SerialName("display_name")
    public val displayName: String = "",
    @SerialName("logo_url")
    public val logoUrl: String? = null,
    @SerialName("gradient_from")
    public val gradientFrom: String = "",
    @SerialName("gradient_to")
    public val gradientTo: String = "",
    @SerialName("series_supported")
    public val seriesSupported: Boolean = false,
)

/** Wire type `internal/requests.DiscoverBrowseResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class DiscoverBrowseResponse(
    @SerialName("kind")
    public val kind: String = "",
    @SerialName("slug")
    public val slug: String = "",
    @SerialName("display_name")
    public val displayName: String = "",
    @SerialName("logo_url")
    public val logoUrl: String? = null,
    @SerialName("media_type")
    public val mediaType: MediaType = MediaType(""),
    @SerialName("sort")
    public val sort: String = "",
    @SerialName("page")
    public val page: Int = 0,
    @SerialName("total_pages")
    public val totalPages: Int = 0,
    @SerialName("results")
    public val results: List<MediaResult> = emptyList(),
)

/** Wire type `internal/requests.DiscoverySection`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class DiscoverySection(
    @SerialName("key")
    public val key: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("page")
    public val page: Int = 0,
    @SerialName("total_pages")
    public val totalPages: Int = 0,
    @SerialName("total_results")
    public val totalResults: Int = 0,
    @SerialName("results")
    public val results: List<MediaResult> = emptyList(),
    @SerialName("next_page")
    public val nextPage: Int = 0,
)

/** Wire type `internal/requests.FeatureStatus`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class FeatureStatus(
    @SerialName("requests_enabled")
    public val requestsEnabled: Boolean = false,
    @SerialName("rating_restrictions_enforced")
    public val ratingRestrictionsEnforced: Boolean = false,
)

/** Wire type `internal/requests.MediaCastMember`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class MediaCastMember(
    @SerialName("name")
    public val name: String = "",
    @SerialName("character")
    public val character: String = "",
    @SerialName("profile_path")
    public val profilePath: String = "",
    @SerialName("order")
    public val order: Int = 0,
)

/** Wire type `internal/requests.MediaDetail`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class MediaDetail(
    @SerialName("media_type")
    public val mediaType: MediaType = MediaType(""),
    @SerialName("tmdb_id")
    public val tmdbid: Int = 0,
    @SerialName("imdb_id")
    public val imdbId: String = "",
    @SerialName("tvdb_id")
    public val tvdbid: Int? = null,
    @SerialName("title")
    public val title: String = "",
    @SerialName("original_title")
    public val originalTitle: String = "",
    @SerialName("tagline")
    public val tagline: String = "",
    @SerialName("overview")
    public val overview: String = "",
    @SerialName("poster_path")
    public val posterPath: String = "",
    @SerialName("backdrop_path")
    public val backdropPath: String = "",
    @SerialName("release_date")
    public val releaseDate: String = "",
    @SerialName("year")
    public val year: Int = 0,
    @SerialName("runtime")
    public val runtime: Int = 0,
    @SerialName("genres")
    public val genres: List<String> = emptyList(),
    @SerialName("vote_average")
    public val voteAverage: Double = 0.0,
    @SerialName("vote_count")
    public val voteCount: Int = 0,
    @SerialName("status")
    public val status: String = "",
    @SerialName("homepage")
    public val homepage: String = "",
    @SerialName("content_rating")
    public val contentRating: String = "",
    @SerialName("production_companies")
    public val productionCompanies: List<String> = emptyList(),
    @SerialName("number_of_seasons")
    public val numberOfSeasons: Int = 0,
    @SerialName("number_of_episodes")
    public val numberOfEpisodes: Int = 0,
    @SerialName("first_air_date")
    public val firstAirDate: String = "",
    @SerialName("last_air_date")
    public val lastAirDate: String = "",
    @SerialName("networks")
    public val networks: List<String> = emptyList(),
    @SerialName("cast")
    public val cast: List<MediaCastMember> = emptyList(),
    @SerialName("director")
    public val director: String = "",
    @SerialName("creators")
    public val creators: List<String> = emptyList(),
    @SerialName("recommendations")
    public val recommendations: List<MediaResult> = emptyList(),
    @SerialName("availability")
    public val availability: Availability = Availability(""),
    @SerialName("library_content_id")
    public val libraryContentId: String = "",
    @SerialName("request")
    public val request: RequestState = RequestState(),
)

/** Wire type `internal/requests.MediaPage`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class MediaPage(
    @SerialName("page")
    public val page: Int = 0,
    @SerialName("total_pages")
    public val totalPages: Int = 0,
    @SerialName("total_results")
    public val totalResults: Int = 0,
    @SerialName("results")
    public val results: List<MediaResult> = emptyList(),
)

/** Wire type `internal/requests.MediaResult`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class MediaResult(
    @SerialName("media_type")
    public val mediaType: MediaType = MediaType(""),
    @SerialName("tmdb_id")
    public val tmdbid: Int = 0,
    @SerialName("title")
    public val title: String = "",
    @SerialName("year")
    public val year: Int = 0,
    @SerialName("overview")
    public val overview: String = "",
    @SerialName("poster_path")
    public val posterPath: String = "",
    @SerialName("backdrop_path")
    public val backdropPath: String = "",
    @SerialName("release_date")
    public val releaseDate: String = "",
    @SerialName("popularity")
    public val popularity: Double = 0.0,
    @SerialName("vote_average")
    public val voteAverage: Double = 0.0,
    @SerialName("availability")
    public val availability: Availability = Availability(""),
    @SerialName("library_content_id")
    public val libraryContentId: String = "",
    @SerialName("request")
    public val request: RequestState = RequestState(),
)

/** Wire type `internal/requests.MediaType`. Direction: both. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class MediaType(public val wire: String) {
    public companion object {
        @SerialName("movie")
        public val MOVIE: MediaType = MediaType("movie")
        @SerialName("series")
        public val SERIES: MediaType = MediaType("series")
        @SerialName("all")
        public val ALL: MediaType = MediaType("all")
        public val KNOWN: List<MediaType> = listOf(MOVIE, SERIES, ALL)
    }
}

/** Wire type `internal/requests.Outcome`. Direction: response. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class Outcome(public val wire: String) {
    public companion object {
        @SerialName("active")
        public val ACTIVE: Outcome = Outcome("active")
        @SerialName("declined")
        public val DECLINED: Outcome = Outcome("declined")
        @SerialName("cancelled")
        public val CANCELLED: Outcome = Outcome("cancelled")
        @SerialName("failed")
        public val FAILED: Outcome = Outcome("failed")
        public val KNOWN: List<Outcome> = listOf(ACTIVE, DECLINED, CANCELLED, FAILED)
    }
}

/** Wire type `internal/requests.Quality`. Direction: response. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class Quality(public val wire: String) {
    public companion object {
        @SerialName("1080p")
        public val _1080: Quality = Quality("1080p")
        @SerialName("2160p")
        public val _2160: Quality = Quality("2160p")
        public val KNOWN: List<Quality> = listOf(_1080, _2160)
    }
}

/** Wire type `internal/requests.Request`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class Request(
    @SerialName("id")
    public val id: String = "",
    @SerialName("provider")
    public val provider: String = "",
    @SerialName("media_type")
    public val mediaType: MediaType = MediaType(""),
    @SerialName("tmdb_id")
    public val tmdbid: Int = 0,
    @SerialName("tvdb_id")
    public val tvdbid: Int? = null,
    @SerialName("imdb_id")
    public val imdbId: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("year")
    public val year: Int? = null,
    @SerialName("overview")
    public val overview: String = "",
    @SerialName("poster_path")
    public val posterPath: String = "",
    @SerialName("backdrop_path")
    public val backdropPath: String = "",
    @SerialName("status")
    public val status: Status = Status(""),
    @SerialName("outcome")
    public val outcome: Outcome = Outcome(""),
    @SerialName("requested_by_user_id")
    public val requestedByUserId: Int = 0,
    @SerialName("requested_by_profile_id")
    public val requestedByProfileId: String = "",
    @SerialName("integration_kind")
    public val integrationKind: String = "",
    @SerialName("is_anime")
    public val isAnime: Boolean = false,
    @SerialName("targets")
    public val targets: List<Target> = emptyList(),
    @SerialName("external_id")
    public val externalId: String = "",
    @SerialName("external_status")
    public val externalStatus: String = "",
    @SerialName("library_content_id")
    public val libraryContentId: String = "",
    @SerialName("last_error")
    public val lastError: String = "",
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("updated_at")
    public val updatedAt: String = "",
    @SerialName("approved_at")
    public val approvedAt: String? = null,
    @SerialName("completed_at")
    public val completedAt: String? = null,
)

/** Wire type `internal/requests.RequestState`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class RequestState(
    @SerialName("status")
    public val status: Status = Status(""),
    @SerialName("requestable")
    public val requestable: Boolean = false,
    @SerialName("reason")
    public val reason: String = "",
    @SerialName("request_id")
    public val requestId: String = "",
)

/** Wire type `internal/requests.Status`. Direction: response. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class Status(public val wire: String) {
    public companion object {
        @SerialName("pending")
        public val PENDING: Status = Status("pending")
        @SerialName("approved")
        public val APPROVED: Status = Status("approved")
        @SerialName("queued")
        public val QUEUED: Status = Status("queued")
        @SerialName("downloading")
        public val DOWNLOADING: Status = Status("downloading")
        @SerialName("completed")
        public val COMPLETED: Status = Status("completed")
        @SerialName("failed")
        public val FAILED: Status = Status("failed")
        public val KNOWN: List<Status> = listOf(PENDING, APPROVED, QUEUED, DOWNLOADING, COMPLETED, FAILED)
    }
}

/** Wire type `internal/requests.Target`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class Target(
    @SerialName("id")
    public val id: Long = 0L,
    @SerialName("request_id")
    public val requestId: String = "",
    @SerialName("integration_id")
    public val integrationId: String = "",
    @SerialName("integration_kind")
    public val integrationKind: String = "",
    @SerialName("instance_name")
    public val instanceName: String = "",
    @SerialName("quality")
    public val quality: Quality = Quality(""),
    @SerialName("is_anime")
    public val isAnime: Boolean = false,
    @SerialName("external_id")
    public val externalId: String = "",
    @SerialName("external_status")
    public val externalStatus: String = "",
    @SerialName("status")
    public val status: Status = Status(""),
    @SerialName("last_error")
    public val lastError: String = "",
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("updated_at")
    public val updatedAt: String = "",
)
