// Code generated by cmd/clientdtogen from bloem-server internal/requests. DO NOT EDIT.
// Server revision: 8c612bd9 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/requests`.
public enum Requests {
    /// Wire type `internal/requests.Availability`. Direction: response. Dialect: upstream-compat.
    public struct Availability: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let MISSING: Availability = Availability(rawValue: "missing")
        public static let AVAILABLE: Availability = Availability(rawValue: "available")
        public static let KNOWN: [Availability] = [MISSING, AVAILABLE]
    }

    /// Wire type `internal/requests.CreateRequestInput`. Direction: request. Dialect: upstream-compat. Registered root.
    public struct CreateRequestInput: Codable, Hashable, Sendable {
        public let mediaType: MediaType
        public let tmdbid: Int
        public let tvdbid: Int?
        public let imdbId: String
        public let title: String
        public let year: Int?
        public let overview: String
        public let posterPath: String
        public let backdropPath: String

        public enum CodingKeys: String, CodingKey {
            case mediaType = "media_type"
            case tmdbid = "tmdb_id"
            case tvdbid = "tvdb_id"
            case imdbId = "imdb_id"
            case title = "title"
            case year = "year"
            case overview = "overview"
            case posterPath = "poster_path"
            case backdropPath = "backdrop_path"
        }

        public init(
            mediaType: MediaType,
            tmdbid: Int,
            tvdbid: Int? = nil,
            imdbId: String = "",
            title: String,
            year: Int? = nil,
            overview: String = "",
            posterPath: String = "",
            backdropPath: String = ""
        ) {
            self.mediaType = mediaType
            self.tmdbid = tmdbid
            self.tvdbid = tvdbid
            self.imdbId = imdbId
            self.title = title
            self.year = year
            self.overview = overview
            self.posterPath = posterPath
            self.backdropPath = backdropPath
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.mediaType = try container.decode(MediaType.self, forKey: .mediaType)
            self.tmdbid = try container.decode(Int.self, forKey: .tmdbid)
            self.tvdbid = try container.decodeIfPresent(Int.self, forKey: .tvdbid)
            self.imdbId = try container.decodeIfPresent(String.self, forKey: .imdbId) ?? ""
            self.title = try container.decode(String.self, forKey: .title)
            self.year = try container.decodeIfPresent(Int.self, forKey: .year)
            self.overview = try container.decodeIfPresent(String.self, forKey: .overview) ?? ""
            self.posterPath = try container.decodeIfPresent(String.self, forKey: .posterPath) ?? ""
            self.backdropPath = try container.decodeIfPresent(String.self, forKey: .backdropPath) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.mediaType, forKey: .mediaType)
            try container.encode(self.tmdbid, forKey: .tmdbid)
            try container.encodeIfPresent(self.tvdbid, forKey: .tvdbid)
            try container.encode(self.imdbId, forKey: .imdbId)
            try container.encode(self.title, forKey: .title)
            try container.encodeIfPresent(self.year, forKey: .year)
            try container.encode(self.overview, forKey: .overview)
            try container.encode(self.posterPath, forKey: .posterPath)
            try container.encode(self.backdropPath, forKey: .backdropPath)
        }
    }

    /// Wire type `internal/requests.DiscoverBrandCard`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct DiscoverBrandCard: Codable, Hashable, Sendable {
        public let tmdbid: Int
        public let slug: String
        public let displayName: String
        public let logoUrl: String?
        public let gradientFrom: String
        public let gradientTo: String
        public let seriesSupported: Bool

        public enum CodingKeys: String, CodingKey {
            case tmdbid = "tmdb_id"
            case slug = "slug"
            case displayName = "display_name"
            case logoUrl = "logo_url"
            case gradientFrom = "gradient_from"
            case gradientTo = "gradient_to"
            case seriesSupported = "series_supported"
        }

        public init(
            tmdbid: Int = 0,
            slug: String = "",
            displayName: String = "",
            logoUrl: String? = nil,
            gradientFrom: String = "",
            gradientTo: String = "",
            seriesSupported: Bool = false
        ) {
            self.tmdbid = tmdbid
            self.slug = slug
            self.displayName = displayName
            self.logoUrl = logoUrl
            self.gradientFrom = gradientFrom
            self.gradientTo = gradientTo
            self.seriesSupported = seriesSupported
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.tmdbid = try container.decodeIfPresent(Int.self, forKey: .tmdbid) ?? 0
            self.slug = try container.decodeIfPresent(String.self, forKey: .slug) ?? ""
            self.displayName = try container.decodeIfPresent(String.self, forKey: .displayName) ?? ""
            self.logoUrl = try container.decodeIfPresent(String.self, forKey: .logoUrl)
            self.gradientFrom = try container.decodeIfPresent(String.self, forKey: .gradientFrom) ?? ""
            self.gradientTo = try container.decodeIfPresent(String.self, forKey: .gradientTo) ?? ""
            self.seriesSupported = try container.decodeIfPresent(Bool.self, forKey: .seriesSupported) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.tmdbid, forKey: .tmdbid)
            try container.encode(self.slug, forKey: .slug)
            try container.encode(self.displayName, forKey: .displayName)
            try container.encodeIfPresent(self.logoUrl, forKey: .logoUrl)
            try container.encode(self.gradientFrom, forKey: .gradientFrom)
            try container.encode(self.gradientTo, forKey: .gradientTo)
            try container.encode(self.seriesSupported, forKey: .seriesSupported)
        }
    }

    /// Wire type `internal/requests.DiscoverBrowseResponse`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct DiscoverBrowseResponse: Codable, Hashable, Sendable {
        public let kind: String
        public let slug: String
        public let displayName: String
        public let logoUrl: String?
        public let mediaType: MediaType
        public let sort: String
        public let page: Int
        public let totalPages: Int
        public let results: [MediaResult]

        public enum CodingKeys: String, CodingKey {
            case kind = "kind"
            case slug = "slug"
            case displayName = "display_name"
            case logoUrl = "logo_url"
            case mediaType = "media_type"
            case sort = "sort"
            case page = "page"
            case totalPages = "total_pages"
            case results = "results"
        }

        public init(
            kind: String = "",
            slug: String = "",
            displayName: String = "",
            logoUrl: String? = nil,
            mediaType: MediaType = MediaType(rawValue: ""),
            sort: String = "",
            page: Int = 0,
            totalPages: Int = 0,
            results: [MediaResult] = []
        ) {
            self.kind = kind
            self.slug = slug
            self.displayName = displayName
            self.logoUrl = logoUrl
            self.mediaType = mediaType
            self.sort = sort
            self.page = page
            self.totalPages = totalPages
            self.results = results
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.kind = try container.decodeIfPresent(String.self, forKey: .kind) ?? ""
            self.slug = try container.decodeIfPresent(String.self, forKey: .slug) ?? ""
            self.displayName = try container.decodeIfPresent(String.self, forKey: .displayName) ?? ""
            self.logoUrl = try container.decodeIfPresent(String.self, forKey: .logoUrl)
            self.mediaType = try container.decodeIfPresent(MediaType.self, forKey: .mediaType) ?? MediaType(rawValue: "")
            self.sort = try container.decodeIfPresent(String.self, forKey: .sort) ?? ""
            self.page = try container.decodeIfPresent(Int.self, forKey: .page) ?? 0
            self.totalPages = try container.decodeIfPresent(Int.self, forKey: .totalPages) ?? 0
            self.results = try container.decodeIfPresent([MediaResult].self, forKey: .results) ?? []
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.kind, forKey: .kind)
            try container.encode(self.slug, forKey: .slug)
            try container.encode(self.displayName, forKey: .displayName)
            try container.encodeIfPresent(self.logoUrl, forKey: .logoUrl)
            try container.encode(self.mediaType, forKey: .mediaType)
            try container.encode(self.sort, forKey: .sort)
            try container.encode(self.page, forKey: .page)
            try container.encode(self.totalPages, forKey: .totalPages)
            try container.encode(self.results, forKey: .results)
        }
    }

    /// Wire type `internal/requests.DiscoverySection`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct DiscoverySection: Codable, Hashable, Sendable {
        public let key: String
        public let title: String
        public let page: Int
        public let totalPages: Int
        public let totalResults: Int
        public let results: [MediaResult]
        public let nextPage: Int

        public enum CodingKeys: String, CodingKey {
            case key = "key"
            case title = "title"
            case page = "page"
            case totalPages = "total_pages"
            case totalResults = "total_results"
            case results = "results"
            case nextPage = "next_page"
        }

        public init(
            key: String = "",
            title: String = "",
            page: Int = 0,
            totalPages: Int = 0,
            totalResults: Int = 0,
            results: [MediaResult] = [],
            nextPage: Int = 0
        ) {
            self.key = key
            self.title = title
            self.page = page
            self.totalPages = totalPages
            self.totalResults = totalResults
            self.results = results
            self.nextPage = nextPage
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.key = try container.decodeIfPresent(String.self, forKey: .key) ?? ""
            self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? ""
            self.page = try container.decodeIfPresent(Int.self, forKey: .page) ?? 0
            self.totalPages = try container.decodeIfPresent(Int.self, forKey: .totalPages) ?? 0
            self.totalResults = try container.decodeIfPresent(Int.self, forKey: .totalResults) ?? 0
            self.results = try container.decodeIfPresent([MediaResult].self, forKey: .results) ?? []
            self.nextPage = try container.decodeIfPresent(Int.self, forKey: .nextPage) ?? 0
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.key, forKey: .key)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.page, forKey: .page)
            try container.encode(self.totalPages, forKey: .totalPages)
            try container.encode(self.totalResults, forKey: .totalResults)
            try container.encode(self.results, forKey: .results)
            try container.encode(self.nextPage, forKey: .nextPage)
        }
    }

    /// Wire type `internal/requests.FeatureStatus`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct FeatureStatus: Codable, Hashable, Sendable {
        public let requestsEnabled: Bool
        public let ratingRestrictionsEnforced: Bool

        public enum CodingKeys: String, CodingKey {
            case requestsEnabled = "requests_enabled"
            case ratingRestrictionsEnforced = "rating_restrictions_enforced"
        }

        public init(
            requestsEnabled: Bool = false,
            ratingRestrictionsEnforced: Bool = false
        ) {
            self.requestsEnabled = requestsEnabled
            self.ratingRestrictionsEnforced = ratingRestrictionsEnforced
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.requestsEnabled = try container.decodeIfPresent(Bool.self, forKey: .requestsEnabled) ?? false
            self.ratingRestrictionsEnforced = try container.decodeIfPresent(Bool.self, forKey: .ratingRestrictionsEnforced) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.requestsEnabled, forKey: .requestsEnabled)
            try container.encode(self.ratingRestrictionsEnforced, forKey: .ratingRestrictionsEnforced)
        }
    }

    /// Wire type `internal/requests.MediaCastMember`. Direction: response. Dialect: upstream-compat.
    public struct MediaCastMember: Codable, Hashable, Sendable {
        public let name: String
        public let character: String
        public let profilePath: String
        public let order: Int

        public enum CodingKeys: String, CodingKey {
            case name = "name"
            case character = "character"
            case profilePath = "profile_path"
            case order = "order"
        }

        public init(
            name: String = "",
            character: String = "",
            profilePath: String = "",
            order: Int = 0
        ) {
            self.name = name
            self.character = character
            self.profilePath = profilePath
            self.order = order
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.name = try container.decodeIfPresent(String.self, forKey: .name) ?? ""
            self.character = try container.decodeIfPresent(String.self, forKey: .character) ?? ""
            self.profilePath = try container.decodeIfPresent(String.self, forKey: .profilePath) ?? ""
            self.order = try container.decodeIfPresent(Int.self, forKey: .order) ?? 0
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.name, forKey: .name)
            try container.encode(self.character, forKey: .character)
            try container.encode(self.profilePath, forKey: .profilePath)
            try container.encode(self.order, forKey: .order)
        }
    }

    /// Wire type `internal/requests.MediaDetail`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct MediaDetail: Codable, Hashable, Sendable {
        public let mediaType: MediaType
        public let tmdbid: Int
        public let imdbId: String
        public let tvdbid: Int?
        public let title: String
        public let originalTitle: String
        public let tagline: String
        public let overview: String
        public let posterPath: String
        public let backdropPath: String
        public let releaseDate: String
        public let year: Int
        public let runtime: Int
        public let genres: [String]
        public let voteAverage: Double
        public let voteCount: Int
        public let status: String
        public let homepage: String
        public let contentRating: String
        public let productionCompanies: [String]
        public let numberOfSeasons: Int
        public let numberOfEpisodes: Int
        public let firstAirDate: String
        public let lastAirDate: String
        public let networks: [String]
        public let cast: [MediaCastMember]
        public let director: String
        public let creators: [String]
        public let recommendations: [MediaResult]
        public let availability: Availability
        public let libraryContentId: String
        public let request: RequestState

        public enum CodingKeys: String, CodingKey {
            case mediaType = "media_type"
            case tmdbid = "tmdb_id"
            case imdbId = "imdb_id"
            case tvdbid = "tvdb_id"
            case title = "title"
            case originalTitle = "original_title"
            case tagline = "tagline"
            case overview = "overview"
            case posterPath = "poster_path"
            case backdropPath = "backdrop_path"
            case releaseDate = "release_date"
            case year = "year"
            case runtime = "runtime"
            case genres = "genres"
            case voteAverage = "vote_average"
            case voteCount = "vote_count"
            case status = "status"
            case homepage = "homepage"
            case contentRating = "content_rating"
            case productionCompanies = "production_companies"
            case numberOfSeasons = "number_of_seasons"
            case numberOfEpisodes = "number_of_episodes"
            case firstAirDate = "first_air_date"
            case lastAirDate = "last_air_date"
            case networks = "networks"
            case cast = "cast"
            case director = "director"
            case creators = "creators"
            case recommendations = "recommendations"
            case availability = "availability"
            case libraryContentId = "library_content_id"
            case request = "request"
        }

        public init(
            mediaType: MediaType = MediaType(rawValue: ""),
            tmdbid: Int = 0,
            imdbId: String = "",
            tvdbid: Int? = nil,
            title: String = "",
            originalTitle: String = "",
            tagline: String = "",
            overview: String = "",
            posterPath: String = "",
            backdropPath: String = "",
            releaseDate: String = "",
            year: Int = 0,
            runtime: Int = 0,
            genres: [String] = [],
            voteAverage: Double = 0.0,
            voteCount: Int = 0,
            status: String = "",
            homepage: String = "",
            contentRating: String = "",
            productionCompanies: [String] = [],
            numberOfSeasons: Int = 0,
            numberOfEpisodes: Int = 0,
            firstAirDate: String = "",
            lastAirDate: String = "",
            networks: [String] = [],
            cast: [MediaCastMember] = [],
            director: String = "",
            creators: [String] = [],
            recommendations: [MediaResult] = [],
            availability: Availability = Availability(rawValue: ""),
            libraryContentId: String = "",
            request: RequestState = RequestState()
        ) {
            self.mediaType = mediaType
            self.tmdbid = tmdbid
            self.imdbId = imdbId
            self.tvdbid = tvdbid
            self.title = title
            self.originalTitle = originalTitle
            self.tagline = tagline
            self.overview = overview
            self.posterPath = posterPath
            self.backdropPath = backdropPath
            self.releaseDate = releaseDate
            self.year = year
            self.runtime = runtime
            self.genres = genres
            self.voteAverage = voteAverage
            self.voteCount = voteCount
            self.status = status
            self.homepage = homepage
            self.contentRating = contentRating
            self.productionCompanies = productionCompanies
            self.numberOfSeasons = numberOfSeasons
            self.numberOfEpisodes = numberOfEpisodes
            self.firstAirDate = firstAirDate
            self.lastAirDate = lastAirDate
            self.networks = networks
            self.cast = cast
            self.director = director
            self.creators = creators
            self.recommendations = recommendations
            self.availability = availability
            self.libraryContentId = libraryContentId
            self.request = request
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.mediaType = try container.decodeIfPresent(MediaType.self, forKey: .mediaType) ?? MediaType(rawValue: "")
            self.tmdbid = try container.decodeIfPresent(Int.self, forKey: .tmdbid) ?? 0
            self.imdbId = try container.decodeIfPresent(String.self, forKey: .imdbId) ?? ""
            self.tvdbid = try container.decodeIfPresent(Int.self, forKey: .tvdbid)
            self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? ""
            self.originalTitle = try container.decodeIfPresent(String.self, forKey: .originalTitle) ?? ""
            self.tagline = try container.decodeIfPresent(String.self, forKey: .tagline) ?? ""
            self.overview = try container.decodeIfPresent(String.self, forKey: .overview) ?? ""
            self.posterPath = try container.decodeIfPresent(String.self, forKey: .posterPath) ?? ""
            self.backdropPath = try container.decodeIfPresent(String.self, forKey: .backdropPath) ?? ""
            self.releaseDate = try container.decodeIfPresent(String.self, forKey: .releaseDate) ?? ""
            self.year = try container.decodeIfPresent(Int.self, forKey: .year) ?? 0
            self.runtime = try container.decodeIfPresent(Int.self, forKey: .runtime) ?? 0
            self.genres = try container.decodeIfPresent([String].self, forKey: .genres) ?? []
            self.voteAverage = try container.decodeIfPresent(Double.self, forKey: .voteAverage) ?? 0.0
            self.voteCount = try container.decodeIfPresent(Int.self, forKey: .voteCount) ?? 0
            self.status = try container.decodeIfPresent(String.self, forKey: .status) ?? ""
            self.homepage = try container.decodeIfPresent(String.self, forKey: .homepage) ?? ""
            self.contentRating = try container.decodeIfPresent(String.self, forKey: .contentRating) ?? ""
            self.productionCompanies = try container.decodeIfPresent([String].self, forKey: .productionCompanies) ?? []
            self.numberOfSeasons = try container.decodeIfPresent(Int.self, forKey: .numberOfSeasons) ?? 0
            self.numberOfEpisodes = try container.decodeIfPresent(Int.self, forKey: .numberOfEpisodes) ?? 0
            self.firstAirDate = try container.decodeIfPresent(String.self, forKey: .firstAirDate) ?? ""
            self.lastAirDate = try container.decodeIfPresent(String.self, forKey: .lastAirDate) ?? ""
            self.networks = try container.decodeIfPresent([String].self, forKey: .networks) ?? []
            self.cast = try container.decodeIfPresent([MediaCastMember].self, forKey: .cast) ?? []
            self.director = try container.decodeIfPresent(String.self, forKey: .director) ?? ""
            self.creators = try container.decodeIfPresent([String].self, forKey: .creators) ?? []
            self.recommendations = try container.decodeIfPresent([MediaResult].self, forKey: .recommendations) ?? []
            self.availability = try container.decodeIfPresent(Availability.self, forKey: .availability) ?? Availability(rawValue: "")
            self.libraryContentId = try container.decodeIfPresent(String.self, forKey: .libraryContentId) ?? ""
            self.request = try container.decodeIfPresent(RequestState.self, forKey: .request) ?? RequestState()
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.mediaType, forKey: .mediaType)
            try container.encode(self.tmdbid, forKey: .tmdbid)
            try container.encode(self.imdbId, forKey: .imdbId)
            try container.encodeIfPresent(self.tvdbid, forKey: .tvdbid)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.originalTitle, forKey: .originalTitle)
            try container.encode(self.tagline, forKey: .tagline)
            try container.encode(self.overview, forKey: .overview)
            try container.encode(self.posterPath, forKey: .posterPath)
            try container.encode(self.backdropPath, forKey: .backdropPath)
            try container.encode(self.releaseDate, forKey: .releaseDate)
            try container.encode(self.year, forKey: .year)
            try container.encode(self.runtime, forKey: .runtime)
            try container.encode(self.genres, forKey: .genres)
            try container.encode(self.voteAverage, forKey: .voteAverage)
            try container.encode(self.voteCount, forKey: .voteCount)
            try container.encode(self.status, forKey: .status)
            try container.encode(self.homepage, forKey: .homepage)
            try container.encode(self.contentRating, forKey: .contentRating)
            try container.encode(self.productionCompanies, forKey: .productionCompanies)
            try container.encode(self.numberOfSeasons, forKey: .numberOfSeasons)
            try container.encode(self.numberOfEpisodes, forKey: .numberOfEpisodes)
            try container.encode(self.firstAirDate, forKey: .firstAirDate)
            try container.encode(self.lastAirDate, forKey: .lastAirDate)
            try container.encode(self.networks, forKey: .networks)
            try container.encode(self.cast, forKey: .cast)
            try container.encode(self.director, forKey: .director)
            try container.encode(self.creators, forKey: .creators)
            try container.encode(self.recommendations, forKey: .recommendations)
            try container.encode(self.availability, forKey: .availability)
            try container.encode(self.libraryContentId, forKey: .libraryContentId)
            try container.encode(self.request, forKey: .request)
        }
    }

    /// Wire type `internal/requests.MediaPage`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct MediaPage: Codable, Hashable, Sendable {
        public let page: Int
        public let totalPages: Int
        public let totalResults: Int
        public let results: [MediaResult]

        public enum CodingKeys: String, CodingKey {
            case page = "page"
            case totalPages = "total_pages"
            case totalResults = "total_results"
            case results = "results"
        }

        public init(
            page: Int = 0,
            totalPages: Int = 0,
            totalResults: Int = 0,
            results: [MediaResult] = []
        ) {
            self.page = page
            self.totalPages = totalPages
            self.totalResults = totalResults
            self.results = results
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.page = try container.decodeIfPresent(Int.self, forKey: .page) ?? 0
            self.totalPages = try container.decodeIfPresent(Int.self, forKey: .totalPages) ?? 0
            self.totalResults = try container.decodeIfPresent(Int.self, forKey: .totalResults) ?? 0
            self.results = try container.decodeIfPresent([MediaResult].self, forKey: .results) ?? []
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.page, forKey: .page)
            try container.encode(self.totalPages, forKey: .totalPages)
            try container.encode(self.totalResults, forKey: .totalResults)
            try container.encode(self.results, forKey: .results)
        }
    }

    /// Wire type `internal/requests.MediaResult`. Direction: response. Dialect: upstream-compat.
    public struct MediaResult: Codable, Hashable, Sendable {
        public let mediaType: MediaType
        public let tmdbid: Int
        public let title: String
        public let year: Int
        public let overview: String
        public let posterPath: String
        public let backdropPath: String
        public let releaseDate: String
        public let popularity: Double
        public let voteAverage: Double
        public let availability: Availability
        public let libraryContentId: String
        public let request: RequestState

        public enum CodingKeys: String, CodingKey {
            case mediaType = "media_type"
            case tmdbid = "tmdb_id"
            case title = "title"
            case year = "year"
            case overview = "overview"
            case posterPath = "poster_path"
            case backdropPath = "backdrop_path"
            case releaseDate = "release_date"
            case popularity = "popularity"
            case voteAverage = "vote_average"
            case availability = "availability"
            case libraryContentId = "library_content_id"
            case request = "request"
        }

        public init(
            mediaType: MediaType = MediaType(rawValue: ""),
            tmdbid: Int = 0,
            title: String = "",
            year: Int = 0,
            overview: String = "",
            posterPath: String = "",
            backdropPath: String = "",
            releaseDate: String = "",
            popularity: Double = 0.0,
            voteAverage: Double = 0.0,
            availability: Availability = Availability(rawValue: ""),
            libraryContentId: String = "",
            request: RequestState = RequestState()
        ) {
            self.mediaType = mediaType
            self.tmdbid = tmdbid
            self.title = title
            self.year = year
            self.overview = overview
            self.posterPath = posterPath
            self.backdropPath = backdropPath
            self.releaseDate = releaseDate
            self.popularity = popularity
            self.voteAverage = voteAverage
            self.availability = availability
            self.libraryContentId = libraryContentId
            self.request = request
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.mediaType = try container.decodeIfPresent(MediaType.self, forKey: .mediaType) ?? MediaType(rawValue: "")
            self.tmdbid = try container.decodeIfPresent(Int.self, forKey: .tmdbid) ?? 0
            self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? ""
            self.year = try container.decodeIfPresent(Int.self, forKey: .year) ?? 0
            self.overview = try container.decodeIfPresent(String.self, forKey: .overview) ?? ""
            self.posterPath = try container.decodeIfPresent(String.self, forKey: .posterPath) ?? ""
            self.backdropPath = try container.decodeIfPresent(String.self, forKey: .backdropPath) ?? ""
            self.releaseDate = try container.decodeIfPresent(String.self, forKey: .releaseDate) ?? ""
            self.popularity = try container.decodeIfPresent(Double.self, forKey: .popularity) ?? 0.0
            self.voteAverage = try container.decodeIfPresent(Double.self, forKey: .voteAverage) ?? 0.0
            self.availability = try container.decodeIfPresent(Availability.self, forKey: .availability) ?? Availability(rawValue: "")
            self.libraryContentId = try container.decodeIfPresent(String.self, forKey: .libraryContentId) ?? ""
            self.request = try container.decodeIfPresent(RequestState.self, forKey: .request) ?? RequestState()
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.mediaType, forKey: .mediaType)
            try container.encode(self.tmdbid, forKey: .tmdbid)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.year, forKey: .year)
            try container.encode(self.overview, forKey: .overview)
            try container.encode(self.posterPath, forKey: .posterPath)
            try container.encode(self.backdropPath, forKey: .backdropPath)
            try container.encode(self.releaseDate, forKey: .releaseDate)
            try container.encode(self.popularity, forKey: .popularity)
            try container.encode(self.voteAverage, forKey: .voteAverage)
            try container.encode(self.availability, forKey: .availability)
            try container.encode(self.libraryContentId, forKey: .libraryContentId)
            try container.encode(self.request, forKey: .request)
        }
    }

    /// Wire type `internal/requests.MediaType`. Direction: both. Dialect: upstream-compat.
    public struct MediaType: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let MOVIE: MediaType = MediaType(rawValue: "movie")
        public static let SERIES: MediaType = MediaType(rawValue: "series")
        public static let ALL: MediaType = MediaType(rawValue: "all")
        public static let KNOWN: [MediaType] = [MOVIE, SERIES, ALL]
    }

    /// Wire type `internal/requests.Outcome`. Direction: response. Dialect: upstream-compat.
    public struct Outcome: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let ACTIVE: Outcome = Outcome(rawValue: "active")
        public static let DECLINED: Outcome = Outcome(rawValue: "declined")
        public static let CANCELLED: Outcome = Outcome(rawValue: "cancelled")
        public static let FAILED: Outcome = Outcome(rawValue: "failed")
        public static let KNOWN: [Outcome] = [ACTIVE, DECLINED, CANCELLED, FAILED]
    }

    /// Wire type `internal/requests.Quality`. Direction: response. Dialect: upstream-compat.
    public struct Quality: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let _1080: Quality = Quality(rawValue: "1080p")
        public static let _2160: Quality = Quality(rawValue: "2160p")
        public static let KNOWN: [Quality] = [_1080, _2160]
    }

    /// Wire type `internal/requests.Request`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct Request: Codable, Hashable, Sendable {
        public let id: String
        public let provider: String
        public let mediaType: MediaType
        public let tmdbid: Int
        public let tvdbid: Int?
        public let imdbId: String
        public let title: String
        public let year: Int?
        public let overview: String
        public let posterPath: String
        public let backdropPath: String
        public let status: Status
        public let outcome: Outcome
        public let requestedByUserId: Int
        public let requestedByProfileId: String
        public let integrationKind: String
        public let isAnime: Bool
        public let targets: [Target]
        public let externalId: String
        public let externalStatus: String
        public let libraryContentId: String
        public let lastError: String
        public let createdAt: String
        public let updatedAt: String
        public let approvedAt: String?
        public let completedAt: String?

        public enum CodingKeys: String, CodingKey {
            case id = "id"
            case provider = "provider"
            case mediaType = "media_type"
            case tmdbid = "tmdb_id"
            case tvdbid = "tvdb_id"
            case imdbId = "imdb_id"
            case title = "title"
            case year = "year"
            case overview = "overview"
            case posterPath = "poster_path"
            case backdropPath = "backdrop_path"
            case status = "status"
            case outcome = "outcome"
            case requestedByUserId = "requested_by_user_id"
            case requestedByProfileId = "requested_by_profile_id"
            case integrationKind = "integration_kind"
            case isAnime = "is_anime"
            case targets = "targets"
            case externalId = "external_id"
            case externalStatus = "external_status"
            case libraryContentId = "library_content_id"
            case lastError = "last_error"
            case createdAt = "created_at"
            case updatedAt = "updated_at"
            case approvedAt = "approved_at"
            case completedAt = "completed_at"
        }

        public init(
            id: String = "",
            provider: String = "",
            mediaType: MediaType = MediaType(rawValue: ""),
            tmdbid: Int = 0,
            tvdbid: Int? = nil,
            imdbId: String = "",
            title: String = "",
            year: Int? = nil,
            overview: String = "",
            posterPath: String = "",
            backdropPath: String = "",
            status: Status = Status(rawValue: ""),
            outcome: Outcome = Outcome(rawValue: ""),
            requestedByUserId: Int = 0,
            requestedByProfileId: String = "",
            integrationKind: String = "",
            isAnime: Bool = false,
            targets: [Target] = [],
            externalId: String = "",
            externalStatus: String = "",
            libraryContentId: String = "",
            lastError: String = "",
            createdAt: String = "",
            updatedAt: String = "",
            approvedAt: String? = nil,
            completedAt: String? = nil
        ) {
            self.id = id
            self.provider = provider
            self.mediaType = mediaType
            self.tmdbid = tmdbid
            self.tvdbid = tvdbid
            self.imdbId = imdbId
            self.title = title
            self.year = year
            self.overview = overview
            self.posterPath = posterPath
            self.backdropPath = backdropPath
            self.status = status
            self.outcome = outcome
            self.requestedByUserId = requestedByUserId
            self.requestedByProfileId = requestedByProfileId
            self.integrationKind = integrationKind
            self.isAnime = isAnime
            self.targets = targets
            self.externalId = externalId
            self.externalStatus = externalStatus
            self.libraryContentId = libraryContentId
            self.lastError = lastError
            self.createdAt = createdAt
            self.updatedAt = updatedAt
            self.approvedAt = approvedAt
            self.completedAt = completedAt
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.id = try container.decodeIfPresent(String.self, forKey: .id) ?? ""
            self.provider = try container.decodeIfPresent(String.self, forKey: .provider) ?? ""
            self.mediaType = try container.decodeIfPresent(MediaType.self, forKey: .mediaType) ?? MediaType(rawValue: "")
            self.tmdbid = try container.decodeIfPresent(Int.self, forKey: .tmdbid) ?? 0
            self.tvdbid = try container.decodeIfPresent(Int.self, forKey: .tvdbid)
            self.imdbId = try container.decodeIfPresent(String.self, forKey: .imdbId) ?? ""
            self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? ""
            self.year = try container.decodeIfPresent(Int.self, forKey: .year)
            self.overview = try container.decodeIfPresent(String.self, forKey: .overview) ?? ""
            self.posterPath = try container.decodeIfPresent(String.self, forKey: .posterPath) ?? ""
            self.backdropPath = try container.decodeIfPresent(String.self, forKey: .backdropPath) ?? ""
            self.status = try container.decodeIfPresent(Status.self, forKey: .status) ?? Status(rawValue: "")
            self.outcome = try container.decodeIfPresent(Outcome.self, forKey: .outcome) ?? Outcome(rawValue: "")
            self.requestedByUserId = try container.decodeIfPresent(Int.self, forKey: .requestedByUserId) ?? 0
            self.requestedByProfileId = try container.decodeIfPresent(String.self, forKey: .requestedByProfileId) ?? ""
            self.integrationKind = try container.decodeIfPresent(String.self, forKey: .integrationKind) ?? ""
            self.isAnime = try container.decodeIfPresent(Bool.self, forKey: .isAnime) ?? false
            self.targets = try container.decodeIfPresent([Target].self, forKey: .targets) ?? []
            self.externalId = try container.decodeIfPresent(String.self, forKey: .externalId) ?? ""
            self.externalStatus = try container.decodeIfPresent(String.self, forKey: .externalStatus) ?? ""
            self.libraryContentId = try container.decodeIfPresent(String.self, forKey: .libraryContentId) ?? ""
            self.lastError = try container.decodeIfPresent(String.self, forKey: .lastError) ?? ""
            self.createdAt = try container.decodeIfPresent(String.self, forKey: .createdAt) ?? ""
            self.updatedAt = try container.decodeIfPresent(String.self, forKey: .updatedAt) ?? ""
            self.approvedAt = try container.decodeIfPresent(String.self, forKey: .approvedAt)
            self.completedAt = try container.decodeIfPresent(String.self, forKey: .completedAt)
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.id, forKey: .id)
            try container.encode(self.provider, forKey: .provider)
            try container.encode(self.mediaType, forKey: .mediaType)
            try container.encode(self.tmdbid, forKey: .tmdbid)
            try container.encodeIfPresent(self.tvdbid, forKey: .tvdbid)
            try container.encode(self.imdbId, forKey: .imdbId)
            try container.encode(self.title, forKey: .title)
            try container.encodeIfPresent(self.year, forKey: .year)
            try container.encode(self.overview, forKey: .overview)
            try container.encode(self.posterPath, forKey: .posterPath)
            try container.encode(self.backdropPath, forKey: .backdropPath)
            try container.encode(self.status, forKey: .status)
            try container.encode(self.outcome, forKey: .outcome)
            try container.encode(self.requestedByUserId, forKey: .requestedByUserId)
            try container.encode(self.requestedByProfileId, forKey: .requestedByProfileId)
            try container.encode(self.integrationKind, forKey: .integrationKind)
            try container.encode(self.isAnime, forKey: .isAnime)
            try container.encode(self.targets, forKey: .targets)
            try container.encode(self.externalId, forKey: .externalId)
            try container.encode(self.externalStatus, forKey: .externalStatus)
            try container.encode(self.libraryContentId, forKey: .libraryContentId)
            try container.encode(self.lastError, forKey: .lastError)
            try container.encode(self.createdAt, forKey: .createdAt)
            try container.encode(self.updatedAt, forKey: .updatedAt)
            try container.encodeIfPresent(self.approvedAt, forKey: .approvedAt)
            try container.encodeIfPresent(self.completedAt, forKey: .completedAt)
        }
    }

    /// Wire type `internal/requests.RequestState`. Direction: response. Dialect: upstream-compat.
    public struct RequestState: Codable, Hashable, Sendable {
        public let status: Status
        public let requestable: Bool
        public let reason: String
        public let requestId: String

        public enum CodingKeys: String, CodingKey {
            case status = "status"
            case requestable = "requestable"
            case reason = "reason"
            case requestId = "request_id"
        }

        public init(
            status: Status = Status(rawValue: ""),
            requestable: Bool = false,
            reason: String = "",
            requestId: String = ""
        ) {
            self.status = status
            self.requestable = requestable
            self.reason = reason
            self.requestId = requestId
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.status = try container.decodeIfPresent(Status.self, forKey: .status) ?? Status(rawValue: "")
            self.requestable = try container.decodeIfPresent(Bool.self, forKey: .requestable) ?? false
            self.reason = try container.decodeIfPresent(String.self, forKey: .reason) ?? ""
            self.requestId = try container.decodeIfPresent(String.self, forKey: .requestId) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.status, forKey: .status)
            try container.encode(self.requestable, forKey: .requestable)
            try container.encode(self.reason, forKey: .reason)
            try container.encode(self.requestId, forKey: .requestId)
        }
    }

    /// Wire type `internal/requests.Status`. Direction: response. Dialect: upstream-compat.
    public struct Status: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let PENDING: Status = Status(rawValue: "pending")
        public static let APPROVED: Status = Status(rawValue: "approved")
        public static let QUEUED: Status = Status(rawValue: "queued")
        public static let DOWNLOADING: Status = Status(rawValue: "downloading")
        public static let COMPLETED: Status = Status(rawValue: "completed")
        public static let FAILED: Status = Status(rawValue: "failed")
        public static let KNOWN: [Status] = [PENDING, APPROVED, QUEUED, DOWNLOADING, COMPLETED, FAILED]
    }

    /// Wire type `internal/requests.Target`. Direction: response. Dialect: upstream-compat.
    public struct Target: Codable, Hashable, Sendable {
        public let id: Int64
        public let requestId: String
        public let integrationId: String
        public let integrationKind: String
        public let instanceName: String
        public let quality: Quality
        public let isAnime: Bool
        public let externalId: String
        public let externalStatus: String
        public let status: Status
        public let lastError: String
        public let createdAt: String
        public let updatedAt: String

        public enum CodingKeys: String, CodingKey {
            case id = "id"
            case requestId = "request_id"
            case integrationId = "integration_id"
            case integrationKind = "integration_kind"
            case instanceName = "instance_name"
            case quality = "quality"
            case isAnime = "is_anime"
            case externalId = "external_id"
            case externalStatus = "external_status"
            case status = "status"
            case lastError = "last_error"
            case createdAt = "created_at"
            case updatedAt = "updated_at"
        }

        public init(
            id: Int64 = 0,
            requestId: String = "",
            integrationId: String = "",
            integrationKind: String = "",
            instanceName: String = "",
            quality: Quality = Quality(rawValue: ""),
            isAnime: Bool = false,
            externalId: String = "",
            externalStatus: String = "",
            status: Status = Status(rawValue: ""),
            lastError: String = "",
            createdAt: String = "",
            updatedAt: String = ""
        ) {
            self.id = id
            self.requestId = requestId
            self.integrationId = integrationId
            self.integrationKind = integrationKind
            self.instanceName = instanceName
            self.quality = quality
            self.isAnime = isAnime
            self.externalId = externalId
            self.externalStatus = externalStatus
            self.status = status
            self.lastError = lastError
            self.createdAt = createdAt
            self.updatedAt = updatedAt
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.id = try container.decodeIfPresent(Int64.self, forKey: .id) ?? 0
            self.requestId = try container.decodeIfPresent(String.self, forKey: .requestId) ?? ""
            self.integrationId = try container.decodeIfPresent(String.self, forKey: .integrationId) ?? ""
            self.integrationKind = try container.decodeIfPresent(String.self, forKey: .integrationKind) ?? ""
            self.instanceName = try container.decodeIfPresent(String.self, forKey: .instanceName) ?? ""
            self.quality = try container.decodeIfPresent(Quality.self, forKey: .quality) ?? Quality(rawValue: "")
            self.isAnime = try container.decodeIfPresent(Bool.self, forKey: .isAnime) ?? false
            self.externalId = try container.decodeIfPresent(String.self, forKey: .externalId) ?? ""
            self.externalStatus = try container.decodeIfPresent(String.self, forKey: .externalStatus) ?? ""
            self.status = try container.decodeIfPresent(Status.self, forKey: .status) ?? Status(rawValue: "")
            self.lastError = try container.decodeIfPresent(String.self, forKey: .lastError) ?? ""
            self.createdAt = try container.decodeIfPresent(String.self, forKey: .createdAt) ?? ""
            self.updatedAt = try container.decodeIfPresent(String.self, forKey: .updatedAt) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.id, forKey: .id)
            try container.encode(self.requestId, forKey: .requestId)
            try container.encode(self.integrationId, forKey: .integrationId)
            try container.encode(self.integrationKind, forKey: .integrationKind)
            try container.encode(self.instanceName, forKey: .instanceName)
            try container.encode(self.quality, forKey: .quality)
            try container.encode(self.isAnime, forKey: .isAnime)
            try container.encode(self.externalId, forKey: .externalId)
            try container.encode(self.externalStatus, forKey: .externalStatus)
            try container.encode(self.status, forKey: .status)
            try container.encode(self.lastError, forKey: .lastError)
            try container.encode(self.createdAt, forKey: .createdAt)
            try container.encode(self.updatedAt, forKey: .updatedAt)
        }
    }
}
