// Code generated by cmd/clientdtogen from bloem-server internal/catalog. DO NOT EDIT.
// Server revision: d73b4e31c1138e3bce555c4104450d75d7aa9eaf (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.catalog

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/catalog.AudiobookDetailExtension`. Direction: response. Dialect: bloem. */
@Serializable
public data class AudiobookDetailExtension(
    @SerialName("authors")
    public val authors: List<AudiobookPerson> = emptyList(),
    @SerialName("narrators")
    public val narrators: List<AudiobookPerson> = emptyList(),
    @SerialName("publisher")
    public val publisher: String = "",
    @SerialName("total_duration_seconds")
    public val totalDurationSeconds: Int = 0,
    @SerialName("series")
    public val series: AudiobookSeriesGroup? = null,
    @SerialName("other_narrations")
    public val otherNarrations: List<AudiobookNarration> = emptyList(),
    @SerialName("related")
    public val related: AudiobookRelatedContent = AudiobookRelatedContent(),
)

/** Wire type `internal/catalog.AudiobookNarration`. Direction: response. Dialect: bloem. */
@Serializable
public data class AudiobookNarration(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("year")
    public val year: Int = 0,
    @SerialName("narrators")
    public val narrators: List<String> = emptyList(),
)

/** Wire type `internal/catalog.AudiobookPerson`. Direction: response. Dialect: bloem. */
@Serializable
public data class AudiobookPerson(
    @SerialName("person_id")
    public val personId: String = "",
    @SerialName("name")
    public val name: String = "",
    @SerialName("photo_url")
    public val photoUrl: String = "",
    @SerialName("photo_thumbhash")
    public val photoThumbhash: String = "",
)

/** Wire type `internal/catalog.AudiobookRelatedContent`. Direction: response. Dialect: bloem. */
@Serializable
public data class AudiobookRelatedContent(
    @SerialName("also_by_author")
    public val alsoByAuthor: List<AudiobookRelatedItem> = emptyList(),
    @SerialName("similar")
    public val similar: List<AudiobookRelatedItem> = emptyList(),
)

/** Wire type `internal/catalog.AudiobookRelatedItem`. Direction: response. Dialect: bloem. */
@Serializable
public data class AudiobookRelatedItem(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("year")
    public val year: Int = 0,
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("series_index")
    public val seriesIndex: Int? = null,
)

/** Wire type `internal/catalog.AudiobookSeriesGroup`. Direction: response. Dialect: bloem. */
@Serializable
public data class AudiobookSeriesGroup(
    @SerialName("name")
    public val name: String = "",
    @SerialName("entries")
    public val entries: List<AudiobookRelatedItem> = emptyList(),
)

/** Wire type `internal/catalog.CastCredit`. Direction: response. Dialect: bloem. */
@Serializable
public data class CastCredit(
    @SerialName("name")
    public val name: String = "",
    @SerialName("character")
    public val character: String = "",
    @SerialName("order")
    public val order: Int = 0,
    @SerialName("person_id")
    public val personId: String = "",
    @SerialName("tmdb_id")
    public val tmdbId: String = "",
    @SerialName("tvdb_id")
    public val tvdbId: String = "",
    @SerialName("imdb_id")
    public val imdbId: String = "",
    @SerialName("plex_guid")
    public val plexGuid: String = "",
    @SerialName("photo_url")
    public val photoUrl: String = "",
    @SerialName("photo_thumbhash")
    public val photoThumbhash: String = "",
)

/** Wire type `internal/catalog.CrewCredit`. Direction: response. Dialect: bloem. */
@Serializable
public data class CrewCredit(
    @SerialName("name")
    public val name: String = "",
    @SerialName("job")
    public val job: String = "",
    @SerialName("person_id")
    public val personId: String = "",
    @SerialName("tmdb_id")
    public val tmdbId: String = "",
    @SerialName("tvdb_id")
    public val tvdbId: String = "",
    @SerialName("imdb_id")
    public val imdbId: String = "",
    @SerialName("plex_guid")
    public val plexGuid: String = "",
    @SerialName("photo_url")
    public val photoUrl: String = "",
    @SerialName("photo_thumbhash")
    public val photoThumbhash: String = "",
)

/** Wire type `internal/catalog.EbookDetailExtension`. Direction: response. Dialect: bloem. */
@Serializable
public data class EbookDetailExtension(
    @SerialName("authors")
    public val authors: List<AudiobookPerson> = emptyList(),
    @SerialName("publisher")
    public val publisher: String = "",
    @SerialName("series")
    public val series: AudiobookSeriesGroup? = null,
    @SerialName("related")
    public val related: AudiobookRelatedContent = AudiobookRelatedContent(),
)

/** Wire type `internal/catalog.ItemExtraInfo`. Direction: response. Dialect: bloem. */
@Serializable
public data class ItemExtraInfo(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("kind")
    public val kind: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("duration_seconds")
    public val durationSeconds: Int = 0,
    @SerialName("file_id")
    public val fileId: Int = 0,
)

/** Wire type `internal/catalog.ItemVideoInfo`. Direction: response. Dialect: bloem. */
@Serializable
public data class ItemVideoInfo(
    @SerialName("kind")
    public val kind: String = "",
    @SerialName("site")
    public val site: String = "",
    @SerialName("site_key")
    public val siteKey: String = "",
    @SerialName("name")
    public val name: String = "",
    @SerialName("language")
    public val language: String = "",
    @SerialName("is_official")
    public val isOfficial: Boolean = false,
)

/** Wire type `internal/catalog.MangaChapter`. Direction: response. Dialect: bloem. */
@Serializable
public data class MangaChapter(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("chapter_index")
    public val chapterIndex: Double? = null,
    @SerialName("volume")
    public val volume: String = "",
    @SerialName("read")
    public val read: Boolean = false,
    @SerialName("progress")
    public val progress: Double? = null,
    @SerialName("poster_url")
    public val posterUrl: String = "",
)

/** Wire type `internal/catalog.MangaDetailExtension`. Direction: response. Dialect: bloem. */
@Serializable
public data class MangaDetailExtension(
    @SerialName("chapters")
    public val chapters: List<MangaChapter> = emptyList(),
)

/** Wire type `internal/catalog.Marker`. Direction: response. Dialect: bloem. */
@Serializable
public data class Marker(
    @SerialName("start")
    public val start: Double = 0.0,
    @SerialName("end")
    public val end: Double = 0.0,
)

/** Wire type `internal/catalog.SeasonUserData`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class SeasonUserData(
    @SerialName("position_seconds")
    public val positionSeconds: Double = 0.0,
    @SerialName("duration_seconds")
    public val durationSeconds: Double = 0.0,
    @SerialName("is_in_progress")
    public val isInProgress: Boolean = false,
    @SerialName("watched_count")
    public val watchedCount: Int = 0,
    @SerialName("unplayed_count")
    public val unplayedCount: Int = 0,
    @SerialName("in_progress_count")
    public val inProgressCount: Int = 0,
    @SerialName("played")
    public val played: Boolean = false,
    @SerialName("last_file_id")
    public val lastFileId: Int? = null,
    @SerialName("last_resolution")
    public val lastResolution: String? = null,
    @SerialName("last_hdr")
    public val lastHdr: Boolean? = null,
    @SerialName("last_codec_video")
    public val lastCodecVideo: String? = null,
    @SerialName("last_edition_key")
    public val lastEditionKey: String? = null,
)

/** Wire type `internal/catalog.SubtitleInfo`. Direction: response. Dialect: bloem. */
@Serializable
public data class SubtitleInfo(
    @SerialName("source")
    public val source: String = "",
    @SerialName("language")
    public val language: String = "",
    @SerialName("codec")
    public val codec: String = "",
    @SerialName("forced")
    public val forced: Boolean = false,
    @SerialName("hearing_impaired")
    public val hearingImpaired: Boolean = false,
    @SerialName("title")
    public val title: String = "",
)

/** Wire type `internal/catalog.VersionChapter`. Direction: response. Dialect: bloem. */
@Serializable
public data class VersionChapter(
    @SerialName("index")
    public val index: Int = 0,
    @SerialName("title")
    public val title: String = "",
    @SerialName("start_seconds")
    public val startSeconds: Double = 0.0,
    @SerialName("end_seconds")
    public val endSeconds: Double = 0.0,
    @SerialName("source")
    public val source: String = "",
    @SerialName("thumbnail_url")
    public val thumbnailUrl: String = "",
    @SerialName("thumbnail_thumbhash")
    public val thumbnailThumbhash: String = "",
)

/** Wire type `internal/catalog.VersionSubtitleTrack`. Direction: response. Dialect: bloem. */
@Serializable
public data class VersionSubtitleTrack(
    @SerialName("index")
    public val index: Int = 0,
    @SerialName("language")
    public val language: String = "",
    @SerialName("codec")
    public val codec: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("embedded_title")
    public val embeddedTitle: String = "",
    @SerialName("resolution")
    public val resolution: String = "",
    @SerialName("forced")
    public val forced: Boolean = false,
    @SerialName("default")
    public val default: Boolean = false,
    @SerialName("hearing_impaired")
    public val hearingImpaired: Boolean = false,
    @SerialName("external")
    public val external: Boolean = false,
    @SerialName("file_name")
    public val fileName: String = "",
)

/** Wire type `internal/catalog.WorkFormatSummary`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class WorkFormatSummary(
    @SerialName("type")
    public val type: String = "",
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("library_id")
    public val libraryId: Int = 0,
)
