// Code generated by cmd/clientdtogen from bloem-server internal/catalog. DO NOT EDIT.
// Server revision: 8c612bd9 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.catalog

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/catalog.SeasonUserData`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class SeasonUserData(
    @SerialName("position_seconds")
    public val positionSeconds: Double = 0.0,
    @SerialName("duration_seconds")
    public val durationSeconds: Double = 0.0,
    @SerialName("is_in_progress")
    public val isInProgress: Boolean = false,
    @SerialName("watched_count")
    public val watchedCount: Int = 0,
    @SerialName("unplayed_count")
    public val unplayedCount: Int = 0,
    @SerialName("in_progress_count")
    public val inProgressCount: Int = 0,
    @SerialName("played")
    public val played: Boolean = false,
    @SerialName("last_file_id")
    public val lastFileId: Int? = null,
    @SerialName("last_resolution")
    public val lastResolution: String? = null,
    @SerialName("last_hdr")
    public val lastHdr: Boolean? = null,
    @SerialName("last_codec_video")
    public val lastCodecVideo: String? = null,
    @SerialName("last_edition_key")
    public val lastEditionKey: String? = null,
)

/** Wire type `internal/catalog.WorkFormatSummary`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class WorkFormatSummary(
    @SerialName("type")
    public val type: String = "",
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("library_id")
    public val libraryId: Int = 0,
)
