// Code generated by cmd/clientdtogen from bloem-server internal/events. DO NOT EDIT.
// Server revision: d66c15d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.events

import kotlin.jvm.JvmInline
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/** Wire type `internal/events.EventChannel`. Direction: both. Dialect: bloem. */
@Serializable
@JvmInline
public value class EventChannel(public val wire: String) {
    public companion object {
        @SerialName("catalog")
        public val CATALOG: EventChannel = EventChannel("catalog")
        @SerialName("jobs")
        public val JOBS: EventChannel = EventChannel("jobs")
        @SerialName("sessions")
        public val SESSIONS: EventChannel = EventChannel("sessions")
        @SerialName("tasks")
        public val TASKS: EventChannel = EventChannel("tasks")
        @SerialName("scans")
        public val SCANS: EventChannel = EventChannel("scans")
        @SerialName("history_import")
        public val HISTORY_IMPORT: EventChannel = EventChannel("history_import")
        @SerialName("user_state")
        public val USER_STATE: EventChannel = EventChannel("user_state")
        @SerialName("user_settings")
        public val USER_SETTINGS: EventChannel = EventChannel("user_settings")
        @SerialName("settings")
        public val SETTINGS: EventChannel = EventChannel("settings")
        @SerialName("plugins")
        public val PLUGINS: EventChannel = EventChannel("plugins")
        @SerialName("notifications")
        public val NOTIFICATIONS: EventChannel = EventChannel("notifications")
        public val KNOWN: List<EventChannel> = listOf(CATALOG, JOBS, SESSIONS, TASKS, SCANS, HISTORY_IMPORT, USER_STATE, USER_SETTINGS, SETTINGS, PLUGINS, NOTIFICATIONS)
    }
}

/** Wire type `internal/events.EventsErrorMessage`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class EventsErrorMessage(
    @SerialName("type")
    public val type: String = "",
    @SerialName("code")
    public val code: String = "",
    @SerialName("message")
    public val message: String = "",
)

/** Wire type `internal/events.EventsEventMessage`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class EventsEventMessage(
    @SerialName("type")
    public val type: String = "",
    @SerialName("channel")
    public val channel: EventChannel = EventChannel(""),
    @SerialName("event")
    public val event: String = "",
    @SerialName("event_id")
    public val eventId: String = "",
    @SerialName("timestamp")
    public val timestamp: String = "",
    @SerialName("data")
    public val data: JsonElement? = null,
)

/** Wire type `internal/events.EventsHelloMessage`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class EventsHelloMessage(
    @SerialName("type")
    public val type: String = "",
    @SerialName("schema_version")
    public val schemaVersion: Int = 0,
    @SerialName("connection_id")
    public val connectionId: String = "",
    @SerialName("available_channels")
    public val availableChannels: List<EventChannel> = emptyList(),
    @SerialName("required_action")
    public val requiredAction: String = "",
)

/** Wire type `internal/events.EventsRejectedChannel`. Direction: response. Dialect: bloem. */
@Serializable
public data class EventsRejectedChannel(
    @SerialName("channel")
    public val channel: EventChannel = EventChannel(""),
    @SerialName("code")
    public val code: String = "",
    @SerialName("message")
    public val message: String = "",
)

/** Wire type `internal/events.EventsSnapshotMessage`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class EventsSnapshotMessage(
    @SerialName("type")
    public val type: String = "",
    @SerialName("channel")
    public val channel: EventChannel = EventChannel(""),
    @SerialName("timestamp")
    public val timestamp: String = "",
    @SerialName("data")
    public val data: JsonElement? = null,
)

/** Wire type `internal/events.EventsSubscribeMessage`. Direction: request. Dialect: bloem. Registered root. */
@Serializable
public data class EventsSubscribeMessage(
    @SerialName("type")
    public val type: String,
    @SerialName("request_id")
    public val requestId: String = "",
    @SerialName("channels")
    public val channels: List<EventChannel>,
)

/** Wire type `internal/events.EventsSubscribedMessage`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class EventsSubscribedMessage(
    @SerialName("type")
    public val type: String = "",
    @SerialName("request_id")
    public val requestId: String = "",
    @SerialName("channels")
    public val channels: List<EventChannel> = emptyList(),
    @SerialName("rejected")
    public val rejected: List<EventsRejectedChannel> = emptyList(),
)
