// Code generated by cmd/clientdtogen from bloem-server internal/api/handlers. DO NOT EDIT.
// Server revision: f5e92f28caf025a10dbf90ab8082d1375f3ee53a (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.handlers

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import org.bloemserver.bloem.contract.ambience.Wire
import org.bloemserver.bloem.contract.catalog.SeasonUserData
import org.bloemserver.bloem.contract.catalog.WorkFormatSummary
import org.bloemserver.bloem.contract.downloads.SkippedDownload
import org.bloemserver.bloem.contract.events.EventChannel
import org.bloemserver.bloem.contract.models.OverlaySummary
import org.bloemserver.bloem.contract.notifications.DeliveryRowPayload
import org.bloemserver.bloem.contract.playback.ClientCapabilities
import org.bloemserver.bloem.contract.playback.CommandName
import org.bloemserver.bloem.contract.promotions.Card
import org.bloemserver.bloem.contract.recommendations.ForYouRow
import org.bloemserver.bloem.contract.recommendations.ScoredItem
import org.bloemserver.bloem.contract.remote.Command
import org.bloemserver.bloem.contract.requests.DiscoverBrandCard
import org.bloemserver.bloem.contract.requests.DiscoverySection
import org.bloemserver.bloem.contract.requests.Request
import org.bloemserver.bloem.contract.sections.FilterGroup
import org.bloemserver.bloem.contract.sections.ReorderEntry
import org.bloemserver.bloem.contract.userstore.SubtitleTrackSignature
import org.bloemserver.bloem.contract.watchtogether.GuestControlPolicy
import org.bloemserver.bloem.contract.watchtogether.Snapshot
import org.bloemserver.bloem.contract.watchtogether.Suggestion

/** Wire type `internal/api/handlers.applePushRegisterRequest`. Direction: request. Dialect: bloem. Registered root. */
@Serializable
public data class applePushRegisterRequest(
    @SerialName("device_id")
    public val deviceId: String,
    @SerialName("apns_token")
    public val apnsToken: String,
    @SerialName("apns_environment")
    public val apnsEnvironment: String,
    @SerialName("apns_topic")
    public val apnsTopic: String,
    @SerialName("push_mode")
    public val pushMode: String,
)

/** Wire type `internal/api/handlers.applePushRegisterResponse`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class applePushRegisterResponse(
    @SerialName("id")
    public val id: String = "",
    @SerialName("server_device_id")
    public val serverDeviceId: String = "",
    @SerialName("enabled")
    public val enabled: Boolean = false,
    @SerialName("push_mode")
    public val pushMode: String = "",
)

/** Wire type `internal/api/handlers.authProviderResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class authProviderResponse(
    @SerialName("id")
    public val id: String = "",
    @SerialName("display_name")
    public val displayName: String = "",
    @SerialName("mode")
    public val mode: String = "",
    @SerialName("default")
    public val default: Boolean = false,
    @SerialName("icon_url")
    public val iconUrl: String = "",
    @SerialName("installation_id")
    public val installationId: Int = 0,
)

/** Wire type `internal/api/handlers.browseResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class browseResponse(
    @SerialName("total")
    public val total: Int = 0,
    @SerialName("total_exact")
    public val totalExact: Boolean = false,
    @SerialName("has_more")
    public val hasMore: Boolean = false,
    @SerialName("items")
    public val items: List<itemListResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.calendarDayResponse`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class calendarDayResponse(
    @SerialName("date")
    public val date: String = "",
    @SerialName("items")
    public val items: List<calendarEventResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.calendarEventResponse`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class calendarEventResponse(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("episode_title")
    public val episodeTitle: String? = null,
    @SerialName("series_id")
    public val seriesId: String? = null,
    @SerialName("season_number")
    public val seasonNumber: Int? = null,
    @SerialName("episode_number")
    public val episodeNumber: Int? = null,
    @SerialName("air_date")
    public val airDate: String = "",
    @SerialName("air_time")
    public val airTime: String? = null,
    @SerialName("air_at")
    public val airAt: String? = null,
    @SerialName("air_timezone")
    public val airTimezone: String? = null,
    @SerialName("local_air_date")
    public val localAirDate: String = "",
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("poster_thumbhash")
    public val posterThumbhash: String = "",
    @SerialName("watched")
    public val watched: Boolean = false,
    @SerialName("badges")
    public val badges: List<String> = emptyList(),
)

/** Wire type `internal/api/handlers.calendarResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class calendarResponse(
    @SerialName("events")
    public val events: List<calendarDayResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.capabilityAccountChannel`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class capabilityAccountChannel(
    @SerialName("available")
    public val available: Boolean = false,
    @SerialName("modes")
    public val modes: List<String> = emptyList(),
    @SerialName("digest_hour")
    public val digestHour: Int = 0,
)

/** Wire type `internal/api/handlers.capabilityInApp`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class capabilityInApp(
    @SerialName("enabled")
    public val enabled: Boolean = false,
)

/** Wire type `internal/api/handlers.capabilityPromotions`. Direction: response. Dialect: bloem. */
@Serializable
public data class capabilityPromotions(
    @SerialName("surfaces")
    public val surfaces: List<String> = emptyList(),
)

/** Wire type `internal/api/handlers.capabilityPush`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class capabilityPush(
    @SerialName("available")
    public val available: Boolean = false,
    @SerialName("provider")
    public val provider: String = "",
    @SerialName("supported_modes")
    public val supportedModes: List<String> = emptyList(),
)

/** Wire type `internal/api/handlers.capabilityRemoteControl`. Direction: response. Dialect: bloem. */
@Serializable
public data class capabilityRemoteControl(
    @SerialName("admin")
    public val admin: Boolean = false,
    @SerialName("household")
    public val household: Boolean = false,
)

/** Wire type `internal/api/handlers.capabilityResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class capabilityResponse(
    @SerialName("in_app")
    public val inApp: capabilityInApp = capabilityInApp(),
    @SerialName("apple_push")
    public val applePush: capabilityPush = capabilityPush(),
    @SerialName("android_push")
    public val androidPush: capabilityPush = capabilityPush(),
    @SerialName("web_push")
    public val webPush: capabilityWebPush = capabilityWebPush(),
    @SerialName("webhooks")
    public val webhooks: capabilityWebhooks = capabilityWebhooks(),
    @SerialName("email")
    public val email: capabilityAccountChannel = capabilityAccountChannel(),
    @SerialName("discord")
    public val discord: capabilityAccountChannel = capabilityAccountChannel(),
    /** Dialect: bloem. */
    @SerialName("announcements")
    public val announcements: Boolean = false,
    /** Dialect: bloem. */
    @SerialName("supported_types")
    public val supportedTypes: List<String> = emptyList(),
    /** Dialect: bloem. */
    @SerialName("dismiss")
    public val dismiss: Boolean = false,
    /** Dialect: bloem. */
    @SerialName("ambience")
    public val ambience: List<Wire>? = null,
    /** Dialect: bloem. */
    @SerialName("promotions")
    public val promotions: capabilityPromotions? = null,
    /** Dialect: bloem. */
    @SerialName("remote_control")
    public val remoteControl: capabilityRemoteControl = capabilityRemoteControl(),
)

/** Wire type `internal/api/handlers.capabilityWebPush`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class capabilityWebPush(
    @SerialName("available")
    public val available: Boolean = false,
    @SerialName("public_key")
    public val publicKey: String = "",
)

/** Wire type `internal/api/handlers.capabilityWebhooks`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class capabilityWebhooks(
    @SerialName("available")
    public val available: Boolean = false,
    @SerialName("max_per_profile")
    public val maxPerProfile: Int = 0,
    @SerialName("supported_types")
    public val supportedTypes: List<String> = emptyList(),
)

/** Wire type `internal/api/handlers.createProfileRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class createProfileRequest(
    @SerialName("name")
    public val name: String,
    @SerialName("avatar")
    public val avatar: String = "",
    @SerialName("pin")
    public val pin: String = "",
    @SerialName("is_child")
    public val isChild: Boolean,
    @SerialName("max_content_rating")
    public val maxContentRating: String = "",
    @SerialName("quality_preference")
    public val qualityPreference: String = "",
    @SerialName("language")
    public val language: String = "",
    @SerialName("preferred_metadata_language")
    public val preferredMetadataLanguage: String = "",
    @SerialName("subtitle_language")
    public val subtitleLanguage: String = "",
    @SerialName("subtitle_mode")
    public val subtitleMode: String = "",
    @SerialName("auto_skip_intro")
    public val autoSkipIntro: Boolean,
    @SerialName("auto_skip_credits")
    public val autoSkipCredits: Boolean,
    @SerialName("auto_skip_recap")
    public val autoSkipRecap: Boolean,
    @SerialName("auto_play_next_preview")
    public val autoPlayNextPreview: Boolean,
    @SerialName("show_forced_subtitles")
    public val showForcedSubtitles: Boolean? = null,
    @SerialName("library_restrictions_enabled")
    public val libraryRestrictionsEnabled: Boolean,
    @SerialName("allowed_library_ids")
    public val allowedLibraryIds: List<Int>,
    @SerialName("max_playback_quality")
    public val maxPlaybackQuality: String,
)

/** Wire type `internal/api/handlers.createSectionRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class createSectionRequest(
    @SerialName("scope")
    public val scope: String,
    @SerialName("library_id")
    public val libraryId: Int? = null,
    @SerialName("position")
    public val position: Int,
    @SerialName("section_type")
    public val sectionType: String,
    @SerialName("title")
    public val title: String,
    @SerialName("featured")
    public val featured: Boolean,
    @SerialName("item_limit")
    public val itemLimit: Int,
    @SerialName("config")
    public val config: JsonElement? = null,
    @SerialName("enabled")
    public val enabled: Boolean,
)

/** Wire type `internal/api/handlers.createWatchTogetherRoomRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class createWatchTogetherRoomRequest(
    @SerialName("selection_mode")
    public val selectionMode: String = "",
)

/** Wire type `internal/api/handlers.createWatchTogetherSuggestionRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class createWatchTogetherSuggestionRequest(
    @SerialName("content_id")
    public val contentId: String,
    @SerialName("content_type")
    public val contentType: String,
    @SerialName("title")
    public val title: String,
    @SerialName("subtitle")
    public val subtitle: String = "",
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("note")
    public val note: String = "",
)

/** Wire type `internal/api/handlers.deviceDecisionRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class deviceDecisionRequest(
    @SerialName("token")
    public val token: String = "",
    @SerialName("code")
    public val code: String = "",
)

/** Wire type `internal/api/handlers.deviceListResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class deviceListResponse(
    @SerialName("devices")
    public val devices: List<deviceResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.deviceLoginCapabilityResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class deviceLoginCapabilityResponse(
    @SerialName("remote_playback_handoff")
    public val remotePlaybackHandoff: Boolean = false,
    @SerialName("protocol_versions")
    public val protocolVersions: List<Int> = emptyList(),
)

/** Wire type `internal/api/handlers.deviceLookupResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class deviceLookupResponse(
    @SerialName("status")
    public val status: String = "",
    @SerialName("user_code")
    public val userCode: String = "",
    @SerialName("match_code")
    public val matchCode: String = "",
    @SerialName("device_name")
    public val deviceName: String = "",
    @SerialName("device_platform")
    public val devicePlatform: String = "",
    @SerialName("ip_address_hint")
    public val ipAddressHint: String = "",
    @SerialName("expires_at")
    public val expiresAt: String = "",
    @SerialName("client_purpose")
    public val clientPurpose: String = "",
    @SerialName("temporary")
    public val temporary: Boolean = false,
)

/** Wire type `internal/api/handlers.devicePollRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class devicePollRequest(
    @SerialName("device_code")
    public val deviceCode: String,
)

/** Wire type `internal/api/handlers.devicePollResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class devicePollResponse(
    @SerialName("status")
    public val status: String = "",
    @SerialName("poll_after")
    public val pollAfter: Int = 0,
    @SerialName("access_token")
    public val accessToken: String = "",
    @SerialName("refresh_token")
    public val refreshToken: String = "",
    @SerialName("expires_in")
    public val expiresIn: Int = 0,
    @SerialName("user")
    public val user: userResponse? = null,
    @SerialName("profile_id")
    public val profileId: String = "",
    @SerialName("profile_token")
    public val profileToken: String = "",
    @SerialName("temporary")
    public val temporary: Boolean = false,
    @SerialName("session_expires_at")
    public val sessionExpiresAt: String = "",
)

/** Wire type `internal/api/handlers.deviceResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class deviceResponse(
    @SerialName("device_id")
    public val deviceId: String = "",
    @SerialName("device_name")
    public val deviceName: String = "",
    @SerialName("device_platform")
    public val devicePlatform: String = "",
    @SerialName("last_seen_at")
    public val lastSeenAt: String = "",
    @SerialName("profile_id")
    public val profileId: String = "",
    @SerialName("profile_name")
    public val profileName: String = "",
    @SerialName("is_current_device")
    public val isCurrentDevice: Boolean = false,
    @SerialName("changed_count")
    public val changedCount: Int = 0,
)

/** Wire type `internal/api/handlers.deviceStartRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class deviceStartRequest(
    @SerialName("device_name")
    public val deviceName: String,
    @SerialName("device_platform")
    public val devicePlatform: String,
    @SerialName("client_purpose")
    public val clientPurpose: String = "",
    @SerialName("temporary")
    public val temporary: Boolean = false,
)

/** Wire type `internal/api/handlers.deviceStartResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class deviceStartResponse(
    @SerialName("device_code")
    public val deviceCode: String = "",
    @SerialName("user_code")
    public val userCode: String = "",
    @SerialName("match_code")
    public val matchCode: String = "",
    @SerialName("verification_uri")
    public val verificationUri: String = "",
    @SerialName("verification_uri_complete")
    public val verificationUriComplete: String = "",
    @SerialName("expires_at")
    public val expiresAt: String = "",
    @SerialName("expires_in")
    public val expiresIn: Int = 0,
    @SerialName("interval")
    public val interval: Int = 0,
    @SerialName("device_name")
    public val deviceName: String = "",
    @SerialName("device_platform")
    public val devicePlatform: String = "",
    @SerialName("client_purpose")
    public val clientPurpose: String = "",
    @SerialName("temporary")
    public val temporary: Boolean = false,
)

/** Wire type `internal/api/handlers.discoverGenresResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class discoverGenresResponse(
    @SerialName("genres")
    public val genres: List<DiscoverBrandCard> = emptyList(),
)

/** Wire type `internal/api/handlers.discoverNetworksResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class discoverNetworksResponse(
    @SerialName("networks")
    public val networks: List<DiscoverBrandCard> = emptyList(),
)

/** Wire type `internal/api/handlers.discoverResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class discoverResponse(
    @SerialName("rows")
    public val rows: List<discoverRowResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.discoverRowResponse`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class discoverRowResponse(
    @SerialName("type")
    public val type: String = "",
    @SerialName("label")
    public val label: String = "",
    @SerialName("section_kind")
    public val sectionKind: String = "",
    @SerialName("section_key")
    public val sectionKey: String = "",
    @SerialName("items")
    public val items: List<sectionItemResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.discoverSectionsResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class discoverSectionsResponse(
    @SerialName("sections")
    public val sections: List<DiscoverySection> = emptyList(),
)

/** Wire type `internal/api/handlers.discoverStudiosResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class discoverStudiosResponse(
    @SerialName("studios")
    public val studios: List<DiscoverBrandCard> = emptyList(),
)

/** Wire type `internal/api/handlers.downloadCapabilityResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class downloadCapabilityResponse(
    @SerialName("enabled")
    public val enabled: Boolean = false,
    @SerialName("download_allowed")
    public val downloadAllowed: Boolean = false,
    @SerialName("quality_presets")
    public val qualityPresets: List<String> = emptyList(),
    @SerialName("transcode_enabled")
    public val transcodeEnabled: Boolean = false,
    @SerialName("transcode_user_allowed")
    public val transcodeUserAllowed: Boolean = false,
    @SerialName("season_download")
    public val seasonDownload: Boolean = false,
    @SerialName("series_monitoring")
    public val seriesMonitoring: Boolean = false,
    @SerialName("monitoring_modes")
    public val monitoringModes: List<String> = emptyList(),
    @SerialName("proxy_delivery")
    public val proxyDelivery: Boolean = false,
)

/** Wire type `internal/api/handlers.downloadRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class downloadRequest(
    @SerialName("content_id")
    public val contentId: String,
    @SerialName("episode_id")
    public val episodeId: String = "",
    @SerialName("file_id")
    public val fileId: Int = 0,
    @SerialName("quality")
    public val quality: String = "",
    @SerialName("series")
    public val series: Boolean = false,
    @SerialName("season_number")
    public val season: Int? = null,
    @SerialName("caps")
    public val caps: ClientCapabilities? = null,
)

/** Wire type `internal/api/handlers.downloadResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class downloadResponse(
    @SerialName("id")
    public val id: String = "",
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("episode_id")
    public val episodeId: String = "",
    @SerialName("batch_id")
    public val batchId: String = "",
    @SerialName("device_id")
    public val deviceId: String = "",
    @SerialName("media_file_id")
    public val mediaFileId: Int = 0,
    @SerialName("file_size")
    public val fileSize: Long = 0L,
    @SerialName("bytes_sent")
    public val bytesSent: Long = 0L,
    @SerialName("kind")
    public val kind: String = "",
    @SerialName("status")
    public val status: String = "",
    @SerialName("quality")
    public val quality: String = "",
    @SerialName("effective_quality")
    public val effectiveQuality: String = "",
    @SerialName("delivery_format")
    public val deliveryFormat: String = "",
    @SerialName("target_bitrate_kbps")
    public val targetBitrateKbps: Int = 0,
    @SerialName("revision")
    public val revision: Int = 0,
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("completed_at")
    public val completedAt: String? = null,
)

/** Wire type `internal/api/handlers.downloadSubtitleRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class downloadSubtitleRequest(
    @SerialName("media_file_id")
    public val mediaFileId: Int,
    @SerialName("provider")
    public val provider: String,
    @SerialName("subtitle_id")
    public val subtitleId: String,
    @SerialName("language")
    public val language: String,
    @SerialName("release_name")
    public val releaseName: String,
    @SerialName("format")
    public val format: String,
    @SerialName("score")
    public val score: Double,
    @SerialName("hearing_impaired")
    public val hearingImpaired: Boolean,
)

/** Wire type `internal/api/handlers.downloadsListResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class downloadsListResponse(
    @SerialName("downloads")
    public val downloads: List<downloadResponse> = emptyList(),
    @SerialName("skipped")
    public val skipped: List<SkippedDownload> = emptyList(),
)

/** Wire type `internal/api/handlers.episodeFileResponse`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class episodeFileResponse(
    @SerialName("file_id")
    public val fileId: Int = 0,
    @SerialName("resolution")
    public val resolution: String = "",
    @SerialName("codec_video")
    public val codecVideo: String = "",
    @SerialName("hdr")
    public val hdr: Boolean = false,
    @SerialName("audio_channels")
    public val audioChannels: Int = 0,
    @SerialName("container")
    public val container: String = "",
    @SerialName("file_size")
    public val fileSize: Long = 0L,
)

/** Wire type `internal/api/handlers.episodeResponse`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class episodeResponse(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("season_number")
    public val seasonNumber: Int = 0,
    @SerialName("episode_number")
    public val episodeNumber: Int = 0,
    @SerialName("title")
    public val title: String = "",
    @SerialName("overview")
    public val overview: String = "",
    @SerialName("air_date")
    public val airDate: String = "",
    @SerialName("runtime")
    public val runtime: Int = 0,
    @SerialName("imdb_id")
    public val imdbId: String = "",
    @SerialName("tmdb_id")
    public val tmdbId: String = "",
    @SerialName("tvdb_id")
    public val tvdbId: String = "",
    @SerialName("still_url")
    public val stillUrl: String = "",
    @SerialName("still_thumbhash")
    public val stillThumbhash: String = "",
    @SerialName("user_data")
    public val userData: SeasonUserData? = null,
    @SerialName("files")
    public val files: List<episodeFileResponse> = emptyList(),
    @SerialName("overlay_summary")
    public val overlaySummary: OverlaySummary? = null,
)

/** Wire type `internal/api/handlers.episodesListResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class episodesListResponse(
    @SerialName("episodes")
    public val episodes: List<episodeResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.errorResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class errorResponse(
    @SerialName("error")
    public val error: String = "",
    @SerialName("message")
    public val message: String = "",
)

/** Wire type `internal/api/handlers.eventsCapabilityResponse`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class eventsCapabilityResponse(
    @SerialName("schema_version")
    public val schemaVersion: Int = 0,
    @SerialName("subscribe_frame")
    public val subscribeFrame: Boolean = false,
    @SerialName("declared_channels")
    public val declaredChannels: Boolean = false,
    @SerialName("subscribe_grace_period_seconds")
    public val subscribeGracePeriodSeconds: Int = 0,
    @SerialName("max_requested_channels")
    public val maxRequestedChannels: Int = 0,
    @SerialName("channels")
    public val channels: List<EventChannel> = emptyList(),
)

/** Wire type `internal/api/handlers.filterItemsRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class filterItemsRequest(
    @SerialName("match")
    public val match: String,
    @SerialName("groups")
    public val groups: List<FilterGroup>,
    @SerialName("sort")
    public val sort: String = "",
    @SerialName("order")
    public val order: String = "",
    @SerialName("library_id")
    public val libraryId: Int,
    @SerialName("limit")
    public val limit: Int,
    @SerialName("offset")
    public val offset: Int,
)

/** Wire type `internal/api/handlers.forYouMainResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class forYouMainResponse(
    @SerialName("row")
    public val row: ForYouRow? = null,
)

/** Wire type `internal/api/handlers.homeLayoutResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class homeLayoutResponse(
    @SerialName("sections")
    public val sections: List<resolvedSectionLayoutResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.homeSectionItemsResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class homeSectionItemsResponse(
    @SerialName("section")
    public val section: resolvedSectionResponse = resolvedSectionResponse(),
)

/** Wire type `internal/api/handlers.homeSectionsResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class homeSectionsResponse(
    @SerialName("sections")
    public val sections: List<resolvedSectionResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.impersonationResponse`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class impersonationResponse(
    @SerialName("active")
    public val active: Boolean = false,
    @SerialName("impersonator_user_id")
    public val impersonatorUserId: Int = 0,
    @SerialName("impersonator_username")
    public val impersonatorUsername: String = "",
)

/** Wire type `internal/api/handlers.itemFiltersResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class itemFiltersResponse(
    @SerialName("genres")
    public val genres: List<String> = emptyList(),
    @SerialName("studios")
    public val studios: List<String> = emptyList(),
    @SerialName("networks")
    public val networks: List<String> = emptyList(),
    @SerialName("countries")
    public val countries: List<String> = emptyList(),
    @SerialName("content_ratings")
    public val contentRatings: List<String> = emptyList(),
)

/** Wire type `internal/api/handlers.itemListResponse`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class itemListResponse(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("play_content_id")
    public val playContentId: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("series_id")
    public val seriesId: String = "",
    @SerialName("series_title")
    public val seriesTitle: String = "",
    @SerialName("season_number")
    public val seasonNumber: Int? = null,
    @SerialName("episode_number")
    public val episodeNumber: Int? = null,
    @SerialName("year")
    public val year: Int = 0,
    @SerialName("runtime")
    public val runtime: Int = 0,
    @SerialName("genres")
    public val genres: List<String> = emptyList(),
    @SerialName("keywords")
    public val keywords: List<String> = emptyList(),
    @SerialName("studios")
    public val studios: List<String> = emptyList(),
    @SerialName("networks")
    public val networks: List<String> = emptyList(),
    @SerialName("content_rating")
    public val contentRating: String = "",
    @SerialName("status")
    public val status: String = "",
    @SerialName("show_status")
    public val showStatus: String = "",
    @SerialName("rating_imdb")
    public val ratingImdb: Double? = null,
    @SerialName("rating_tmdb")
    public val ratingTmdb: Double? = null,
    @SerialName("rating_rt_critic")
    public val ratingRtCritic: Int? = null,
    @SerialName("rating_rt_audience")
    public val ratingRtAudience: Int? = null,
    @SerialName("original_language")
    public val originalLanguage: String = "",
    @SerialName("overview")
    public val overview: String = "",
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("poster_thumbhash")
    public val posterThumbhash: String = "",
    @SerialName("backdrop_url")
    public val backdropUrl: String = "",
    @SerialName("backdrop_thumbhash")
    public val backdropThumbhash: String = "",
    @SerialName("release_date")
    public val releaseDate: String? = null,
    @SerialName("last_air_date")
    public val lastAirDate: String? = null,
    @SerialName("added_at")
    public val addedAt: String? = null,
    @SerialName("manga_chapter_count")
    public val mangaChapterCount: Int? = null,
    @SerialName("manga_volume_count")
    public val mangaVolumeCount: Int? = null,
    @SerialName("overlay_summary")
    public val overlaySummary: OverlaySummary? = null,
    @SerialName("sort_metrics")
    public val sortMetrics: sortMetricsResponse? = null,
    @SerialName("user_state")
    public val userState: itemUserStateResponse? = null,
    @SerialName("work_id")
    public val workId: String = "",
    @SerialName("work_title")
    public val workTitle: String = "",
    @SerialName("work_formats")
    public val workFormats: List<WorkFormatSummary> = emptyList(),
)

/** Wire type `internal/api/handlers.itemUserStateResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class itemUserStateResponse(
    @SerialName("played")
    public val played: Boolean = false,
    @SerialName("is_favorite")
    public val isFavorite: Boolean = false,
    @SerialName("in_watchlist")
    public val inWatchlist: Boolean = false,
)

/** Wire type `internal/api/handlers.itemsListResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class itemsListResponse(
    @SerialName("items")
    public val items: List<itemListResponse> = emptyList(),
    @SerialName("has_more")
    public val hasMore: Boolean = false,
)

/** Wire type `internal/api/handlers.joinWatchTogetherRoomRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class joinWatchTogetherRoomRequest(
    @SerialName("code")
    public val code: String,
    @SerialName("join_token")
    public val joinToken: String,
)

/** Wire type `internal/api/handlers.loginRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class loginRequest(
    @SerialName("username")
    public val username: String,
    @SerialName("password")
    public val password: String,
    @SerialName("provider")
    public val provider: String = "",
)

/** Wire type `internal/api/handlers.loginResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class loginResponse(
    @SerialName("access_token")
    public val accessToken: String = "",
    @SerialName("refresh_token")
    public val refreshToken: String = "",
    @SerialName("expires_in")
    public val expiresIn: Int = 0,
    @SerialName("user")
    public val user: userResponse = userResponse(),
)

/** Wire type `internal/api/handlers.notificationDismissedPayload`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class notificationDismissedPayload(
    @SerialName("id")
    public val id: String = "",
    @SerialName("profile_id")
    public val profileId: String = "",
)

/** Wire type `internal/api/handlers.notificationListResponse`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class notificationListResponse(
    @SerialName("notifications")
    public val notifications: List<DeliveryRowPayload> = emptyList(),
    @SerialName("next_cursor")
    public val nextCursor: String = "",
)

/** Wire type `internal/api/handlers.notificationReadPayload`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class notificationReadPayload(
    @SerialName("all")
    public val all: Boolean = false,
    @SerialName("id")
    public val id: String = "",
    @SerialName("profile_id")
    public val profileId: String = "",
)

/** Wire type `internal/api/handlers.notificationSyncResponse`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class notificationSyncResponse(
    @SerialName("notifications")
    public val notifications: List<DeliveryRowPayload> = emptyList(),
    @SerialName("next_cursor")
    public val nextCursor: String = "",
    @SerialName("unread_count")
    public val unreadCount: Int = 0,
)

/** Wire type `internal/api/handlers.onboardingProgressRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class onboardingProgressRequest(
    @SerialName("tour_id")
    public val tourId: String,
    @SerialName("last_step")
    public val lastStep: String,
    @SerialName("completed")
    public val completed: Boolean,
    @SerialName("skipped")
    public val skipped: Boolean,
)

/** Wire type `internal/api/handlers.onboardingStateResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class onboardingStateResponse(
    @SerialName("tour_id")
    public val tourId: String = "",
    @SerialName("last_step")
    public val lastStep: String = "",
    @SerialName("completed_at")
    public val completedAt: String = "",
    @SerialName("skipped_at")
    public val skippedAt: String = "",
    @SerialName("done")
    public val done: Boolean = false,
)

/** Wire type `internal/api/handlers.patchDownloadRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class patchDownloadRequest(
    @SerialName("status")
    public val status: String,
)

/** Wire type `internal/api/handlers.patchSubscriptionRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class patchSubscriptionRequest(
    @SerialName("mode")
    public val mode: String? = null,
    @SerialName("season_numbers")
    public val seasonNumbers: List<Int>? = null,
    @SerialName("delete_watched")
    public val deleteWatched: Boolean? = null,
    @SerialName("max_storage_bytes")
    public val maxStorageBytes: Long? = null,
    @SerialName("active")
    public val active: Boolean? = null,
)

/** Wire type `internal/api/handlers.personDetailResponse`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class personDetailResponse(
    @SerialName("id")
    public val id: String = "",
    @SerialName("name")
    public val name: String = "",
    @SerialName("bio")
    public val bio: String = "",
    @SerialName("birth_date")
    public val birthDate: String? = null,
    @SerialName("death_date")
    public val deathDate: String? = null,
    @SerialName("birthplace")
    public val birthplace: String = "",
    @SerialName("photo_url")
    public val photoUrl: String = "",
    @SerialName("filmography")
    public val filmography: List<personFilmographyEntry> = emptyList(),
)

/** Wire type `internal/api/handlers.personFilmographyEntry`. Direction: response. Dialect: bloem. */
@Serializable
public data class personFilmographyEntry(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("kind")
    public val kind: String = "",
    @SerialName("year")
    public val year: Int = 0,
    @SerialName("role")
    public val role: String = "",
    @SerialName("poster_url")
    public val posterUrl: String = "",
)

/** Wire type `internal/api/handlers.personResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class personResponse(
    @SerialName("id")
    public val id: Long = 0L,
    @SerialName("name")
    public val name: String = "",
    @SerialName("bio")
    public val bio: String = "",
    @SerialName("birth_date")
    public val birthDate: String? = null,
    @SerialName("death_date")
    public val deathDate: String? = null,
    @SerialName("birthplace")
    public val birthplace: String = "",
    @SerialName("homepage")
    public val homepage: String = "",
    @SerialName("photo_url")
    public val photoUrl: String = "",
    @SerialName("photo_thumbhash")
    public val photoThumbhash: String = "",
    @SerialName("tmdb_id")
    public val tmdbId: String = "",
    @SerialName("imdb_id")
    public val imdbId: String = "",
    @SerialName("tvdb_id")
    public val tvdbId: String = "",
    @SerialName("plex_guid")
    public val plexGuid: String = "",
)

/** Wire type `internal/api/handlers.profileListResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class profileListResponse(
    @SerialName("profiles")
    public val profiles: List<profileResponse> = emptyList(),
    @SerialName("avatar_upload_enabled")
    public val avatarUploadEnabled: Boolean = false,
)

/** Wire type `internal/api/handlers.profileLoginRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class profileLoginRequest(
    @SerialName("email")
    public val email: String,
    @SerialName("password")
    public val password: String,
    @SerialName("device_id")
    public val deviceId: String,
)

/** Wire type `internal/api/handlers.profileLoginResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class profileLoginResponse(
    @SerialName("access_token")
    public val accessToken: String = "",
    @SerialName("refresh_token")
    public val refreshToken: String = "",
    @SerialName("expires_in")
    public val expiresIn: Int = 0,
    @SerialName("profile_id")
    public val profileId: String = "",
    @SerialName("organization_id")
    public val organizationId: String = "",
    @SerialName("membership_id")
    public val membershipId: String = "",
    @SerialName("policy_revision")
    public val policyRevision: Long = 0L,
    @SerialName("security_revision")
    public val securityRevision: Long = 0L,
    @SerialName("credential_revision")
    public val credentialRevision: Long = 0L,
)

/** Wire type `internal/api/handlers.profileOverrideRequest`. Direction: request. Dialect: upstream-compat. */
@Serializable
public data class profileOverrideRequest(
    @SerialName("id")
    public val id: String,
    @SerialName("section_id")
    public val sectionId: String,
    @SerialName("position")
    public val position: Int? = null,
    @SerialName("hidden")
    public val hidden: Boolean,
    @SerialName("removed")
    public val removed: Boolean,
    @SerialName("section_type")
    public val sectionType: String,
    @SerialName("title")
    public val title: String,
    @SerialName("featured")
    public val featured: Boolean? = null,
    @SerialName("item_limit")
    public val itemLimit: Int? = null,
    @SerialName("config")
    public val config: JsonElement? = null,
    @SerialName("is_user_added")
    public val isUserAdded: Boolean = false,
    @SerialName("user_section_type")
    public val userSectionType: String = "",
    @SerialName("user_config")
    public val userConfig: JsonElement? = null,
    @SerialName("user_title")
    public val userTitle: String = "",
)

/** Wire type `internal/api/handlers.profileResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class profileResponse(
    @SerialName("id")
    public val id: String = "",
    @SerialName("name")
    public val name: String = "",
    @SerialName("avatar")
    public val avatar: String = "",
    @SerialName("avatar_url")
    public val avatarUrl: String = "",
    @SerialName("avatar_source")
    public val avatarSource: String = "",
    @SerialName("has_pin")
    public val hasPin: Boolean = false,
    @SerialName("is_child")
    public val isChild: Boolean = false,
    @SerialName("is_primary")
    public val isPrimary: Boolean = false,
    @SerialName("max_content_rating")
    public val maxContentRating: String = "",
    @SerialName("quality_preference")
    public val qualityPreference: String = "",
    @SerialName("language")
    public val language: String = "",
    @SerialName("preferred_metadata_language")
    public val preferredMetadataLanguage: String = "",
    @SerialName("subtitle_language")
    public val subtitleLanguage: String = "",
    @SerialName("subtitle_mode")
    public val subtitleMode: String = "",
    @SerialName("auto_skip_intro")
    public val autoSkipIntro: Boolean = false,
    @SerialName("auto_skip_credits")
    public val autoSkipCredits: Boolean = false,
    @SerialName("auto_skip_recap")
    public val autoSkipRecap: Boolean = false,
    @SerialName("auto_play_next_preview")
    public val autoPlayNextPreview: Boolean = false,
    @SerialName("show_forced_subtitles")
    public val showForcedSubtitles: Boolean = false,
    @SerialName("library_restrictions_enabled")
    public val libraryRestrictionsEnabled: Boolean = false,
    @SerialName("allowed_library_ids")
    public val allowedLibraryIds: List<Int> = emptyList(),
    @SerialName("max_playback_quality")
    public val maxPlaybackQuality: String = "",
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("updated_at")
    public val updatedAt: String = "",
)

/** Wire type `internal/api/handlers.progressEntryResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class progressEntryResponse(
    @SerialName("media_item_id")
    public val mediaItemId: String = "",
    @SerialName("position_seconds")
    public val positionSeconds: Double = 0.0,
    @SerialName("duration_seconds")
    public val durationSeconds: Double = 0.0,
    @SerialName("completed")
    public val completed: Boolean = false,
    @SerialName("updated_at")
    public val updatedAt: String = "",
)

/** Wire type `internal/api/handlers.progressListResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class progressListResponse(
    @SerialName("progress")
    public val progress: List<progressEntryResponse> = emptyList(),
    @SerialName("next_cursor")
    public val nextCursor: String = "",
)

/** Wire type `internal/api/handlers.promoteSuggestionRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class promoteSuggestionRequest(
    @SerialName("suggestion_id")
    public val suggestionId: String,
)

/** Wire type `internal/api/handlers.promotionsResponse`. Direction: response. Dialect: bloem. Gate: notifications.promotions. Registered root. */
@Serializable
public data class promotionsResponse(
    @SerialName("surface")
    public val surface: String = "",
    @SerialName("promotions")
    public val promotions: List<Card> = emptyList(),
)

/** Wire type `internal/api/handlers.pushDeviceRegisterRequest`. Direction: request. Dialect: bloem. Registered root. */
@Serializable
public data class pushDeviceRegisterRequest(
    @SerialName("platform")
    public val platform: String,
    @SerialName("token")
    public val token: String,
    @SerialName("device_id")
    public val deviceId: String,
    @SerialName("push_mode")
    public val pushMode: String,
)

/** Wire type `internal/api/handlers.ratingListItem`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class ratingListItem(
    @SerialName("media_item_id")
    public val mediaItemId: String = "",
    @SerialName("rating")
    public val rating: Int = 0,
    @SerialName("rated_at")
    public val ratedAt: String = "",
)

/** Wire type `internal/api/handlers.ratingListResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class ratingListResponse(
    @SerialName("ratings")
    public val ratings: List<ratingListItem> = emptyList(),
)

/** Wire type `internal/api/handlers.ratingResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class ratingResponse(
    @SerialName("rating")
    public val rating: Int = 0,
    @SerialName("rated_at")
    public val ratedAt: String = "",
)

/** Wire type `internal/api/handlers.refreshRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class refreshRequest(
    @SerialName("refresh_token")
    public val refreshToken: String,
)

/** Wire type `internal/api/handlers.refreshResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class refreshResponse(
    @SerialName("access_token")
    public val accessToken: String = "",
    @SerialName("refresh_token")
    public val refreshToken: String = "",
    @SerialName("expires_in")
    public val expiresIn: Int = 0,
)

/** Wire type `internal/api/handlers.remoteAuditResponse`. Direction: response. Dialect: bloem. Gate: notifications.remote_control. Registered root. */
@Serializable
public data class remoteAuditResponse(
    @SerialName("commands")
    public val commands: List<Command> = emptyList(),
    @SerialName("limit")
    public val limit: Int = 0,
    @SerialName("offset")
    public val offset: Int = 0,
)

/** Wire type `internal/api/handlers.remoteCapabilityRequest`. Direction: request. Dialect: bloem. Gate: notifications.remote_control. Registered root. */
@Serializable
public data class remoteCapabilityRequest(
    @SerialName("version")
    public val version: Int,
    @SerialName("commands")
    public val commands: List<CommandName>,
)

/** Wire type `internal/api/handlers.remoteCapabilityResponse`. Direction: response. Dialect: bloem. Gate: notifications.remote_control. Registered root. */
@Serializable
public data class remoteCapabilityResponse(
    @SerialName("device_id")
    public val deviceId: String = "",
    @SerialName("version")
    public val version: Int = 0,
    @SerialName("commands")
    public val commands: List<CommandName> = emptyList(),
)

/** Wire type `internal/api/handlers.remoteCommandRequest`. Direction: request. Dialect: bloem. Gate: notifications.remote_control. Registered root. */
@Serializable
public data class remoteCommandRequest(
    @SerialName("name")
    public val name: CommandName,
    @SerialName("payload")
    public val payload: JsonElement? = null,
    @SerialName("reason")
    public val reason: String = "",
    @SerialName("ttl_seconds")
    public val ttlSeconds: Int = 0,
)

/** Wire type `internal/api/handlers.remotePlanSummary`. Direction: response. Dialect: bloem. Gate: notifications.remote_control. */
@Serializable
public data class remotePlanSummary(
    @SerialName("play_method")
    public val playMethod: String = "",
    @SerialName("effective_play_method")
    public val effectivePlayMethod: String = "",
    @SerialName("video_decision")
    public val videoDecision: String = "",
    @SerialName("audio_decision")
    public val audioDecision: String = "",
    @SerialName("source_container")
    public val sourceContainer: String = "",
    @SerialName("source_video_codec")
    public val sourceVideoCodec: String = "",
    @SerialName("source_audio_codec")
    public val sourceAudioCodec: String = "",
    @SerialName("target_video_codec")
    public val targetVideoCodec: String = "",
    @SerialName("target_audio_codec")
    public val targetAudioCodec: String = "",
    @SerialName("target_resolution")
    public val targetResolution: String = "",
    @SerialName("target_bitrate_kbps")
    public val targetBitrateKbps: Int? = null,
    @SerialName("stream_bitrate_kbps")
    public val streamBitrateKbps: Int? = null,
    @SerialName("is_paused")
    public val isPaused: Boolean = false,
    @SerialName("position_seconds")
    public val positionSeconds: Double = 0.0,
)

/** Wire type `internal/api/handlers.remoteSessionControl`. Direction: response. Dialect: bloem. Gate: notifications.remote_control. */
@Serializable
public data class remoteSessionControl(
    @SerialName("device_id")
    public val deviceId: String = "",
    @SerialName("connected")
    public val connected: Boolean = false,
    @SerialName("controllable")
    public val controllable: Boolean = false,
    @SerialName("commands")
    public val commands: List<CommandName> = emptyList(),
)

/** Wire type `internal/api/handlers.remoteSessionRow`. Direction: response. Dialect: bloem. Gate: notifications.remote_control. */
@Serializable
public data class remoteSessionRow(
    @SerialName("session_id")
    public val sessionId: String = "",
    @SerialName("user_id")
    public val userId: Int = 0,
    @SerialName("username")
    public val username: String = "",
    @SerialName("profile_id")
    public val profileId: String = "",
    @SerialName("profile_name")
    public val profileName: String = "",
    @SerialName("media_file_id")
    public val mediaFileId: Int = 0,
    @SerialName("requested_media_file_id")
    public val requestedMediaFileId: Int = 0,
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("media_title")
    public val mediaTitle: String = "",
    @SerialName("media_type")
    public val mediaType: String = "",
    @SerialName("series_name")
    public val seriesName: String = "",
    @SerialName("episode_name")
    public val episodeName: String = "",
    @SerialName("season_number")
    public val seasonNumber: Int? = null,
    @SerialName("episode_number")
    public val episodeNumber: Int? = null,
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("play_method")
    public val playMethod: String = "",
    @SerialName("reporting_node")
    public val reportingNode: String = "",
    @SerialName("node_display_name")
    public val nodeDisplayName: String = "",
    @SerialName("file_duration")
    public val fileDuration: Int? = null,
    @SerialName("started_at")
    public val startedAt: String = "",
    @SerialName("updated_at")
    public val updatedAt: String = "",
    @SerialName("position_seconds")
    public val positionSeconds: Double = 0.0,
    @SerialName("is_paused")
    public val isPaused: Boolean = false,
    @SerialName("has_playback_control")
    public val hasPlaybackControl: Boolean = false,
    @SerialName("client_ip")
    public val clientIp: String = "",
    @SerialName("client_name")
    public val clientName: String = "",
    @SerialName("client_version")
    public val clientVersion: String = "",
    @SerialName("client_build")
    public val clientBuild: String = "",
    @SerialName("client_channel")
    public val clientChannel: String = "",
    @SerialName("client_label")
    public val clientLabel: String = "",
    @SerialName("client_label_full")
    public val clientLabelFull: String = "",
    @SerialName("client_user_agent")
    public val clientUserAgent: String = "",
    @SerialName("audio_track_index")
    public val audioTrackIndex: Int = 0,
    @SerialName("transcode_audio")
    public val transcodeAudio: Boolean = false,
    @SerialName("stream_bitrate_kbps")
    public val streamBitrateKbps: Int? = null,
    @SerialName("target_resolution")
    public val targetResolution: String = "",
    @SerialName("target_video_codec")
    public val targetVideoCodec: String = "",
    @SerialName("target_audio_codec")
    public val targetAudioCodec: String = "",
    @SerialName("target_audio_channels")
    public val targetAudioChannels: Int? = null,
    @SerialName("target_bitrate_kbps")
    public val targetBitrateKbps: Int? = null,
    @SerialName("transcode_hw_accel")
    public val transcodeHwAccel: String = "",
    @SerialName("tone_map_mode")
    public val toneMapMode: String = "",
    @SerialName("source_container")
    public val sourceContainer: String = "",
    @SerialName("source_bitrate_kbps")
    public val sourceBitrateKbps: Int? = null,
    @SerialName("source_video_codec")
    public val sourceVideoCodec: String = "",
    @SerialName("source_video_resolution")
    public val sourceVideoResolution: String = "",
    @SerialName("source_audio_codec")
    public val sourceAudioCodec: String = "",
    @SerialName("source_audio_channels")
    public val sourceAudioChannels: Int? = null,
    @SerialName("source_audio_language")
    public val sourceAudioLanguage: String = "",
    @SerialName("source_audio_title")
    public val sourceAudioTitle: String = "",
    @SerialName("source_audio_layout")
    public val sourceAudioLayout: String = "",
    @SerialName("requested_video_codec")
    public val requestedVideoCodec: String = "",
    @SerialName("requested_video_resolution")
    public val requestedVideoResolution: String = "",
    @SerialName("video_decision")
    public val videoDecision: String = "",
    @SerialName("audio_decision")
    public val audioDecision: String = "",
    @SerialName("effective_play_method")
    public val effectivePlayMethod: String = "",
    @SerialName("is_jellyfin_client")
    public val isJellyfinClient: Boolean = false,
    @SerialName("remote_control")
    public val remoteControl: remoteSessionControl = remoteSessionControl(),
    @SerialName("plan_summary")
    public val planSummary: remotePlanSummary = remotePlanSummary(),
)

/** Wire type `internal/api/handlers.remoteSessionsResponse`. Direction: response. Dialect: bloem. Gate: notifications.remote_control. Registered root. */
@Serializable
public data class remoteSessionsResponse(
    @SerialName("sessions")
    public val sessions: List<remoteSessionRow> = emptyList(),
)

/** Wire type `internal/api/handlers.reorderSectionsRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class reorderSectionsRequest(
    @SerialName("entries")
    public val entries: List<ReorderEntry>,
)

/** Wire type `internal/api/handlers.requestListResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class requestListResponse(
    @SerialName("requests")
    public val requests: List<Request?> = emptyList(),
)

/** Wire type `internal/api/handlers.requestQuotaErrorResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class requestQuotaErrorResponse(
    @SerialName("error")
    public val error: String = "",
    @SerialName("message")
    public val message: String = "",
    @SerialName("used")
    public val used: Int = 0,
    @SerialName("limit")
    public val limit: Int = 0,
    @SerialName("window_days")
    public val windowDays: Int = 0,
)

/** Wire type `internal/api/handlers.requestReasonRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class requestReasonRequest(
    @SerialName("reason")
    public val reason: String,
)

/** Wire type `internal/api/handlers.requestValidationErrorResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class requestValidationErrorResponse(
    @SerialName("error")
    public val error: String = "",
    @SerialName("field_errors")
    public val fieldErrors: Map<String, String> = emptyMap(),
    @SerialName("form_error")
    public val formError: String = "",
)

/** Wire type `internal/api/handlers.resolvedSectionLayoutResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class resolvedSectionLayoutResponse(
    @SerialName("id")
    public val id: String = "",
    @SerialName("section_type")
    public val sectionType: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("featured")
    public val featured: Boolean = false,
    @SerialName("item_limit")
    public val itemLimit: Int = 0,
    @SerialName("is_custom")
    public val isCustom: Boolean = false,
    @SerialName("customized")
    public val customized: Boolean = false,
)

/** Wire type `internal/api/handlers.resolvedSectionResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class resolvedSectionResponse(
    @SerialName("id")
    public val id: String = "",
    @SerialName("section_type")
    public val sectionType: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("featured")
    public val featured: Boolean = false,
    @SerialName("item_limit")
    public val itemLimit: Int = 0,
    @SerialName("total_count")
    public val totalCount: Int = 0,
    @SerialName("is_custom")
    public val isCustom: Boolean = false,
    @SerialName("customized")
    public val customized: Boolean = false,
    @SerialName("items")
    public val items: List<sectionItemResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.resolvedSimilarItem`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class resolvedSimilarItem(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("year")
    public val year: Int = 0,
    @SerialName("runtime_seconds")
    public val runtimeSecond: Int = 0,
    @SerialName("content_rating")
    public val contentRating: String = "",
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("score")
    public val score: Double = 0.0,
    @SerialName("reason")
    public val reason: String = "",
    @SerialName("reason_detail")
    public val reasonDetail: String = "",
)

/** Wire type `internal/api/handlers.resolvedSimilarItemsResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class resolvedSimilarItemsResponse(
    @SerialName("items")
    public val items: List<resolvedSimilarItem> = emptyList(),
)

/** Wire type `internal/api/handlers.restoreDefaultsRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class restoreDefaultsRequest(
    @SerialName("scope")
    public val scope: String,
    @SerialName("library_id")
    public val libraryId: Int? = null,
    @SerialName("reset_profiles")
    public val resetProfiles: Boolean,
)

/** Wire type `internal/api/handlers.saveOverridesRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class saveOverridesRequest(
    @SerialName("scope")
    public val scope: String,
    @SerialName("library_id")
    public val libraryId: String,
    @SerialName("overrides")
    public val overrides: List<profileOverrideRequest>,
)

/** Wire type `internal/api/handlers.scoredItemsResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class scoredItemsResponse(
    @SerialName("items")
    public val items: List<ScoredItem> = emptyList(),
)

/** Wire type `internal/api/handlers.searchSubtitlesRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class searchSubtitlesRequest(
    @SerialName("media_file_id")
    public val mediaFileId: Int,
    @SerialName("languages")
    public val languages: List<String>,
)

/** Wire type `internal/api/handlers.seasonDetailResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class seasonDetailResponse(
    @SerialName("season")
    public val season: seasonResponse = seasonResponse(),
)

/** Wire type `internal/api/handlers.seasonResponse`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class seasonResponse(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("play_content_id")
    public val playContentId: String = "",
    @SerialName("season_number")
    public val seasonNumber: Int = 0,
    @SerialName("is_specials")
    public val isSpecials: Boolean = false,
    @SerialName("title")
    public val title: String = "",
    @SerialName("overview")
    public val overview: String = "",
    @SerialName("air_date")
    public val airDate: String = "",
    @SerialName("episode_count")
    public val episodeCount: Int = 0,
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("poster_thumbhash")
    public val posterThumbhash: String = "",
    @SerialName("user_data")
    public val userData: SeasonUserData? = null,
)

/** Wire type `internal/api/handlers.seasonsResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class seasonsResponse(
    @SerialName("seasons")
    public val seasons: List<seasonResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.sectionDetailResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class sectionDetailResponse(
    @SerialName("kind")
    public val kind: String = "",
    @SerialName("key")
    public val key: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("label")
    public val label: String = "",
    @SerialName("items")
    public val items: List<sectionItemResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.sectionItemResponse`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class sectionItemResponse(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("play_content_id")
    public val playContentId: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("series_id")
    public val seriesId: String = "",
    @SerialName("series_title")
    public val seriesTitle: String = "",
    @SerialName("season_number")
    public val seasonNumber: Int? = null,
    @SerialName("episode_number")
    public val episodeNumber: Int? = null,
    @SerialName("year")
    public val year: Int = 0,
    @SerialName("runtime")
    public val runtime: Int = 0,
    @SerialName("genres")
    public val genres: List<String> = emptyList(),
    @SerialName("keywords")
    public val keywords: List<String> = emptyList(),
    @SerialName("studios")
    public val studios: List<String> = emptyList(),
    @SerialName("networks")
    public val networks: List<String> = emptyList(),
    @SerialName("content_rating")
    public val contentRating: String = "",
    @SerialName("status")
    public val status: String = "",
    @SerialName("show_status")
    public val showStatus: String = "",
    @SerialName("rating_imdb")
    public val ratingImdb: Double? = null,
    @SerialName("rating_tmdb")
    public val ratingTmdb: Double? = null,
    @SerialName("rating_rt_critic")
    public val ratingRtCritic: Int? = null,
    @SerialName("rating_rt_audience")
    public val ratingRtAudience: Int? = null,
    @SerialName("original_language")
    public val originalLanguage: String = "",
    @SerialName("overview")
    public val overview: String = "",
    @SerialName("position_seconds")
    public val positionSeconds: Double? = null,
    @SerialName("duration_seconds")
    public val durationSeconds: Double? = null,
    @SerialName("progress_updated_at")
    public val progressUpdatedAt: String? = null,
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("poster_thumbhash")
    public val posterThumbhash: String = "",
    @SerialName("backdrop_url")
    public val backdropUrl: String = "",
    @SerialName("backdrop_thumbhash")
    public val backdropThumbhash: String = "",
    @SerialName("logo_url")
    public val logoUrl: String = "",
    @SerialName("overlay_summary")
    public val overlaySummary: OverlaySummary? = null,
    @SerialName("badges")
    public val badges: List<String> = emptyList(),
    @SerialName("item_source")
    public val itemSource: String = "",
    @SerialName("user_state")
    public val userState: itemUserStateResponse? = null,
    @SerialName("upcoming_event")
    public val upcomingEvent: upcomingEventResponse? = null,
    @SerialName("promo")
    public val promo: Card? = null,
)

/** Wire type `internal/api/handlers.sectionListResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class sectionListResponse(
    @SerialName("sections")
    public val sections: List<sectionResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.sectionResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class sectionResponse(
    @SerialName("id")
    public val id: String = "",
    @SerialName("scope")
    public val scope: String = "",
    @SerialName("library_id")
    public val libraryId: Int? = null,
    @SerialName("position")
    public val position: Int = 0,
    @SerialName("section_type")
    public val sectionType: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("featured")
    public val featured: Boolean = false,
    @SerialName("item_limit")
    public val itemLimit: Int = 0,
    @SerialName("config")
    public val config: JsonElement? = null,
    @SerialName("enabled")
    public val enabled: Boolean = false,
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("updated_at")
    public val updatedAt: String = "",
)

/** Wire type `internal/api/handlers.sectionSettingsEntry`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class sectionSettingsEntry(
    @SerialName("id")
    public val id: String = "",
    @SerialName("section_type")
    public val sectionType: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("featured")
    public val featured: Boolean = false,
    @SerialName("item_limit")
    public val itemLimit: Int = 0,
    @SerialName("hidden")
    public val hidden: Boolean = false,
    @SerialName("is_custom")
    public val isCustom: Boolean = false,
    @SerialName("customized")
    public val customized: Boolean = false,
    @SerialName("position")
    public val position: Int = 0,
    @SerialName("config")
    public val config: JsonElement? = null,
)

/** Wire type `internal/api/handlers.sectionSettingsResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class sectionSettingsResponse(
    @SerialName("sections")
    public val sections: List<sectionSettingsEntry> = emptyList(),
)

/** Wire type `internal/api/handlers.selectWatchTogetherRoomItemRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class selectWatchTogetherRoomItemRequest(
    @SerialName("content_id")
    public val contentId: String,
    @SerialName("file_id")
    public val fileId: Int? = null,
    @SerialName("library_id")
    public val libraryId: Int? = null,
)

/** Wire type `internal/api/handlers.serverIdentityResponse`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class serverIdentityResponse(
    @SerialName("status")
    public val status: String = "",
    @SerialName("server_id")
    public val serverId: String = "",
    @SerialName("server_name")
    public val serverName: String = "",
    @SerialName("api_versions")
    public val apiVersions: List<Int> = emptyList(),
    @SerialName("bloem_api")
    public val bloemApi: List<String> = emptyList(),
    @SerialName("setup_complete")
    public val setupComplete: Boolean = false,
)

/** Wire type `internal/api/handlers.sessionResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class sessionResponse(
    @SerialName("id")
    public val id: String = "",
    @SerialName("device_name")
    public val deviceName: String = "",
    @SerialName("ip_address")
    public val ipAddress: String = "",
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("expires_at")
    public val expiresAt: String = "",
    @SerialName("revoked_at")
    public val revokedAt: String? = null,
)

/** Wire type `internal/api/handlers.sessionsListResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class sessionsListResponse(
    @SerialName("sessions")
    public val sessions: List<sessionResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.setSubtitlePrefRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class setSubtitlePrefRequest(
    @SerialName("subtitle_language")
    public val subtitleLanguage: String,
    @SerialName("subtitle_track_index")
    public val subtitleTrackIndex: Int,
    @SerialName("external_subtitle_path")
    public val externalSubtitlePath: String = "",
    @SerialName("subtitle_mode")
    public val subtitleMode: String,
    @SerialName("track_signature")
    public val trackSignature: SubtitleTrackSignature? = null,
    @SerialName("show_forced_subtitles")
    public val showForcedSubtitles: Boolean? = null,
)

/** Wire type `internal/api/handlers.setupRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class setupRequest(
    @SerialName("username")
    public val username: String,
    @SerialName("email")
    public val email: String,
    @SerialName("password")
    public val password: String,
    @SerialName("create_default_profile")
    public val createDefaultProfile: Boolean,
    @SerialName("default_profile_name")
    public val defaultProfileName: String = "",
)

/** Wire type `internal/api/handlers.setupStatusResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class setupStatusResponse(
    @SerialName("needs_setup")
    public val needsSetup: Boolean = false,
)

/** Wire type `internal/api/handlers.signupRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class signupRequest(
    @SerialName("username")
    public val username: String,
    @SerialName("email")
    public val email: String,
    @SerialName("password")
    public val password: String,
    @SerialName("invite_code")
    public val inviteCode: String,
    @SerialName("create_default_profile")
    public val createDefaultProfile: Boolean,
    @SerialName("default_profile_name")
    public val defaultProfileName: String = "",
)

/** Wire type `internal/api/handlers.signupStatusResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class signupStatusResponse(
    @SerialName("enabled")
    public val enabled: Boolean = false,
)

/** Wire type `internal/api/handlers.sortMetricsResponse`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class sortMetricsResponse(
    @SerialName("release_date")
    public val releaseDate: String? = null,
    @SerialName("runtime_minutes")
    public val runtimeMinutes: Int? = null,
    @SerialName("resolution")
    public val resolution: String = "",
    @SerialName("bitrate_kbps")
    public val bitrateKbps: Int? = null,
    @SerialName("progress_ratio")
    public val progressRatio: Double? = null,
    @SerialName("viewed_at")
    public val viewedAt: String = "",
    @SerialName("play_count")
    public val playCount: Int? = null,
    @SerialName("author")
    public val author: String = "",
    @SerialName("narrator")
    public val narrator: String = "",
    @SerialName("series_name")
    public val seriesName: String = "",
)

/** Wire type `internal/api/handlers.subscriptionRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class subscriptionRequest(
    @SerialName("series_id")
    public val seriesId: String,
    @SerialName("mode")
    public val mode: String,
    @SerialName("season_numbers")
    public val seasonNumbers: List<Int> = emptyList(),
    @SerialName("delete_watched")
    public val deleteWatched: Boolean = false,
    @SerialName("max_storage_bytes")
    public val maxStorageBytes: Long = 0L,
)

/** Wire type `internal/api/handlers.subscriptionResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class subscriptionResponse(
    @SerialName("id")
    public val id: String = "",
    @SerialName("series_id")
    public val seriesId: String = "",
    @SerialName("mode")
    public val mode: String = "",
    @SerialName("season_numbers")
    public val seasonNumbers: List<Int> = emptyList(),
    @SerialName("target_season")
    public val targetSeason: Int? = null,
    @SerialName("delete_watched")
    public val deleteWatched: Boolean = false,
    @SerialName("max_storage_bytes")
    public val maxStorageBytes: Long = 0L,
    @SerialName("active")
    public val active: Boolean = false,
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("updated_at")
    public val updatedAt: String = "",
)

/** Wire type `internal/api/handlers.subscriptionResultResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class subscriptionResultResponse(
    @SerialName("subscription")
    public val subscription: subscriptionResponse = subscriptionResponse(),
    @SerialName("registered")
    public val registered: Int = 0,
)

/** Wire type `internal/api/handlers.subscriptionSyncResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class subscriptionSyncResponse(
    @SerialName("registered")
    public val registered: Int = 0,
)

/** Wire type `internal/api/handlers.subscriptionsListResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class subscriptionsListResponse(
    @SerialName("subscriptions")
    public val subscriptions: List<subscriptionResponse> = emptyList(),
)

/** Wire type `internal/api/handlers.subtitlePrefResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class subtitlePrefResponse(
    @SerialName("profile_id")
    public val profileId: String = "",
    @SerialName("series_id")
    public val seriesId: String = "",
    @SerialName("subtitle_language")
    public val subtitleLanguage: String = "",
    @SerialName("subtitle_track_index")
    public val subtitleTrackIndex: Int = 0,
    @SerialName("external_subtitle_path")
    public val externalSubtitlePath: String = "",
    @SerialName("subtitle_mode")
    public val subtitleMode: String = "",
    @SerialName("track_signature")
    public val trackSignature: SubtitleTrackSignature? = null,
    @SerialName("show_forced_subtitles")
    public val showForcedSubtitles: Boolean? = null,
    @SerialName("updated_at")
    public val updatedAt: String = "",
)

/** Wire type `internal/api/handlers.subtitleProviderStatusResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class subtitleProviderStatusResponse(
    @SerialName("schema_version")
    public val schemaVersion: Int = 0,
    @SerialName("enabled")
    public val enabled: Boolean = false,
    @SerialName("providers")
    public val providers: List<String> = emptyList(),
)

/** Wire type `internal/api/handlers.syncProgressItem`. Direction: request. Dialect: upstream-compat. */
@Serializable
public data class syncProgressItem(
    @SerialName("media_item_id")
    public val mediaItemId: String,
    @SerialName("position")
    public val position: Double,
    @SerialName("duration")
    public val duration: Double,
    @SerialName("force_overwrite")
    public val forceOverwrite: Boolean,
    @SerialName("updated_at")
    public val updatedAt: String? = null,
)

/** Wire type `internal/api/handlers.syncProgressRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class syncProgressRequest(
    @SerialName("items")
    public val items: List<syncProgressItem>,
)

/** Wire type `internal/api/handlers.syncProgressResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class syncProgressResponse(
    @SerialName("results")
    public val results: List<syncProgressResultItem> = emptyList(),
)

/** Wire type `internal/api/handlers.syncProgressResultItem`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class syncProgressResultItem(
    @SerialName("media_item_id")
    public val mediaItemId: String = "",
    @SerialName("status")
    public val status: String = "",
    @SerialName("error")
    public val error: String = "",
)

/** Wire type `internal/api/handlers.trailerRefreshCapabilityResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class trailerRefreshCapabilityResponse(
    @SerialName("schema_version")
    public val schemaVersion: Int = 0,
    @SerialName("refresh")
    public val refresh: Boolean = false,
    @SerialName("cooldown_seconds")
    public val cooldownSeconds: Int = 0,
    @SerialName("statuses")
    public val statuses: List<String> = emptyList(),
    @SerialName("supported_types")
    public val supportedTypes: List<String> = emptyList(),
)

/** Wire type `internal/api/handlers.trailerRefreshResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class trailerRefreshResponse(
    @SerialName("status")
    public val status: String = "",
    @SerialName("next_allowed_at")
    public val nextAllowedAt: String = "",
)

/** Wire type `internal/api/handlers.unreadCountResponse`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class unreadCountResponse(
    @SerialName("count")
    public val count: Int = 0,
)

/** Wire type `internal/api/handlers.upcomingEventResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class upcomingEventResponse(
    @SerialName("type")
    public val type: String = "",
    @SerialName("air_date")
    public val airDate: String = "",
    @SerialName("air_time")
    public val airTime: String? = null,
    @SerialName("episode_title")
    public val episodeTitle: String? = null,
    @SerialName("season_number")
    public val seasonNumber: Int? = null,
    @SerialName("episode_number")
    public val episodeNumber: Int? = null,
    @SerialName("badges")
    public val badges: List<String> = emptyList(),
)

/** Wire type `internal/api/handlers.updatePreferencesRequest`. Direction: request. Dialect: bloem. Registered root. */
@Serializable
public data class updatePreferencesRequest(
    @SerialName("enabled")
    public val enabled: Boolean? = null,
    @SerialName("notify_favorites")
    public val notifyFavorites: Boolean? = null,
    @SerialName("notify_watchlist")
    public val notifyWatchlist: Boolean? = null,
    @SerialName("notify_continue_watching")
    public val notifyContinueWatching: Boolean? = null,
    @SerialName("notify_next_up")
    public val notifyNextUp: Boolean? = null,
)

/** Wire type `internal/api/handlers.updateProfileRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class updateProfileRequest(
    @SerialName("name")
    public val name: String? = null,
    @SerialName("avatar")
    public val avatar: String? = null,
    @SerialName("pin")
    public val pin: String? = null,
    @SerialName("is_child")
    public val isChild: Boolean? = null,
    @SerialName("max_content_rating")
    public val maxContentRating: String? = null,
    @SerialName("quality_preference")
    public val qualityPreference: String? = null,
    @SerialName("language")
    public val language: String? = null,
    @SerialName("preferred_metadata_language")
    public val preferredMetadataLanguage: String? = null,
    @SerialName("subtitle_language")
    public val subtitleLanguage: String? = null,
    @SerialName("subtitle_mode")
    public val subtitleMode: String? = null,
    @SerialName("auto_skip_intro")
    public val autoSkipIntro: Boolean? = null,
    @SerialName("auto_skip_credits")
    public val autoSkipCredits: Boolean? = null,
    @SerialName("auto_skip_recap")
    public val autoSkipRecap: Boolean? = null,
    @SerialName("auto_play_next_preview")
    public val autoPlayNextPreview: Boolean? = null,
    @SerialName("show_forced_subtitles")
    public val showForcedSubtitles: Boolean? = null,
    @SerialName("library_restrictions_enabled")
    public val libraryRestrictionsEnabled: Boolean? = null,
    @SerialName("allowed_library_ids")
    public val allowedLibraryIds: List<Int>? = null,
    @SerialName("max_playback_quality")
    public val maxPlaybackQuality: String? = null,
)

/** Wire type `internal/api/handlers.updateSectionRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class updateSectionRequest(
    @SerialName("position")
    public val position: Int? = null,
    @SerialName("section_type")
    public val sectionType: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("featured")
    public val featured: Boolean? = null,
    @SerialName("item_limit")
    public val itemLimit: Int? = null,
    @SerialName("config")
    public val config: JsonElement? = null,
    @SerialName("enabled")
    public val enabled: Boolean? = null,
)

/** Wire type `internal/api/handlers.updateWatchTogetherPolicyRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class updateWatchTogetherPolicyRequest(
    @SerialName("guest_control_policy")
    public val guestControlPolicy: GuestControlPolicy,
)

/** Wire type `internal/api/handlers.userLibraryResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class userLibraryResponse(
    @SerialName("id")
    public val id: Int = 0,
    @SerialName("name")
    public val name: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("sort_order")
    public val sortOrder: Int = 0,
    @SerialName("poster_url")
    public val posterUrl: String = "",
)

/** Wire type `internal/api/handlers.userResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class userResponse(
    @SerialName("id")
    public val id: Int = 0,
    @SerialName("username")
    public val username: String = "",
    @SerialName("email")
    public val email: String = "",
    @SerialName("role")
    public val role: String = "",
    @SerialName("permissions")
    public val permissions: List<String> = emptyList(),
    @SerialName("download_allowed")
    public val downloadAllowed: Boolean = false,
    @SerialName("impersonation")
    public val impersonation: impersonationResponse? = null,
)

/** Wire type `internal/api/handlers.verifyPINRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class verifyPINRequest(
    @SerialName("pin")
    public val pin: String,
)

/** Wire type `internal/api/handlers.verifyPINResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class verifyPINResponse(
    @SerialName("valid")
    public val valid: Boolean = false,
    @SerialName("profile_token")
    public val profileToken: String = "",
    @SerialName("expires_at")
    public val expiresAt: String = "",
)

/** Wire type `internal/api/handlers.watchTogetherClientMessage`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class watchTogetherClientMessage(
    @SerialName("type")
    public val type: String,
    @SerialName("owner_generation")
    public val ownerGeneration: Long = 0L,
)

/** Wire type `internal/api/handlers.watchTogetherErrorFrame`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class watchTogetherErrorFrame(
    @SerialName("code")
    public val code: String = "",
    @SerialName("message")
    public val message: String = "",
    @SerialName("type")
    public val type: String = "",
)

/** Wire type `internal/api/handlers.watchTogetherPongFrame`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class watchTogetherPongFrame(
    @SerialName("client_sent_at")
    public val clientSentAt: String = "",
    @SerialName("owner_generation")
    public val ownerGeneration: Long = 0L,
    @SerialName("server_received_at")
    public val serverReceivedAt: String = "",
    @SerialName("server_sent_at")
    public val serverSentAt: String = "",
    @SerialName("type")
    public val type: String = "",
)

/** Wire type `internal/api/handlers.watchTogetherRoomClosedFrame`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class watchTogetherRoomClosedFrame(
    @SerialName("reason")
    public val reason: String = "",
    @SerialName("type")
    public val type: String = "",
)

/** Wire type `internal/api/handlers.watchTogetherRoomResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class watchTogetherRoomResponse(
    @SerialName("room")
    public val room: Snapshot = Snapshot(),
    @SerialName("room_access_token")
    public val roomAccessToken: String = "",
)

/** Wire type `internal/api/handlers.watchTogetherSnapshotFrame`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class watchTogetherSnapshotFrame(
    @SerialName("owner_generation")
    public val ownerGeneration: Long = 0L,
    @SerialName("room")
    public val room: Snapshot = Snapshot(),
    @SerialName("type")
    public val type: String = "",
)

/** Wire type `internal/api/handlers.watchTogetherSuggestionsResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class watchTogetherSuggestionsResponse(
    @SerialName("suggestions")
    public val suggestions: List<Suggestion> = emptyList(),
)

/** Wire type `internal/api/handlers.watchTogetherWSTicketRequest`. Direction: request. Dialect: upstream-compat. Registered root. */
@Serializable
public data class watchTogetherWSTicketRequest(
    @SerialName("room_access_token")
    public val roomAccessToken: String,
)

/** Wire type `internal/api/handlers.watchTonightItemResponse`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class watchTonightItemResponse(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("play_content_id")
    public val playContentId: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("series_id")
    public val seriesId: String = "",
    @SerialName("series_title")
    public val seriesTitle: String = "",
    @SerialName("season_number")
    public val seasonNumber: Int? = null,
    @SerialName("episode_number")
    public val episodeNumber: Int? = null,
    @SerialName("year")
    public val year: Int = 0,
    @SerialName("runtime")
    public val runtime: Int = 0,
    @SerialName("genres")
    public val genres: List<String> = emptyList(),
    @SerialName("keywords")
    public val keywords: List<String> = emptyList(),
    @SerialName("studios")
    public val studios: List<String> = emptyList(),
    @SerialName("networks")
    public val networks: List<String> = emptyList(),
    @SerialName("content_rating")
    public val contentRating: String = "",
    @SerialName("status")
    public val status: String = "",
    @SerialName("show_status")
    public val showStatus: String = "",
    @SerialName("rating_imdb")
    public val ratingImdb: Double? = null,
    @SerialName("rating_tmdb")
    public val ratingTmdb: Double? = null,
    @SerialName("rating_rt_critic")
    public val ratingRtCritic: Int? = null,
    @SerialName("rating_rt_audience")
    public val ratingRtAudience: Int? = null,
    @SerialName("original_language")
    public val originalLanguage: String = "",
    @SerialName("overview")
    public val overview: String = "",
    @SerialName("position_seconds")
    public val positionSeconds: Double? = null,
    @SerialName("duration_seconds")
    public val durationSeconds: Double? = null,
    @SerialName("progress_updated_at")
    public val progressUpdatedAt: String? = null,
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("poster_thumbhash")
    public val posterThumbhash: String = "",
    @SerialName("backdrop_url")
    public val backdropUrl: String = "",
    @SerialName("backdrop_thumbhash")
    public val backdropThumbhash: String = "",
    @SerialName("logo_url")
    public val logoUrl: String = "",
    @SerialName("overlay_summary")
    public val overlaySummary: OverlaySummary? = null,
    @SerialName("badges")
    public val badges: List<String> = emptyList(),
    @SerialName("item_source")
    public val itemSource: String = "",
    @SerialName("user_state")
    public val userState: itemUserStateResponse? = null,
    @SerialName("upcoming_event")
    public val upcomingEvent: upcomingEventResponse? = null,
    @SerialName("promo")
    public val promo: Card? = null,
    @SerialName("watch_tonight_source")
    public val watchTonightSource: String = "",
)

/** Wire type `internal/api/handlers.watchTonightResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class watchTonightResponse(
    @SerialName("items")
    public val items: List<watchTonightItemResponse> = emptyList(),
    @SerialName("is_cold")
    public val isCold: Boolean = false,
)

/** Wire type `internal/api/handlers.watchedStateResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class watchedStateResponse(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("affected_count")
    public val affectedCount: Int = 0,
    @SerialName("played")
    public val played: Boolean = false,
)

/** Wire type `internal/api/handlers.wsTicketResponse`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class wsTicketResponse(
    @SerialName("ticket")
    public val ticket: String = "",
    @SerialName("expires_in")
    public val expiresIn: Int = 0,
)
