// Code generated by cmd/clientdtogen from bloem-server internal/notifications. DO NOT EDIT.
// Server revision: 6b6f13f180e04ad8e0974ac12ea3b6562fd848d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.notifications

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/** Wire type `internal/notifications.AlertCTA`. Direction: response. Dialect: bloem. */
@Serializable
public data class AlertCTA(
    @SerialName("label")
    public val label: String = "",
    @SerialName("url")
    public val url: String = "",
)

/** Wire type `internal/notifications.DeliveryRowPayload`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class DeliveryRowPayload(
    @SerialName("id")
    public val id: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("profile_id")
    public val profileId: String = "",
    @SerialName("library_id")
    public val libraryId: Int? = null,
    @SerialName("series_id")
    public val seriesId: String? = null,
    @SerialName("episode_id")
    public val episodeId: String? = null,
    @SerialName("series_title")
    public val seriesTitle: String = "",
    @SerialName("episode_title")
    public val episodeTitle: String = "",
    @SerialName("season_number")
    public val seasonNumber: Int? = null,
    @SerialName("episode_number")
    public val episodeNumber: Int? = null,
    @SerialName("poster_path")
    public val posterPath: String = "",
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("poster_thumbhash")
    public val posterThumbhash: String = "",
    @SerialName("reason_flags")
    public val reasonFlags: JsonElement? = null,
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("read_at")
    public val readAt: String? = null,
    @SerialName("title")
    public val title: String = "",
    @SerialName("body")
    public val body: String = "",
    @SerialName("severity")
    public val severity: String = "",
    @SerialName("deeplink")
    public val deeplink: String = "",
    @SerialName("image_url")
    public val imageUrl: String = "",
    @SerialName("dismissible")
    public val dismissible: Boolean? = null,
    @SerialName("cta")
    public val cta: AlertCTA? = null,
    @SerialName("expires_at")
    public val expiresAt: String? = null,
    @SerialName("dismissed_at")
    public val dismissedAt: String? = null,
)

/** Wire type `internal/notifications.NotificationDisplay`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class NotificationDisplay(
    @SerialName("delivery_id")
    public val deliveryId: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("body")
    public val body: String = "",
    @SerialName("thread_id")
    public val threadId: String = "",
    @SerialName("category")
    public val category: String = "",
    @SerialName("url")
    public val url: String = "",
)

/** Wire type `internal/notifications.Preferences`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class Preferences(
    @SerialName("profile_id")
    public val profileId: String = "",
    @SerialName("enabled")
    public val enabled: Boolean = false,
    @SerialName("notify_favorites")
    public val notifyFavorites: Boolean = false,
    @SerialName("notify_watchlist")
    public val notifyWatchlist: Boolean = false,
    @SerialName("notify_continue_watching")
    public val notifyContinueWatching: Boolean = false,
    @SerialName("notify_next_up")
    public val notifyNextUp: Boolean = false,
)
