// Code generated by cmd/clientdtogen from bloem-server internal/jellycompat. DO NOT EDIT.
// Server revision: 9f1fd8928444ed5abbdc9c13473ed4311f3599fe (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.jellycompat

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/jellycompat.ConnectInfo`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class ConnectInfo(
    @SerialName("enabled")
    public val enabled: Boolean = false,
    @SerialName("pending_restart")
    public val pendingRestart: Boolean = false,
    @SerialName("public_url")
    public val publicUrl: String = "",
    @SerialName("server_name")
    public val serverName: String = "",
)
