// Code generated by cmd/clientdtogen from bloem-server internal/catalog. DO NOT EDIT.
// Server revision: 55d3ae52f51751e4da769252179e9988a005782e (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/catalog`.
public enum Catalog {
    /// Wire type `internal/catalog.SeasonUserData`. Direction: response. Dialect: upstream-compat.
    public struct SeasonUserData: Codable, Hashable, Sendable {
        public let positionSeconds: Double
        public let durationSeconds: Double
        public let isInProgress: Bool
        public let watchedCount: Int
        public let unplayedCount: Int
        public let inProgressCount: Int
        public let played: Bool
        public let lastFileId: Int?
        public let lastResolution: String?
        public let lastHdr: Bool?
        public let lastCodecVideo: String?
        public let lastEditionKey: String?

        public enum CodingKeys: String, CodingKey {
            case positionSeconds = "position_seconds"
            case durationSeconds = "duration_seconds"
            case isInProgress = "is_in_progress"
            case watchedCount = "watched_count"
            case unplayedCount = "unplayed_count"
            case inProgressCount = "in_progress_count"
            case played = "played"
            case lastFileId = "last_file_id"
            case lastResolution = "last_resolution"
            case lastHdr = "last_hdr"
            case lastCodecVideo = "last_codec_video"
            case lastEditionKey = "last_edition_key"
        }

        public init(
            positionSeconds: Double = 0.0,
            durationSeconds: Double = 0.0,
            isInProgress: Bool = false,
            watchedCount: Int = 0,
            unplayedCount: Int = 0,
            inProgressCount: Int = 0,
            played: Bool = false,
            lastFileId: Int? = nil,
            lastResolution: String? = nil,
            lastHdr: Bool? = nil,
            lastCodecVideo: String? = nil,
            lastEditionKey: String? = nil
        ) {
            self.positionSeconds = positionSeconds
            self.durationSeconds = durationSeconds
            self.isInProgress = isInProgress
            self.watchedCount = watchedCount
            self.unplayedCount = unplayedCount
            self.inProgressCount = inProgressCount
            self.played = played
            self.lastFileId = lastFileId
            self.lastResolution = lastResolution
            self.lastHdr = lastHdr
            self.lastCodecVideo = lastCodecVideo
            self.lastEditionKey = lastEditionKey
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.positionSeconds = try container.decodeIfPresent(Double.self, forKey: .positionSeconds) ?? 0.0
            self.durationSeconds = try container.decodeIfPresent(Double.self, forKey: .durationSeconds) ?? 0.0
            self.isInProgress = try container.decodeIfPresent(Bool.self, forKey: .isInProgress) ?? false
            self.watchedCount = try container.decodeIfPresent(Int.self, forKey: .watchedCount) ?? 0
            self.unplayedCount = try container.decodeIfPresent(Int.self, forKey: .unplayedCount) ?? 0
            self.inProgressCount = try container.decodeIfPresent(Int.self, forKey: .inProgressCount) ?? 0
            self.played = try container.decodeIfPresent(Bool.self, forKey: .played) ?? false
            self.lastFileId = try container.decodeIfPresent(Int.self, forKey: .lastFileId)
            self.lastResolution = try container.decodeIfPresent(String.self, forKey: .lastResolution)
            self.lastHdr = try container.decodeIfPresent(Bool.self, forKey: .lastHdr)
            self.lastCodecVideo = try container.decodeIfPresent(String.self, forKey: .lastCodecVideo)
            self.lastEditionKey = try container.decodeIfPresent(String.self, forKey: .lastEditionKey)
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.positionSeconds, forKey: .positionSeconds)
            try container.encode(self.durationSeconds, forKey: .durationSeconds)
            try container.encode(self.isInProgress, forKey: .isInProgress)
            try container.encode(self.watchedCount, forKey: .watchedCount)
            try container.encode(self.unplayedCount, forKey: .unplayedCount)
            try container.encode(self.inProgressCount, forKey: .inProgressCount)
            try container.encode(self.played, forKey: .played)
            try container.encodeIfPresent(self.lastFileId, forKey: .lastFileId)
            try container.encodeIfPresent(self.lastResolution, forKey: .lastResolution)
            try container.encodeIfPresent(self.lastHdr, forKey: .lastHdr)
            try container.encodeIfPresent(self.lastCodecVideo, forKey: .lastCodecVideo)
            try container.encodeIfPresent(self.lastEditionKey, forKey: .lastEditionKey)
        }
    }

    /// Wire type `internal/catalog.WorkFormatSummary`. Direction: response. Dialect: upstream-compat.
    public struct WorkFormatSummary: Codable, Hashable, Sendable {
        public let type: String
        public let contentId: String
        public let libraryId: Int

        public enum CodingKeys: String, CodingKey {
            case type = "type"
            case contentId = "content_id"
            case libraryId = "library_id"
        }

        public init(
            type: String = "",
            contentId: String = "",
            libraryId: Int = 0
        ) {
            self.type = type
            self.contentId = contentId
            self.libraryId = libraryId
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.type = try container.decodeIfPresent(String.self, forKey: .type) ?? ""
            self.contentId = try container.decodeIfPresent(String.self, forKey: .contentId) ?? ""
            self.libraryId = try container.decodeIfPresent(Int.self, forKey: .libraryId) ?? 0
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.type, forKey: .type)
            try container.encode(self.contentId, forKey: .contentId)
            try container.encode(self.libraryId, forKey: .libraryId)
        }
    }
}
