// Code generated by cmd/clientdtogen from bloem-server internal/promotions. DO NOT EDIT.
// Server revision: 6b6f13f180e04ad8e0974ac12ea3b6562fd848d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/promotions`.
public enum Promotions {
    /// Wire type `internal/promotions.CTA`. Direction: response. Dialect: upstream-compat.
    public struct CTA: Codable, Hashable, Sendable {
        public let label: String
        public let url: String

        public enum CodingKeys: String, CodingKey {
            case label = "label"
            case url = "url"
        }

        public init(
            label: String = "",
            url: String = ""
        ) {
            self.label = label
            self.url = url
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.label = try container.decodeIfPresent(String.self, forKey: .label) ?? ""
            self.url = try container.decodeIfPresent(String.self, forKey: .url) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.label, forKey: .label)
            try container.encode(self.url, forKey: .url)
        }
    }

    /// Wire type `internal/promotions.Card`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct Card: Codable, Hashable, Sendable {
        public let durationSeconds: Int
        public let videoUrl: String
        public let playbackStyle: String
        public let expiresAt: String
        public let id: String
        public let kicker: String
        public let headline: String
        public let subtitle: String
        public let imageUrl: String
        public let deeplink: String
        public let cta: CTA?
        public let dismissible: Bool

        public enum CodingKeys: String, CodingKey {
            case durationSeconds = "duration_seconds"
            case videoUrl = "video_url"
            case playbackStyle = "playback_style"
            case expiresAt = "expires_at"
            case id = "id"
            case kicker = "kicker"
            case headline = "headline"
            case subtitle = "subtitle"
            case imageUrl = "image_url"
            case deeplink = "deeplink"
            case cta = "cta"
            case dismissible = "dismissible"
        }

        public init(
            durationSeconds: Int = 0,
            videoUrl: String = "",
            playbackStyle: String = "",
            expiresAt: String = "",
            id: String = "",
            kicker: String = "",
            headline: String = "",
            subtitle: String = "",
            imageUrl: String = "",
            deeplink: String = "",
            cta: CTA? = nil,
            dismissible: Bool = false
        ) {
            self.durationSeconds = durationSeconds
            self.videoUrl = videoUrl
            self.playbackStyle = playbackStyle
            self.expiresAt = expiresAt
            self.id = id
            self.kicker = kicker
            self.headline = headline
            self.subtitle = subtitle
            self.imageUrl = imageUrl
            self.deeplink = deeplink
            self.cta = cta
            self.dismissible = dismissible
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.durationSeconds = try container.decodeIfPresent(Int.self, forKey: .durationSeconds) ?? 0
            self.videoUrl = try container.decodeIfPresent(String.self, forKey: .videoUrl) ?? ""
            self.playbackStyle = try container.decodeIfPresent(String.self, forKey: .playbackStyle) ?? ""
            self.expiresAt = try container.decodeIfPresent(String.self, forKey: .expiresAt) ?? ""
            self.id = try container.decodeIfPresent(String.self, forKey: .id) ?? ""
            self.kicker = try container.decodeIfPresent(String.self, forKey: .kicker) ?? ""
            self.headline = try container.decodeIfPresent(String.self, forKey: .headline) ?? ""
            self.subtitle = try container.decodeIfPresent(String.self, forKey: .subtitle) ?? ""
            self.imageUrl = try container.decodeIfPresent(String.self, forKey: .imageUrl) ?? ""
            self.deeplink = try container.decodeIfPresent(String.self, forKey: .deeplink) ?? ""
            self.cta = try container.decodeIfPresent(CTA.self, forKey: .cta)
            self.dismissible = try container.decodeIfPresent(Bool.self, forKey: .dismissible) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.durationSeconds, forKey: .durationSeconds)
            try container.encode(self.videoUrl, forKey: .videoUrl)
            try container.encode(self.playbackStyle, forKey: .playbackStyle)
            try container.encode(self.expiresAt, forKey: .expiresAt)
            try container.encode(self.id, forKey: .id)
            try container.encode(self.kicker, forKey: .kicker)
            try container.encode(self.headline, forKey: .headline)
            try container.encode(self.subtitle, forKey: .subtitle)
            try container.encode(self.imageUrl, forKey: .imageUrl)
            try container.encode(self.deeplink, forKey: .deeplink)
            try container.encodeIfPresent(self.cta, forKey: .cta)
            try container.encode(self.dismissible, forKey: .dismissible)
        }
    }
}
