// Code generated by cmd/clientdtogen from bloem-server internal/nativestorage. DO NOT EDIT.
// Server revision: 9a427dc19ce7f25fe03ae97bbdcebe792d0784e2 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/nativestorage`.
public enum Nativestorage {
    /// Wire type `internal/nativestorage.BindResult`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. Registered root.
    public struct BindResult: Codable, Hashable, Sendable {
        public let bindingId: String
        public let sourceKey: String
        public let folderId: Int
        public let sourceRevision: Int64
        public let libraryRevision: Int64
        public let repeated: Bool

        public enum CodingKeys: String, CodingKey {
            case bindingId = "binding_id"
            case sourceKey = "source_key"
            case folderId = "folder_id"
            case sourceRevision = "source_revision"
            case libraryRevision = "library_revision"
            case repeated = "repeated"
        }

        public init(
            bindingId: String = "",
            sourceKey: String = "",
            folderId: Int = 0,
            sourceRevision: Int64 = 0,
            libraryRevision: Int64 = 0,
            repeated: Bool = false
        ) {
            self.bindingId = bindingId
            self.sourceKey = sourceKey
            self.folderId = folderId
            self.sourceRevision = sourceRevision
            self.libraryRevision = libraryRevision
            self.repeated = repeated
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.bindingId = try container.decodeIfPresent(String.self, forKey: .bindingId) ?? ""
            self.sourceKey = try container.decodeIfPresent(String.self, forKey: .sourceKey) ?? ""
            self.folderId = try container.decodeIfPresent(Int.self, forKey: .folderId) ?? 0
            self.sourceRevision = try container.decodeIfPresent(Int64.self, forKey: .sourceRevision) ?? 0
            self.libraryRevision = try container.decodeIfPresent(Int64.self, forKey: .libraryRevision) ?? 0
            self.repeated = try container.decodeIfPresent(Bool.self, forKey: .repeated) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.bindingId, forKey: .bindingId)
            try container.encode(self.sourceKey, forKey: .sourceKey)
            try container.encode(self.folderId, forKey: .folderId)
            try container.encode(self.sourceRevision, forKey: .sourceRevision)
            try container.encode(self.libraryRevision, forKey: .libraryRevision)
            try container.encode(self.repeated, forKey: .repeated)
        }
    }

    /// Wire type `internal/nativestorage.InstallCommand`. Direction: request. Dialect: bloem. Gate: native_storage.source_management. Registered root.
    public struct InstallCommand: Codable, Hashable, Sendable {
        public let artifactKey: String
        public let providerSourceId: String
        public let rootEntryId: String
        public let enabled: Bool
        public let sourceKey: String?
        public let organizationId: String?
        public let expectedRevision: Int64?
        public let config: [String: [String: BloemJSONValue]]

        public enum CodingKeys: String, CodingKey {
            case artifactKey = "artifact_key"
            case providerSourceId = "provider_source_id"
            case rootEntryId = "root_entry_id"
            case enabled = "enabled"
            case sourceKey = "source_key"
            case organizationId = "organization_id"
            case expectedRevision = "expected_revision"
            case config = "config"
        }

        public init(
            artifactKey: String,
            providerSourceId: String,
            rootEntryId: String,
            enabled: Bool,
            sourceKey: String? = nil,
            organizationId: String? = nil,
            expectedRevision: Int64? = nil,
            config: [String: [String: BloemJSONValue]]
        ) {
            self.artifactKey = artifactKey
            self.providerSourceId = providerSourceId
            self.rootEntryId = rootEntryId
            self.enabled = enabled
            self.sourceKey = sourceKey
            self.organizationId = organizationId
            self.expectedRevision = expectedRevision
            self.config = config
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.artifactKey = try container.decode(String.self, forKey: .artifactKey)
            self.providerSourceId = try container.decode(String.self, forKey: .providerSourceId)
            self.rootEntryId = try container.decode(String.self, forKey: .rootEntryId)
            self.enabled = try container.decode(Bool.self, forKey: .enabled)
            self.sourceKey = try container.decodeIfPresent(String.self, forKey: .sourceKey)
            self.organizationId = try container.decodeIfPresent(String.self, forKey: .organizationId)
            self.expectedRevision = try container.decodeIfPresent(Int64.self, forKey: .expectedRevision)
            self.config = try container.decode([String: [String: BloemJSONValue]].self, forKey: .config)
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.artifactKey, forKey: .artifactKey)
            try container.encode(self.providerSourceId, forKey: .providerSourceId)
            try container.encode(self.rootEntryId, forKey: .rootEntryId)
            try container.encode(self.enabled, forKey: .enabled)
            try container.encodeIfPresent(self.sourceKey, forKey: .sourceKey)
            try container.encodeIfPresent(self.organizationId, forKey: .organizationId)
            try container.encodeIfPresent(self.expectedRevision, forKey: .expectedRevision)
            try container.encode(self.config, forKey: .config)
        }
    }

    /// Wire type `internal/nativestorage.LibraryPage`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. Registered root.
    public struct LibraryPage: Codable, Hashable, Sendable {
        public let libraries: [LibraryStatus]
        public let nextAfter: Int?

        public enum CodingKeys: String, CodingKey {
            case libraries = "libraries"
            case nextAfter = "next_after"
        }

        public init(
            libraries: [LibraryStatus] = [],
            nextAfter: Int? = nil
        ) {
            self.libraries = libraries
            self.nextAfter = nextAfter
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.libraries = try container.decodeIfPresent([LibraryStatus].self, forKey: .libraries) ?? []
            self.nextAfter = try container.decodeIfPresent(Int.self, forKey: .nextAfter)
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.libraries, forKey: .libraries)
            try container.encodeIfPresent(self.nextAfter, forKey: .nextAfter)
        }
    }

    /// Wire type `internal/nativestorage.LibraryStatus`. Direction: response. Dialect: bloem. Gate: native_storage.source_management.
    public struct LibraryStatus: Codable, Hashable, Sendable {
        public let libraryId: Int
        public let creationKey: String
        public let libraryRevision: Int64
        public let mode: String
        public let initialized: Bool
        public let state: String
        public let bindingId: String?
        public let sourceKey: String?
        public let sourceRevision: Int64?
        public let sourceAvailability: String
        public let supportedOperations: [String: Bool]
        public let readyToQueue: Bool

        public enum CodingKeys: String, CodingKey {
            case libraryId = "library_id"
            case creationKey = "creation_key"
            case libraryRevision = "library_revision"
            case mode = "mode"
            case initialized = "initialized"
            case state = "state"
            case bindingId = "binding_id"
            case sourceKey = "source_key"
            case sourceRevision = "source_revision"
            case sourceAvailability = "source_availability"
            case supportedOperations = "supported_operations"
            case readyToQueue = "ready_to_queue"
        }

        public init(
            libraryId: Int = 0,
            creationKey: String = "",
            libraryRevision: Int64 = 0,
            mode: String = "",
            initialized: Bool = false,
            state: String = "",
            bindingId: String? = nil,
            sourceKey: String? = nil,
            sourceRevision: Int64? = nil,
            sourceAvailability: String = "",
            supportedOperations: [String: Bool] = [:],
            readyToQueue: Bool = false
        ) {
            self.libraryId = libraryId
            self.creationKey = creationKey
            self.libraryRevision = libraryRevision
            self.mode = mode
            self.initialized = initialized
            self.state = state
            self.bindingId = bindingId
            self.sourceKey = sourceKey
            self.sourceRevision = sourceRevision
            self.sourceAvailability = sourceAvailability
            self.supportedOperations = supportedOperations
            self.readyToQueue = readyToQueue
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.libraryId = try container.decodeIfPresent(Int.self, forKey: .libraryId) ?? 0
            self.creationKey = try container.decodeIfPresent(String.self, forKey: .creationKey) ?? ""
            self.libraryRevision = try container.decodeIfPresent(Int64.self, forKey: .libraryRevision) ?? 0
            self.mode = try container.decodeIfPresent(String.self, forKey: .mode) ?? ""
            self.initialized = try container.decodeIfPresent(Bool.self, forKey: .initialized) ?? false
            self.state = try container.decodeIfPresent(String.self, forKey: .state) ?? ""
            self.bindingId = try container.decodeIfPresent(String.self, forKey: .bindingId)
            self.sourceKey = try container.decodeIfPresent(String.self, forKey: .sourceKey)
            self.sourceRevision = try container.decodeIfPresent(Int64.self, forKey: .sourceRevision)
            self.sourceAvailability = try container.decodeIfPresent(String.self, forKey: .sourceAvailability) ?? ""
            self.supportedOperations = try container.decodeIfPresent([String: Bool].self, forKey: .supportedOperations) ?? [:]
            self.readyToQueue = try container.decodeIfPresent(Bool.self, forKey: .readyToQueue) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.libraryId, forKey: .libraryId)
            try container.encode(self.creationKey, forKey: .creationKey)
            try container.encode(self.libraryRevision, forKey: .libraryRevision)
            try container.encode(self.mode, forKey: .mode)
            try container.encode(self.initialized, forKey: .initialized)
            try container.encode(self.state, forKey: .state)
            try container.encodeIfPresent(self.bindingId, forKey: .bindingId)
            try container.encodeIfPresent(self.sourceKey, forKey: .sourceKey)
            try container.encodeIfPresent(self.sourceRevision, forKey: .sourceRevision)
            try container.encode(self.sourceAvailability, forKey: .sourceAvailability)
            try container.encode(self.supportedOperations, forKey: .supportedOperations)
            try container.encode(self.readyToQueue, forKey: .readyToQueue)
        }
    }

    /// Wire type `internal/nativestorage.ScanResult`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. Registered root.
    public struct ScanResult: Codable, Hashable, Sendable {
        public let libraryId: Int
        public let scanRunId: String
        public let mode: String
        public let state: String
        public let created: Bool
        public let libraryRevision: Int64
        public let sourceRevision: Int64

        public enum CodingKeys: String, CodingKey {
            case libraryId = "library_id"
            case scanRunId = "scan_run_id"
            case mode = "mode"
            case state = "state"
            case created = "created"
            case libraryRevision = "library_revision"
            case sourceRevision = "source_revision"
        }

        public init(
            libraryId: Int = 0,
            scanRunId: String = "",
            mode: String = "",
            state: String = "",
            created: Bool = false,
            libraryRevision: Int64 = 0,
            sourceRevision: Int64 = 0
        ) {
            self.libraryId = libraryId
            self.scanRunId = scanRunId
            self.mode = mode
            self.state = state
            self.created = created
            self.libraryRevision = libraryRevision
            self.sourceRevision = sourceRevision
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.libraryId = try container.decodeIfPresent(Int.self, forKey: .libraryId) ?? 0
            self.scanRunId = try container.decodeIfPresent(String.self, forKey: .scanRunId) ?? ""
            self.mode = try container.decodeIfPresent(String.self, forKey: .mode) ?? ""
            self.state = try container.decodeIfPresent(String.self, forKey: .state) ?? ""
            self.created = try container.decodeIfPresent(Bool.self, forKey: .created) ?? false
            self.libraryRevision = try container.decodeIfPresent(Int64.self, forKey: .libraryRevision) ?? 0
            self.sourceRevision = try container.decodeIfPresent(Int64.self, forKey: .sourceRevision) ?? 0
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.libraryId, forKey: .libraryId)
            try container.encode(self.scanRunId, forKey: .scanRunId)
            try container.encode(self.mode, forKey: .mode)
            try container.encode(self.state, forKey: .state)
            try container.encode(self.created, forKey: .created)
            try container.encode(self.libraryRevision, forKey: .libraryRevision)
            try container.encode(self.sourceRevision, forKey: .sourceRevision)
        }
    }

    /// Wire type `internal/nativestorage.SourcePage`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. Registered root.
    public struct SourcePage: Codable, Hashable, Sendable {
        public let sources: [SourceView]
        public let nextAfter: String?

        public enum CodingKeys: String, CodingKey {
            case sources = "sources"
            case nextAfter = "next_after"
        }

        public init(
            sources: [SourceView] = [],
            nextAfter: String? = nil
        ) {
            self.sources = sources
            self.nextAfter = nextAfter
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.sources = try container.decodeIfPresent([SourceView].self, forKey: .sources) ?? []
            self.nextAfter = try container.decodeIfPresent(String.self, forKey: .nextAfter)
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.sources, forKey: .sources)
            try container.encodeIfPresent(self.nextAfter, forKey: .nextAfter)
        }
    }

    /// Wire type `internal/nativestorage.SourceView`. Direction: response. Dialect: bloem. Gate: native_storage.source_management.
    public struct SourceView: Codable, Hashable, Sendable {
        public let sourceKey: String
        public let ownerKind: Resourcetenancy.OwnerKind
        public let organizationId: String?
        public let installationId: Int64?
        public let pluginId: String
        public let providerSourceId: String
        public let rootEntryId: String
        public let configurationRevision: Int64
        public let enabled: Bool
        public let state: String
        public let configured: Bool

        public enum CodingKeys: String, CodingKey {
            case sourceKey = "source_key"
            case ownerKind = "owner_kind"
            case organizationId = "organization_id"
            case installationId = "installation_id"
            case pluginId = "plugin_id"
            case providerSourceId = "provider_source_id"
            case rootEntryId = "root_entry_id"
            case configurationRevision = "configuration_revision"
            case enabled = "enabled"
            case state = "state"
            case configured = "configured"
        }

        public init(
            sourceKey: String = "",
            ownerKind: Resourcetenancy.OwnerKind = Resourcetenancy.OwnerKind(rawValue: ""),
            organizationId: String? = nil,
            installationId: Int64? = nil,
            pluginId: String = "",
            providerSourceId: String = "",
            rootEntryId: String = "",
            configurationRevision: Int64 = 0,
            enabled: Bool = false,
            state: String = "",
            configured: Bool = false
        ) {
            self.sourceKey = sourceKey
            self.ownerKind = ownerKind
            self.organizationId = organizationId
            self.installationId = installationId
            self.pluginId = pluginId
            self.providerSourceId = providerSourceId
            self.rootEntryId = rootEntryId
            self.configurationRevision = configurationRevision
            self.enabled = enabled
            self.state = state
            self.configured = configured
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.sourceKey = try container.decodeIfPresent(String.self, forKey: .sourceKey) ?? ""
            self.ownerKind = try container.decodeIfPresent(Resourcetenancy.OwnerKind.self, forKey: .ownerKind) ?? Resourcetenancy.OwnerKind(rawValue: "")
            self.organizationId = try container.decodeIfPresent(String.self, forKey: .organizationId)
            self.installationId = try container.decodeIfPresent(Int64.self, forKey: .installationId)
            self.pluginId = try container.decodeIfPresent(String.self, forKey: .pluginId) ?? ""
            self.providerSourceId = try container.decodeIfPresent(String.self, forKey: .providerSourceId) ?? ""
            self.rootEntryId = try container.decodeIfPresent(String.self, forKey: .rootEntryId) ?? ""
            self.configurationRevision = try container.decodeIfPresent(Int64.self, forKey: .configurationRevision) ?? 0
            self.enabled = try container.decodeIfPresent(Bool.self, forKey: .enabled) ?? false
            self.state = try container.decodeIfPresent(String.self, forKey: .state) ?? ""
            self.configured = try container.decodeIfPresent(Bool.self, forKey: .configured) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.sourceKey, forKey: .sourceKey)
            try container.encode(self.ownerKind, forKey: .ownerKind)
            try container.encodeIfPresent(self.organizationId, forKey: .organizationId)
            try container.encodeIfPresent(self.installationId, forKey: .installationId)
            try container.encode(self.pluginId, forKey: .pluginId)
            try container.encode(self.providerSourceId, forKey: .providerSourceId)
            try container.encode(self.rootEntryId, forKey: .rootEntryId)
            try container.encode(self.configurationRevision, forKey: .configurationRevision)
            try container.encode(self.enabled, forKey: .enabled)
            try container.encode(self.state, forKey: .state)
            try container.encode(self.configured, forKey: .configured)
        }
    }
}
