// Code generated by cmd/clientdtogen from bloem-server cmd/clientdtogen/internal/graph/graphtest/graphtest.go. DO NOT EDIT.
// Server revision: 0000000000000000000000000000000000000000 (generator v1, registry cmd/clientdtogen/internal/graph/graphtest/graphtest.go)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract

/** Provenance of the generated contract and per-type registry metadata, as tables. */
public object GeneratedContract {
    public const val SERVER_REVISION: String = "0000000000000000000000000000000000000000"
    public const val GENERATOR_VERSION: Int = 1
    /** Digest of the normalised type graph; changes only when a wire shape changes. */
    public const val CONTRACT_DIGEST: String = "sha256:b4faceed6040aafc310ee3a69c6094345834ec33cf960060dd73486f576f8064"
    /** Fully qualified class name → direction (request, response or both). */
    public val DIRECTION: Map<String, String> = mapOf(
        "org.bloemserver.bloem.contract.fixture.BloemOnly" to "both",
        "org.bloemserver.bloem.contract.fixture.Child" to "both",
        "org.bloemserver.bloem.contract.fixture.Collections" to "response",
        "org.bloemserver.bloem.contract.fixture.Compat" to "response",
        "org.bloemserver.bloem.contract.fixture.Embedded" to "request",
        "org.bloemserver.bloem.contract.fixture.Gated" to "response",
        "org.bloemserver.bloem.contract.fixture.Gated2" to "response",
        "org.bloemserver.bloem.contract.fixture.GatedChild" to "response",
        "org.bloemserver.bloem.contract.fixture.GatedOnly" to "response",
        "org.bloemserver.bloem.contract.fixture.Inner" to "request",
        "org.bloemserver.bloem.contract.fixture.PromoCard" to "both",
        "org.bloemserver.bloem.contract.fixture.Protocol" to "both",
        "org.bloemserver.bloem.contract.fixture.Request" to "request",
        "org.bloemserver.bloem.contract.fixture.Response" to "response",
        "org.bloemserver.bloem.contract.fixture.Scalars" to "response",
        "org.bloemserver.bloem.contract.fixture.Shared" to "both",
        "org.bloemserver.bloem.contract.other.Standalone" to "request",
        "org.bloemserver.bloem.contract.other.Target" to "response",
    )
    /** Fully qualified class name → dialect (upstream-compat or bloem), from the registry. */
    public val DIALECT: Map<String, String> = mapOf(
        "org.bloemserver.bloem.contract.fixture.BloemOnly" to "bloem",
        "org.bloemserver.bloem.contract.fixture.Child" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.Collections" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.Compat" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.Embedded" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.Gated" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.Gated2" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.GatedChild" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.GatedOnly" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.Inner" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.PromoCard" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.Protocol" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.Request" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.Response" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.Scalars" to "upstream-compat",
        "org.bloemserver.bloem.contract.fixture.Shared" to "upstream-compat",
        "org.bloemserver.bloem.contract.other.Standalone" to "bloem",
        "org.bloemserver.bloem.contract.other.Target" to "upstream-compat",
    )
    /** Fully qualified class name → capability gates, for gated types only; any one of the "|"-separated gates suffices. */
    public val GATE: Map<String, String> = mapOf(
        "org.bloemserver.bloem.contract.fixture.BloemOnly" to "cap.bloem",
        "org.bloemserver.bloem.contract.fixture.Gated" to "cap.gated",
        "org.bloemserver.bloem.contract.fixture.Gated2" to "cap.other",
        "org.bloemserver.bloem.contract.fixture.GatedOnly" to "cap.gated|cap.other",
        "org.bloemserver.bloem.contract.other.Standalone" to "cap.alias",
    )
}
