// Code generated by cmd/clientdtogen from bloem-server internal/downloads. DO NOT EDIT.
// Server revision: c11744b55dea1eadb50df15d8f75ff824a159810 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.downloads

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/downloads.SkippedDownload`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class SkippedDownload(
    @SerialName("episode_id")
    public val episodeId: String = "",
    @SerialName("reason")
    public val reason: String = "",
)
