// Code generated by cmd/clientdtogen from bloem-server internal/downloads. DO NOT EDIT.
// Server revision: 9dca6ac01cc6f1395ec124a57674e835b7169bf8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.downloads

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/downloads.SkippedDownload`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class SkippedDownload(
    @SerialName("episode_id")
    public val episodeId: String = "",
    @SerialName("reason")
    public val reason: String = "",
)
