// Code generated by cmd/clientdtogen from bloem-server internal/sections. DO NOT EDIT.
// Server revision: 55d3ae52f51751e4da769252179e9988a005782e (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/sections`.
public enum Sections {
    /// Wire type `internal/sections.FilterGroup`. Direction: request. Dialect: upstream-compat.
    public struct FilterGroup: Codable, Hashable, Sendable {
        public let match: String
        public let rules: [FilterRule]

        public enum CodingKeys: String, CodingKey {
            case match = "match"
            case rules = "rules"
        }

        public init(
            match: String,
            rules: [FilterRule]
        ) {
            self.match = match
            self.rules = rules
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.match = try container.decode(String.self, forKey: .match)
            self.rules = try container.decode([FilterRule].self, forKey: .rules)
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.match, forKey: .match)
            try container.encode(self.rules, forKey: .rules)
        }
    }

    /// Wire type `internal/sections.FilterRule`. Direction: request. Dialect: upstream-compat.
    public struct FilterRule: Codable, Hashable, Sendable {
        public let field: String
        public let op: String
        public let value: BloemJSONValue?

        public enum CodingKeys: String, CodingKey {
            case field = "field"
            case op = "op"
            case value = "value"
        }

        public init(
            field: String,
            op: String,
            value: BloemJSONValue? = nil
        ) {
            self.field = field
            self.op = op
            self.value = value
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.field = try container.decode(String.self, forKey: .field)
            self.op = try container.decode(String.self, forKey: .op)
            self.value = try container.decodeIfPresent(BloemJSONValue.self, forKey: .value)
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.field, forKey: .field)
            try container.encode(self.op, forKey: .op)
            try container.encodeIfPresent(self.value, forKey: .value)
        }
    }

    /// Wire type `internal/sections.ReorderEntry`. Direction: request. Dialect: upstream-compat.
    public struct ReorderEntry: Codable, Hashable, Sendable {
        public let id: String
        public let position: Int

        public enum CodingKeys: String, CodingKey {
            case id = "id"
            case position = "position"
        }

        public init(
            id: String,
            position: Int
        ) {
            self.id = id
            self.position = position
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.id = try container.decode(String.self, forKey: .id)
            self.position = try container.decode(Int.self, forKey: .position)
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.id, forKey: .id)
            try container.encode(self.position, forKey: .position)
        }
    }
}
