// Code generated by cmd/clientdtogen from bloem-server internal/ambience. DO NOT EDIT.
// Server revision: 6b6f13f180e04ad8e0974ac12ea3b6562fd848d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.ambience

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/ambience.Assets`. Direction: response. Dialect: bloem. */
@Serializable
public data class Assets(
    @SerialName("banner_url")
    public val bannerUrl: String = "",
    @SerialName("sprites")
    public val sprites: List<String> = emptyList(),
)

/** Wire type `internal/ambience.Window`. Direction: response. Dialect: bloem. */
@Serializable
public data class Window(
    @SerialName("starts_at")
    public val startsAt: String = "",
    @SerialName("repeat_yearly")
    public val repeatYearly: Boolean = false,
    @SerialName("timezone")
    public val timezone: String = "",
    @SerialName("ends_at")
    public val endsAt: String = "",
)

/** Wire type `internal/ambience.Wire`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class Wire(
    @SerialName("id")
    public val id: String = "",
    @SerialName("effect_id")
    public val effectId: String = "",
    @SerialName("window")
    public val window: Window = Window(),
    @SerialName("intensity")
    public val intensity: Double = 0.0,
    @SerialName("surfaces")
    public val surfaces: List<String> = emptyList(),
    @SerialName("assets")
    public val assets: Assets = Assets(),
)
