// Code generated by cmd/clientdtogen from bloem-server internal/nativestorage. DO NOT EDIT.
// Server revision: c87b44545228c93f909275c0b5c4fc1d6a289e1b (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.nativestorage

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import org.bloemserver.bloem.contract.resourcetenancy.OwnerKind

/** Wire type `internal/nativestorage.BindResult`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. Registered root. */
@Serializable
public data class BindResult(
    @SerialName("binding_id")
    public val bindingId: String = "",
    @SerialName("source_key")
    public val sourceKey: String = "",
    @SerialName("folder_id")
    public val folderId: Int = 0,
    @SerialName("source_revision")
    public val sourceRevision: Long = 0L,
    @SerialName("library_revision")
    public val libraryRevision: Long = 0L,
    @SerialName("repeated")
    public val repeated: Boolean = false,
)

/** Wire type `internal/nativestorage.InstallCommand`. Direction: request. Dialect: bloem. Gate: native_storage.source_management. Registered root. */
@Serializable
public data class InstallCommand(
    @SerialName("artifact_key")
    public val artifactKey: String,
    @SerialName("provider_source_id")
    public val providerSourceId: String,
    @SerialName("root_entry_id")
    public val rootEntryId: String,
    @SerialName("enabled")
    public val enabled: Boolean,
    @SerialName("source_key")
    public val sourceKey: String? = null,
    @SerialName("organization_id")
    public val organizationId: String? = null,
    @SerialName("expected_revision")
    public val expectedRevision: Long? = null,
    @SerialName("config")
    public val config: Map<String, Map<String, JsonElement>>,
)

/** Wire type `internal/nativestorage.LibraryPage`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. Registered root. */
@Serializable
public data class LibraryPage(
    @SerialName("libraries")
    public val libraries: List<LibraryStatus> = emptyList(),
    @SerialName("next_after")
    public val nextAfter: Int? = null,
)

/** Wire type `internal/nativestorage.LibraryStatus`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. */
@Serializable
public data class LibraryStatus(
    @SerialName("library_id")
    public val libraryId: Int = 0,
    @SerialName("creation_key")
    public val creationKey: String = "",
    @SerialName("library_revision")
    public val libraryRevision: Long = 0L,
    @SerialName("mode")
    public val mode: String = "",
    @SerialName("initialized")
    public val initialized: Boolean = false,
    @SerialName("state")
    public val state: String = "",
    @SerialName("binding_id")
    public val bindingId: String? = null,
    @SerialName("source_key")
    public val sourceKey: String? = null,
    @SerialName("source_revision")
    public val sourceRevision: Long? = null,
    @SerialName("source_availability")
    public val sourceAvailability: String = "",
    @SerialName("supported_operations")
    public val supportedOperations: Map<String, Boolean> = emptyMap(),
    @SerialName("ready_to_queue")
    public val readyToQueue: Boolean = false,
)

/** Wire type `internal/nativestorage.ScanResult`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. Registered root. */
@Serializable
public data class ScanResult(
    @SerialName("library_id")
    public val libraryId: Int = 0,
    @SerialName("scan_run_id")
    public val scanRunId: String = "",
    @SerialName("mode")
    public val mode: String = "",
    @SerialName("state")
    public val state: String = "",
    @SerialName("created")
    public val created: Boolean = false,
    @SerialName("library_revision")
    public val libraryRevision: Long = 0L,
    @SerialName("source_revision")
    public val sourceRevision: Long = 0L,
)

/** Wire type `internal/nativestorage.SourcePage`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. Registered root. */
@Serializable
public data class SourcePage(
    @SerialName("sources")
    public val sources: List<SourceView> = emptyList(),
    @SerialName("next_after")
    public val nextAfter: String? = null,
)

/** Wire type `internal/nativestorage.SourceView`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. */
@Serializable
public data class SourceView(
    @SerialName("source_key")
    public val sourceKey: String = "",
    @SerialName("owner_kind")
    public val ownerKind: OwnerKind = OwnerKind(""),
    @SerialName("organization_id")
    public val organizationId: String? = null,
    @SerialName("installation_id")
    public val installationId: Long? = null,
    @SerialName("plugin_id")
    public val pluginId: String = "",
    @SerialName("provider_source_id")
    public val providerSourceId: String = "",
    @SerialName("root_entry_id")
    public val rootEntryId: String = "",
    @SerialName("configuration_revision")
    public val configurationRevision: Long = 0L,
    @SerialName("enabled")
    public val enabled: Boolean = false,
    @SerialName("state")
    public val state: String = "",
    @SerialName("configured")
    public val configured: Boolean = false,
)
