// Code generated by cmd/clientdtogen from bloem-server internal/nativestorage. DO NOT EDIT.
// Server revision: cdbeda7d1f2ecd38ba88f5633c35aec8ff77999d (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.nativestorage

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import org.bloemserver.bloem.contract.resourcetenancy.OwnerKind

/** Wire type `internal/nativestorage.InstallCommand`. Direction: request. Dialect: bloem. Gate: native_storage.source_management. Registered root. */
@Serializable
public data class InstallCommand(
    @SerialName("artifact_key")
    public val artifactKey: String,
    @SerialName("provider_source_id")
    public val providerSourceId: String,
    @SerialName("root_entry_id")
    public val rootEntryId: String,
    @SerialName("enabled")
    public val enabled: Boolean,
    @SerialName("source_key")
    public val sourceKey: String? = null,
    @SerialName("organization_id")
    public val organizationId: String? = null,
    @SerialName("expected_revision")
    public val expectedRevision: Long? = null,
    @SerialName("config")
    public val config: Map<String, Map<String, JsonElement>>,
)

/** Wire type `internal/nativestorage.SourcePage`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. Registered root. */
@Serializable
public data class SourcePage(
    @SerialName("sources")
    public val sources: List<SourceView> = emptyList(),
    @SerialName("next_after")
    public val nextAfter: String? = null,
)

/** Wire type `internal/nativestorage.SourceView`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. */
@Serializable
public data class SourceView(
    @SerialName("source_key")
    public val sourceKey: String = "",
    @SerialName("owner_kind")
    public val ownerKind: OwnerKind = OwnerKind(""),
    @SerialName("organization_id")
    public val organizationId: String? = null,
    @SerialName("installation_id")
    public val installationId: Long? = null,
    @SerialName("plugin_id")
    public val pluginId: String = "",
    @SerialName("provider_source_id")
    public val providerSourceId: String = "",
    @SerialName("root_entry_id")
    public val rootEntryId: String = "",
    @SerialName("configuration_revision")
    public val configurationRevision: Long = 0L,
    @SerialName("enabled")
    public val enabled: Boolean = false,
    @SerialName("state")
    public val state: String = "",
    @SerialName("configured")
    public val configured: Boolean = false,
)

/** Wire type `internal/nativestorage.UpgradeCommand`. Direction: request. Dialect: bloem. Gate: native_storage.source_management. Registered root. */
@Serializable
public data class UpgradeCommand(
    @SerialName("artifact_key")
    public val artifactKey: String,
    @SerialName("source_key")
    public val sourceKey: String,
    @SerialName("expected_revision")
    public val expectedRevision: Long,
)
