// Code generated by cmd/clientdtogen from bloem-server internal/diagnostics. DO NOT EDIT.
// Server revision: 55d3ae52f51751e4da769252179e9988a005782e (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/diagnostics`.
public enum Diagnostics {
    /// Wire type `internal/diagnostics.AvailabilityStatus`. Direction: response. Dialect: upstream-compat.
    public struct AvailabilityStatus: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let AVAILABLE: AvailabilityStatus = AvailabilityStatus(rawValue: "available")
        public static let DISABLED: AvailabilityStatus = AvailabilityStatus(rawValue: "disabled")
        public static let STORAGE_UNAVAILABLE: AvailabilityStatus = AvailabilityStatus(rawValue: "storage_unavailable")
        public static let KNOWN: [AvailabilityStatus] = [AVAILABLE, DISABLED, STORAGE_UNAVAILABLE]
    }

    /// Wire type `internal/diagnostics.IngestResult`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct IngestResult: Codable, Hashable, Sendable {
        public let reportId: String
        public let shortId: String

        public enum CodingKeys: String, CodingKey {
            case reportId = "report_id"
            case shortId = "short_id"
        }

        public init(
            reportId: String = "",
            shortId: String = ""
        ) {
            self.reportId = reportId
            self.shortId = shortId
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.reportId = try container.decodeIfPresent(String.self, forKey: .reportId) ?? ""
            self.shortId = try container.decodeIfPresent(String.self, forKey: .shortId) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.reportId, forKey: .reportId)
            try container.encode(self.shortId, forKey: .shortId)
        }
    }

    /// Wire type `internal/diagnostics.Status`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct Status: Codable, Hashable, Sendable {
        public let status: AvailabilityStatus
        public let serverInstanceId: String
        public let acceptedSchemaVersions: [Int]
        public let maxBundleBytes: Int64
        public let maxManifestBytes: Int64
        public let retentionDays: Int
        public let consentNoticeVersion: Int
        public let uploadChunkBytes: Int64

        public enum CodingKeys: String, CodingKey {
            case status = "status"
            case serverInstanceId = "server_instance_id"
            case acceptedSchemaVersions = "accepted_schema_versions"
            case maxBundleBytes = "max_bundle_bytes"
            case maxManifestBytes = "max_manifest_bytes"
            case retentionDays = "retention_days"
            case consentNoticeVersion = "consent_notice_version"
            case uploadChunkBytes = "upload_chunk_bytes"
        }

        public init(
            status: AvailabilityStatus = AvailabilityStatus(rawValue: ""),
            serverInstanceId: String = "",
            acceptedSchemaVersions: [Int] = [],
            maxBundleBytes: Int64 = 0,
            maxManifestBytes: Int64 = 0,
            retentionDays: Int = 0,
            consentNoticeVersion: Int = 0,
            uploadChunkBytes: Int64 = 0
        ) {
            self.status = status
            self.serverInstanceId = serverInstanceId
            self.acceptedSchemaVersions = acceptedSchemaVersions
            self.maxBundleBytes = maxBundleBytes
            self.maxManifestBytes = maxManifestBytes
            self.retentionDays = retentionDays
            self.consentNoticeVersion = consentNoticeVersion
            self.uploadChunkBytes = uploadChunkBytes
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.status = try container.decodeIfPresent(AvailabilityStatus.self, forKey: .status) ?? AvailabilityStatus(rawValue: "")
            self.serverInstanceId = try container.decodeIfPresent(String.self, forKey: .serverInstanceId) ?? ""
            self.acceptedSchemaVersions = try container.decodeIfPresent([Int].self, forKey: .acceptedSchemaVersions) ?? []
            self.maxBundleBytes = try container.decodeIfPresent(Int64.self, forKey: .maxBundleBytes) ?? 0
            self.maxManifestBytes = try container.decodeIfPresent(Int64.self, forKey: .maxManifestBytes) ?? 0
            self.retentionDays = try container.decodeIfPresent(Int.self, forKey: .retentionDays) ?? 0
            self.consentNoticeVersion = try container.decodeIfPresent(Int.self, forKey: .consentNoticeVersion) ?? 0
            self.uploadChunkBytes = try container.decodeIfPresent(Int64.self, forKey: .uploadChunkBytes) ?? 0
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.status, forKey: .status)
            try container.encode(self.serverInstanceId, forKey: .serverInstanceId)
            try container.encode(self.acceptedSchemaVersions, forKey: .acceptedSchemaVersions)
            try container.encode(self.maxBundleBytes, forKey: .maxBundleBytes)
            try container.encode(self.maxManifestBytes, forKey: .maxManifestBytes)
            try container.encode(self.retentionDays, forKey: .retentionDays)
            try container.encode(self.consentNoticeVersion, forKey: .consentNoticeVersion)
            try container.encode(self.uploadChunkBytes, forKey: .uploadChunkBytes)
        }
    }
}
