// Code generated by cmd/clientdtogen from bloem-server internal/resourcetenancy. DO NOT EDIT.
// Server revision: cdbeda7d1f2ecd38ba88f5633c35aec8ff77999d (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.resourcetenancy

import kotlin.jvm.JvmInline
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/resourcetenancy.OwnerKind`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. */
@Serializable
@JvmInline
public value class OwnerKind(public val wire: String) {
    public companion object {
        @SerialName("platform")
        public val PLATFORM: OwnerKind = OwnerKind("platform")
        @SerialName("organization")
        public val ORGANIZATION: OwnerKind = OwnerKind("organization")
        public val KNOWN: List<OwnerKind> = listOf(PLATFORM, ORGANIZATION)
    }
}
