// Code generated by cmd/clientdtogen from bloem-server internal/apiv2. DO NOT EDIT.
// Server revision: 3408ce19b2a82c0cda0247e7cff652fd4a49da05 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.apiv2

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import org.bloemserver.bloem.contract.notifications.DeliveryRowPayload

/** Wire type `internal/apiv2.BloemNotificationPage`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class BloemNotificationPage(
    @SerialName("items")
    public val items: List<DeliveryRowPayload> = emptyList(),
    @SerialName("page")
    public val page: BloemNotificationPageInfo = BloemNotificationPageInfo(),
    @SerialName("read_cutoff")
    public val readCutoff: String = "",
)

/** Wire type `internal/apiv2.BloemNotificationPageInfo`. Direction: response. Dialect: bloem. */
@Serializable
public data class BloemNotificationPageInfo(
    @SerialName("next_cursor")
    public val nextCursor: String = "",
    @SerialName("has_more")
    public val hasMore: Boolean = false,
)

/** Wire type `internal/apiv2.BloemNotificationSyncPage`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class BloemNotificationSyncPage(
    @SerialName("items")
    public val items: List<DeliveryRowPayload> = emptyList(),
    @SerialName("page")
    public val page: BloemNotificationPageInfo = BloemNotificationPageInfo(),
    @SerialName("unread_count")
    public val unreadCount: Int = 0,
    @SerialName("initial_snapshot")
    public val initialSnapshot: Boolean = false,
)

/** Wire type `internal/apiv2.BulkItemFailure`. Direction: response. Dialect: bloem. */
@Serializable
public data class BulkItemFailure(
    @SerialName("type")
    public val type: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("status")
    public val status: Int = 0,
    @SerialName("detail")
    public val detail: String = "",
    @SerialName("errors")
    public val errors: List<ProblemError> = emptyList(),
)

/** Wire type `internal/apiv2.BulkSummary`. Direction: response. Dialect: bloem. */
@Serializable
public data class BulkSummary(
    @SerialName("total")
    public val total: Int = 0,
    @SerialName("succeeded")
    public val succeeded: Int = 0,
    @SerialName("failed")
    public val failed: Int = 0,
)

/** Wire type `internal/apiv2.CatalogItemOverlay`. Direction: response. Dialect: bloem. */
@Serializable
public data class CatalogItemOverlay(
    @SerialName("resolution")
    public val resolution: String = "",
    @SerialName("hdr")
    public val hdr: String = "",
    @SerialName("audio")
    public val audio: String = "",
    @SerialName("audio_channels")
    public val audioChannels: String = "",
    @SerialName("video_codec")
    public val videoCodec: String = "",
    @SerialName("container")
    public val container: String = "",
    @SerialName("aspect_ratio")
    public val aspectRatio: String = "",
    @SerialName("release_type")
    public val releaseType: String = "",
    @SerialName("edition")
    public val edition: String = "",
    @SerialName("multi_audio")
    public val multiAudio: Boolean = false,
    @SerialName("multi_sub")
    public val multiSub: Boolean = false,
)

/** Wire type `internal/apiv2.CatalogItemSortMetrics`. Direction: response. Dialect: bloem. */
@Serializable
public data class CatalogItemSortMetrics(
    @SerialName("release_date")
    public val releaseDate: String? = null,
    @SerialName("runtime_minutes")
    public val runtimeMinutes: Int? = null,
    @SerialName("resolution")
    public val resolution: String = "",
    @SerialName("bitrate_kbps")
    public val bitrateKbps: Int? = null,
    @SerialName("progress_ratio")
    public val progressRatio: Double? = null,
    @SerialName("viewed_at")
    public val viewedAt: String = "",
    @SerialName("play_count")
    public val playCount: Int? = null,
    @SerialName("author")
    public val author: String = "",
    @SerialName("narrator")
    public val narrator: String = "",
    @SerialName("series_name")
    public val seriesName: String = "",
)

/** Wire type `internal/apiv2.CatalogItemUpcomingEvent`. Direction: response. Dialect: bloem. */
@Serializable
public data class CatalogItemUpcomingEvent(
    @SerialName("type")
    public val type: String = "",
    @SerialName("air_date")
    public val airDate: String = "",
    @SerialName("air_time")
    public val airTime: String? = null,
    @SerialName("episode_title")
    public val episodeTitle: String? = null,
    @SerialName("season_number")
    public val seasonNumber: Int? = null,
    @SerialName("episode_number")
    public val episodeNumber: Int? = null,
    @SerialName("badges")
    public val badges: List<String> = emptyList(),
)

/** Wire type `internal/apiv2.CatalogItemUserState`. Direction: response. Dialect: bloem. */
@Serializable
public data class CatalogItemUserState(
    @SerialName("played")
    public val played: Boolean = false,
    @SerialName("is_favorite")
    public val isFavorite: Boolean = false,
    @SerialName("in_watchlist")
    public val inWatchlist: Boolean = false,
)

/** Wire type `internal/apiv2.CatalogWorkFormat`. Direction: response. Dialect: bloem. */
@Serializable
public data class CatalogWorkFormat(
    @SerialName("type")
    public val type: String = "",
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("library_id")
    public val libraryId: String = "",
)

/** Wire type `internal/apiv2.DownloadEntry`. Direction: response. Dialect: bloem. */
@Serializable
public data class DownloadEntry(
    @SerialName("id")
    public val id: String = "",
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("episode_id")
    public val episodeId: String = "",
    @SerialName("batch_id")
    public val batchId: String = "",
    @SerialName("device_id")
    public val deviceId: String = "",
    @SerialName("media_file_id")
    public val mediaFileId: String = "",
    @SerialName("file_size")
    public val fileSize: Long = 0L,
    @SerialName("bytes_sent")
    public val bytesSent: Long = 0L,
    @SerialName("kind")
    public val kind: String = "",
    @SerialName("status")
    public val status: String = "",
    @SerialName("quality")
    public val quality: String = "",
    @SerialName("effective_quality")
    public val effectiveQuality: String = "",
    @SerialName("delivery_format")
    public val deliveryFormat: String = "",
    @SerialName("target_bitrate_kbps")
    public val targetBitrateKbps: Int = 0,
    @SerialName("revision")
    public val revision: Int = 0,
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("completed_at")
    public val completedAt: String? = null,
    @SerialName("status_event_at")
    public val statusEventAt: String? = null,
)

/** Wire type `internal/apiv2.DownloadEntryCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class DownloadEntryCollection(
    @SerialName("items")
    public val items: List<DownloadEntry> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.DownloadSubscription`. Direction: response. Dialect: bloem. */
@Serializable
public data class DownloadSubscription(
    @SerialName("id")
    public val id: String = "",
    @SerialName("series_id")
    public val seriesId: String = "",
    @SerialName("mode")
    public val mode: String = "",
    @SerialName("season_numbers")
    public val seasonNumbers: List<Int> = emptyList(),
    @SerialName("target_season")
    public val targetSeason: Int? = null,
    @SerialName("delete_watched")
    public val deleteWatched: Boolean = false,
    @SerialName("max_storage_bytes")
    public val maxStorageBytes: Long = 0L,
    @SerialName("active")
    public val active: Boolean = false,
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("updated_at")
    public val updatedAt: String = "",
    @SerialName("etag")
    public val eTag: String = "",
)

/** Wire type `internal/apiv2.DownloadSubscriptionCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class DownloadSubscriptionCollection(
    @SerialName("items")
    public val items: List<DownloadSubscription> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.EbookAnnotation`. Direction: response. Dialect: bloem. */
@Serializable
public data class EbookAnnotation(
    @SerialName("id")
    public val id: String = "",
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("kind")
    public val kind: String = "",
    @SerialName("cfi_range")
    public val cfiRange: String = "",
    @SerialName("location")
    public val location: String = "",
    @SerialName("selected_text")
    public val selectedText: String = "",
    @SerialName("note")
    public val note: String = "",
    @SerialName("style")
    public val style: String = "",
    @SerialName("color")
    public val color: String = "",
    @SerialName("metadata")
    public val metadata: Map<String, JsonElement> = emptyMap(),
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("updated_at")
    public val updatedAt: String = "",
    @SerialName("etag")
    public val eTag: String = "",
)

/** Wire type `internal/apiv2.EbookAnnotationCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class EbookAnnotationCollection(
    @SerialName("items")
    public val items: List<EbookAnnotation> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.HistoryCard`. Direction: response. Dialect: bloem. */
@Serializable
public data class HistoryCard(
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("play_content_id")
    public val playContentId: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("series_id")
    public val seriesId: String = "",
    @SerialName("series_title")
    public val seriesTitle: String = "",
    @SerialName("season_number")
    public val seasonNumber: Int? = null,
    @SerialName("episode_number")
    public val episodeNumber: Int? = null,
    @SerialName("year")
    public val year: Int = 0,
    @SerialName("runtime")
    public val runtime: Int = 0,
    @SerialName("genres")
    public val genres: List<String> = emptyList(),
    @SerialName("keywords")
    public val keywords: List<String> = emptyList(),
    @SerialName("studios")
    public val studios: List<String> = emptyList(),
    @SerialName("networks")
    public val networks: List<String> = emptyList(),
    @SerialName("content_rating")
    public val contentRating: String = "",
    @SerialName("status")
    public val status: String = "",
    @SerialName("show_status")
    public val showStatus: String = "",
    @SerialName("rating_imdb")
    public val ratingImdb: Double? = null,
    @SerialName("rating_tmdb")
    public val ratingTmdb: Double? = null,
    @SerialName("rating_rt_critic")
    public val ratingRtCritic: Int? = null,
    @SerialName("rating_rt_audience")
    public val ratingRtAudience: Int? = null,
    @SerialName("original_language")
    public val originalLanguage: String = "",
    @SerialName("overview")
    public val overview: String = "",
    @SerialName("release_date")
    public val releaseDate: String? = null,
    @SerialName("last_air_date")
    public val lastAirDate: String? = null,
    @SerialName("added_at")
    public val addedAt: String? = null,
    @SerialName("position_seconds")
    public val positionSeconds: Double? = null,
    @SerialName("duration_seconds")
    public val durationSeconds: Double? = null,
    @SerialName("progress_updated_at")
    public val progressUpdatedAt: String? = null,
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("poster_thumbhash")
    public val posterThumbhash: String = "",
    @SerialName("backdrop_url")
    public val backdropUrl: String = "",
    @SerialName("backdrop_thumbhash")
    public val backdropThumbhash: String = "",
    @SerialName("logo_url")
    public val logoUrl: String = "",
    @SerialName("manga_chapter_count")
    public val mangaChapterCount: Int? = null,
    @SerialName("manga_volume_count")
    public val mangaVolumeCount: Int? = null,
    @SerialName("overlay_summary")
    public val overlaySummary: CatalogItemOverlay? = null,
    @SerialName("badges")
    public val badges: List<String> = emptyList(),
    @SerialName("item_source")
    public val itemSource: String = "",
    @SerialName("sort_metrics")
    public val sortMetrics: CatalogItemSortMetrics? = null,
    @SerialName("user_state")
    public val userState: CatalogItemUserState? = null,
    @SerialName("upcoming_event")
    public val upcomingEvent: CatalogItemUpcomingEvent? = null,
    @SerialName("work_id")
    public val workId: String = "",
    @SerialName("work_title")
    public val workTitle: String = "",
    @SerialName("work_formats")
    public val workFormats: List<CatalogWorkFormat> = emptyList(),
    @SerialName("watch")
    public val watch: HistoryWatch = HistoryWatch(),
)

/** Wire type `internal/apiv2.HistoryCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class HistoryCollection(
    @SerialName("items")
    public val items: List<HistoryCard> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.HistoryWatch`. Direction: response. Dialect: bloem. */
@Serializable
public data class HistoryWatch(
    @SerialName("media_item_id")
    public val mediaItemId: String = "",
    @SerialName("watched_at")
    public val watchedAt: String = "",
    @SerialName("duration_seconds")
    public val durationSeconds: Double = 0.0,
    @SerialName("completed")
    public val completed: Boolean = false,
    @SerialName("source")
    public val source: String = "",
)

/** Wire type `internal/apiv2.NotificationServerChannel`. Direction: response. Dialect: bloem. */
@Serializable
public data class NotificationServerChannel(
    @SerialName("id")
    public val id: String = "",
    @SerialName("name")
    public val name: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("url_host")
    public val urlHost: String = "",
    @SerialName("enabled")
    public val enabled: Boolean = false,
    @SerialName("notify_new_movies")
    public val notifyNewMovies: Boolean = false,
    @SerialName("notify_new_episodes")
    public val notifyNewEpisodes: Boolean = false,
    @SerialName("notify_new_audiobooks")
    public val notifyNewAudiobooks: Boolean = false,
    @SerialName("notify_new_ebooks")
    public val notifyNewEbooks: Boolean = false,
    @SerialName("notify_request_submitted")
    public val notifyRequestSubmitted: Boolean = false,
    @SerialName("notify_request_approved")
    public val notifyRequestApproved: Boolean = false,
    @SerialName("notify_request_declined")
    public val notifyRequestDeclined: Boolean = false,
    @SerialName("notify_request_fulfilled")
    public val notifyRequestFulfilled: Boolean = false,
    @SerialName("consecutive_failures")
    public val consecutiveFailures: Int = 0,
    @SerialName("disabled_reason")
    public val disabledReason: String? = null,
    @SerialName("last_success_at")
    public val lastSuccessAt: String? = null,
    @SerialName("last_failure_at")
    public val lastFailureAt: String? = null,
    @SerialName("last_failure_status")
    public val lastFailureStatus: Int? = null,
    @SerialName("last_failure_message")
    public val lastFailureMessage: String? = null,
    @SerialName("created_at")
    public val createdAt: String = "",
)

/** Wire type `internal/apiv2.NotificationServerChannelCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class NotificationServerChannelCollection(
    @SerialName("items")
    public val items: List<NotificationServerChannel> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.NotificationWebPushSubscription`. Direction: response. Dialect: bloem. */
@Serializable
public data class NotificationWebPushSubscription(
    @SerialName("id")
    public val id: String = "",
    @SerialName("endpoint")
    public val endpoint: String = "",
    @SerialName("device_name")
    public val deviceName: String = "",
    @SerialName("enabled")
    public val enabled: Boolean = false,
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("last_success_at")
    public val lastSuccessAt: String? = null,
    @SerialName("last_failure_at")
    public val lastFailureAt: String? = null,
)

/** Wire type `internal/apiv2.NotificationWebPushSubscriptionCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class NotificationWebPushSubscriptionCollection(
    @SerialName("items")
    public val items: List<NotificationWebPushSubscription> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.NotificationWebhookDestination`. Direction: response. Dialect: bloem. */
@Serializable
public data class NotificationWebhookDestination(
    @SerialName("etag")
    public val eTag: String = "",
    @SerialName("id")
    public val id: String = "",
    @SerialName("name")
    public val name: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("url_host")
    public val urlHost: String = "",
    @SerialName("enabled")
    public val enabled: Boolean = false,
    @SerialName("notify_favorites")
    public val notifyFavorites: Boolean = false,
    @SerialName("notify_watchlist")
    public val notifyWatchlist: Boolean = false,
    @SerialName("notify_continue_watching")
    public val notifyContinueWatching: Boolean = false,
    @SerialName("notify_next_up")
    public val notifyNextUp: Boolean = false,
    @SerialName("notify_requests")
    public val notifyRequests: Boolean = false,
    @SerialName("consecutive_failures")
    public val consecutiveFailures: Int = 0,
    @SerialName("disabled_reason")
    public val disabledReason: String? = null,
    @SerialName("last_success_at")
    public val lastSuccessAt: String? = null,
    @SerialName("last_failure_at")
    public val lastFailureAt: String? = null,
    @SerialName("last_failure_status")
    public val lastFailureStatus: Int? = null,
    @SerialName("last_failure_message")
    public val lastFailureMessage: String? = null,
)

/** Wire type `internal/apiv2.NotificationWebhookDestinationCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class NotificationWebhookDestinationCollection(
    @SerialName("items")
    public val items: List<NotificationWebhookDestination> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.PageInfo`. Direction: response. Dialect: bloem. */
@Serializable
public data class PageInfo(
    @SerialName("next_cursor")
    public val nextCursor: String = "",
    @SerialName("has_more")
    public val hasMore: Boolean = false,
)

/** Wire type `internal/apiv2.PersonalAPIKeyListItem`. Direction: response. Dialect: bloem. */
@Serializable
public data class PersonalAPIKeyListItem(
    @SerialName("id")
    public val id: String = "",
    @SerialName("user_id")
    public val userId: String = "",
    @SerialName("label")
    public val label: String = "",
    @SerialName("key_prefix")
    public val keyPrefix: String = "",
    @SerialName("rate_tier")
    public val rateTier: String = "",
    @SerialName("scopes")
    public val scopes: List<String> = emptyList(),
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("last_used_at")
    public val lastUsedAt: String? = null,
)

/** Wire type `internal/apiv2.PersonalAPIKeyListItemCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class PersonalAPIKeyListItemCollection(
    @SerialName("items")
    public val items: List<PersonalAPIKeyListItem> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.PersonalCollectionItem`. Direction: response. Dialect: bloem. */
@Serializable
public data class PersonalCollectionItem(
    @SerialName("title")
    public val title: String = "",
    @SerialName("collection_id")
    public val collectionId: String = "",
    @SerialName("media_item_id")
    public val mediaItemId: String = "",
    @SerialName("position")
    public val position: Int = 0,
    @SerialName("added_at")
    public val addedAt: String = "",
)

/** Wire type `internal/apiv2.PersonalCollectionItemCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class PersonalCollectionItemCollection(
    @SerialName("items")
    public val items: List<PersonalCollectionItem> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.PlaybackSubtitleFont`. Direction: response. Dialect: bloem. */
@Serializable
public data class PlaybackSubtitleFont(
    @SerialName("name")
    public val name: String = "",
    @SerialName("data")
    public val data: String = "",
)

/** Wire type `internal/apiv2.PlaybackSubtitleFontCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class PlaybackSubtitleFontCollection(
    @SerialName("items")
    public val items: List<PlaybackSubtitleFont> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.ProblemError`. Direction: response. Dialect: bloem. */
@Serializable
public data class ProblemError(
    @SerialName("location")
    public val location: String = "",
    @SerialName("code")
    public val code: String = "",
    @SerialName("detail")
    public val detail: String = "",
)

/** Wire type `internal/apiv2.Profile`. Direction: response. Dialect: bloem. */
@Serializable
public data class Profile(
    @SerialName("id")
    public val id: String = "",
    @SerialName("name")
    public val name: String = "",
    @SerialName("avatar")
    public val avatar: String = "",
    @SerialName("avatar_url")
    public val avatarUrl: String = "",
    @SerialName("avatar_source")
    public val avatarSource: String = "",
    @SerialName("has_pin")
    public val hasPin: Boolean = false,
    @SerialName("is_child")
    public val isChild: Boolean = false,
    @SerialName("is_primary")
    public val isPrimary: Boolean = false,
    @SerialName("max_content_rating")
    public val maxContentRating: String = "",
    @SerialName("quality_preference")
    public val qualityPreference: String = "",
    @SerialName("language")
    public val language: String = "",
    @SerialName("preferred_metadata_language")
    public val preferredMetadataLanguage: String = "",
    @SerialName("subtitle_language")
    public val subtitleLanguage: String = "",
    @SerialName("subtitle_mode")
    public val subtitleMode: String = "",
    @SerialName("auto_skip_intro")
    public val autoSkipIntro: Boolean = false,
    @SerialName("auto_skip_credits")
    public val autoSkipCredits: Boolean = false,
    @SerialName("auto_skip_recap")
    public val autoSkipRecap: Boolean = false,
    @SerialName("auto_play_next_preview")
    public val autoPlayNextPreview: Boolean = false,
    @SerialName("show_forced_subtitles")
    public val showForcedSubtitles: Boolean = false,
    @SerialName("library_restrictions_enabled")
    public val libraryRestrictionsEnabled: Boolean = false,
    @SerialName("allowed_library_ids")
    public val allowedLibraryIds: List<String> = emptyList(),
    @SerialName("max_playback_quality")
    public val maxPlaybackQuality: String = "",
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("updated_at")
    public val updatedAt: String = "",
)

/** Wire type `internal/apiv2.ProfileCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class ProfileCollection(
    @SerialName("items")
    public val items: List<Profile> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
    @SerialName("avatar_upload_enabled")
    public val avatarUploadEnabled: Boolean = false,
)

/** Wire type `internal/apiv2.ProgressCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class ProgressCollection(
    @SerialName("items")
    public val items: List<ProgressEntry> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.ProgressEntry`. Direction: response. Dialect: bloem. */
@Serializable
public data class ProgressEntry(
    @SerialName("media_item_id")
    public val mediaItemId: String = "",
    @SerialName("position_seconds")
    public val positionSeconds: Double = 0.0,
    @SerialName("duration_seconds")
    public val durationSeconds: Double = 0.0,
    @SerialName("completed")
    public val completed: Boolean = false,
    @SerialName("updated_at")
    public val updatedAt: String = "",
)

/** Wire type `internal/apiv2.ProgressSyncBatchResult`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class ProgressSyncBatchResult(
    @SerialName("items")
    public val items: List<ProgressSyncResult> = emptyList(),
    @SerialName("summary")
    public val summary: BulkSummary = BulkSummary(),
)

/** Wire type `internal/apiv2.ProgressSyncResult`. Direction: response. Dialect: bloem. */
@Serializable
public data class ProgressSyncResult(
    @SerialName("index")
    public val index: Int = 0,
    @SerialName("client_ref")
    public val clientRef: String? = null,
    @SerialName("media_item_id")
    public val mediaItemId: String = "",
    @SerialName("status")
    public val status: String = "",
    @SerialName("failure")
    public val failure: BulkItemFailure? = null,
)

/** Wire type `internal/apiv2.UserLibrary`. Direction: response. Dialect: bloem. */
@Serializable
public data class UserLibrary(
    @SerialName("id")
    public val id: String = "",
    @SerialName("name")
    public val name: String = "",
    @SerialName("type")
    public val type: String = "",
    @SerialName("sort_order")
    public val sortOrder: Int = 0,
    @SerialName("poster_url")
    public val posterUrl: String = "",
)

/** Wire type `internal/apiv2.UserLibraryCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class UserLibraryCollection(
    @SerialName("items")
    public val items: List<UserLibrary> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)

/** Wire type `internal/apiv2.WatchTogetherSuggestion`. Direction: response. Dialect: bloem. */
@Serializable
public data class WatchTogetherSuggestion(
    @SerialName("id")
    public val id: String = "",
    @SerialName("room_id")
    public val roomId: String = "",
    @SerialName("suggester_user_id")
    public val suggesterUserId: String = "",
    @SerialName("suggester_profile_id")
    public val suggesterProfileId: String = "",
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("content_type")
    public val contentType: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("subtitle")
    public val subtitle: String = "",
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("note")
    public val note: String = "",
    @SerialName("vote_count")
    public val voteCount: Int = 0,
    @SerialName("voted_by_me")
    public val votedByMe: Boolean = false,
    @SerialName("created_at")
    public val createdAt: String = "",
)

/** Wire type `internal/apiv2.WatchTogetherSuggestionCollection`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class WatchTogetherSuggestionCollection(
    @SerialName("items")
    public val items: List<WatchTogetherSuggestion> = emptyList(),
    @SerialName("page")
    public val page: PageInfo? = null,
)
