// Code generated by cmd/clientdtogen from bloem-server internal/subtitles. DO NOT EDIT.
// Server revision: 8c612bd9 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/subtitles`.
public enum Subtitles {
    /// Wire type `internal/subtitles.DownloadedSubtitle`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct DownloadedSubtitle: Codable, Hashable, Sendable {
        public let id: Int
        public let mediaFileId: Int
        public let provider: String
        public let language: String
        public let format: SubtitleFormat
        public let releaseName: String
        public let score: Double
        public let hearingImpaired: Bool
        public let createdAt: String

        public enum CodingKeys: String, CodingKey {
            case id = "id"
            case mediaFileId = "media_file_id"
            case provider = "provider"
            case language = "language"
            case format = "format"
            case releaseName = "release_name"
            case score = "score"
            case hearingImpaired = "hearing_impaired"
            case createdAt = "created_at"
        }

        public init(
            id: Int = 0,
            mediaFileId: Int = 0,
            provider: String = "",
            language: String = "",
            format: SubtitleFormat = SubtitleFormat(rawValue: ""),
            releaseName: String = "",
            score: Double = 0.0,
            hearingImpaired: Bool = false,
            createdAt: String = ""
        ) {
            self.id = id
            self.mediaFileId = mediaFileId
            self.provider = provider
            self.language = language
            self.format = format
            self.releaseName = releaseName
            self.score = score
            self.hearingImpaired = hearingImpaired
            self.createdAt = createdAt
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.id = try container.decodeIfPresent(Int.self, forKey: .id) ?? 0
            self.mediaFileId = try container.decodeIfPresent(Int.self, forKey: .mediaFileId) ?? 0
            self.provider = try container.decodeIfPresent(String.self, forKey: .provider) ?? ""
            self.language = try container.decodeIfPresent(String.self, forKey: .language) ?? ""
            self.format = try container.decodeIfPresent(SubtitleFormat.self, forKey: .format) ?? SubtitleFormat(rawValue: "")
            self.releaseName = try container.decodeIfPresent(String.self, forKey: .releaseName) ?? ""
            self.score = try container.decodeIfPresent(Double.self, forKey: .score) ?? 0.0
            self.hearingImpaired = try container.decodeIfPresent(Bool.self, forKey: .hearingImpaired) ?? false
            self.createdAt = try container.decodeIfPresent(String.self, forKey: .createdAt) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.id, forKey: .id)
            try container.encode(self.mediaFileId, forKey: .mediaFileId)
            try container.encode(self.provider, forKey: .provider)
            try container.encode(self.language, forKey: .language)
            try container.encode(self.format, forKey: .format)
            try container.encode(self.releaseName, forKey: .releaseName)
            try container.encode(self.score, forKey: .score)
            try container.encode(self.hearingImpaired, forKey: .hearingImpaired)
            try container.encode(self.createdAt, forKey: .createdAt)
        }
    }

    /// Wire type `internal/subtitles.LanguageDetection`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct LanguageDetection: Codable, Hashable, Sendable {
        public let language: String
        public let source: LanguageDetectionSource

        public enum CodingKeys: String, CodingKey {
            case language = "language"
            case source = "source"
        }

        public init(
            language: String = "",
            source: LanguageDetectionSource = LanguageDetectionSource(rawValue: "")
        ) {
            self.language = language
            self.source = source
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.language = try container.decodeIfPresent(String.self, forKey: .language) ?? ""
            self.source = try container.decodeIfPresent(LanguageDetectionSource.self, forKey: .source) ?? LanguageDetectionSource(rawValue: "")
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.language, forKey: .language)
            try container.encode(self.source, forKey: .source)
        }
    }

    /// Wire type `internal/subtitles.LanguageDetectionSource`. Direction: response. Dialect: upstream-compat.
    public struct LanguageDetectionSource: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let FILENAME: LanguageDetectionSource = LanguageDetectionSource(rawValue: "filename")
        public static let METADATA: LanguageDetectionSource = LanguageDetectionSource(rawValue: "metadata")
        public static let CONTENT: LanguageDetectionSource = LanguageDetectionSource(rawValue: "content")
        public static let MANUAL: LanguageDetectionSource = LanguageDetectionSource(rawValue: "manual")
        public static let KNOWN: [LanguageDetectionSource] = [FILENAME, METADATA, CONTENT, MANUAL]
    }

    /// Wire type `internal/subtitles.SearchResponse`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct SearchResponse: Codable, Hashable, Sendable {
        public let results: [SubtitleResult]
        public let warnings: [String]

        public enum CodingKeys: String, CodingKey {
            case results = "results"
            case warnings = "warnings"
        }

        public init(
            results: [SubtitleResult] = [],
            warnings: [String] = []
        ) {
            self.results = results
            self.warnings = warnings
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.results = try container.decodeIfPresent([SubtitleResult].self, forKey: .results) ?? []
            self.warnings = try container.decodeIfPresent([String].self, forKey: .warnings) ?? []
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.results, forKey: .results)
            try container.encode(self.warnings, forKey: .warnings)
        }
    }

    /// Wire type `internal/subtitles.SubtitleFormat`. Direction: response. Dialect: upstream-compat.
    public struct SubtitleFormat: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let SRT: SubtitleFormat = SubtitleFormat(rawValue: "srt")
        public static let ASS: SubtitleFormat = SubtitleFormat(rawValue: "ass")
        public static let SSA: SubtitleFormat = SubtitleFormat(rawValue: "ssa")
        public static let VTT: SubtitleFormat = SubtitleFormat(rawValue: "vtt")
        public static let SUB: SubtitleFormat = SubtitleFormat(rawValue: "sub")
        public static let KNOWN: [SubtitleFormat] = [SRT, ASS, SSA, VTT, SUB]
    }

    /// Wire type `internal/subtitles.SubtitleResult`. Direction: response. Dialect: upstream-compat.
    public struct SubtitleResult: Codable, Hashable, Sendable {
        public let id: String
        public let provider: String
        public let language: String
        public let releaseName: String
        public let format: SubtitleFormat
        public let score: Double
        public let downloads: Int
        public let hearingImpaired: Bool
        public let uploadDate: String

        public enum CodingKeys: String, CodingKey {
            case id = "id"
            case provider = "provider"
            case language = "language"
            case releaseName = "release_name"
            case format = "format"
            case score = "score"
            case downloads = "downloads"
            case hearingImpaired = "hearing_impaired"
            case uploadDate = "upload_date"
        }

        public init(
            id: String = "",
            provider: String = "",
            language: String = "",
            releaseName: String = "",
            format: SubtitleFormat = SubtitleFormat(rawValue: ""),
            score: Double = 0.0,
            downloads: Int = 0,
            hearingImpaired: Bool = false,
            uploadDate: String = ""
        ) {
            self.id = id
            self.provider = provider
            self.language = language
            self.releaseName = releaseName
            self.format = format
            self.score = score
            self.downloads = downloads
            self.hearingImpaired = hearingImpaired
            self.uploadDate = uploadDate
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.id = try container.decodeIfPresent(String.self, forKey: .id) ?? ""
            self.provider = try container.decodeIfPresent(String.self, forKey: .provider) ?? ""
            self.language = try container.decodeIfPresent(String.self, forKey: .language) ?? ""
            self.releaseName = try container.decodeIfPresent(String.self, forKey: .releaseName) ?? ""
            self.format = try container.decodeIfPresent(SubtitleFormat.self, forKey: .format) ?? SubtitleFormat(rawValue: "")
            self.score = try container.decodeIfPresent(Double.self, forKey: .score) ?? 0.0
            self.downloads = try container.decodeIfPresent(Int.self, forKey: .downloads) ?? 0
            self.hearingImpaired = try container.decodeIfPresent(Bool.self, forKey: .hearingImpaired) ?? false
            self.uploadDate = try container.decodeIfPresent(String.self, forKey: .uploadDate) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.id, forKey: .id)
            try container.encode(self.provider, forKey: .provider)
            try container.encode(self.language, forKey: .language)
            try container.encode(self.releaseName, forKey: .releaseName)
            try container.encode(self.format, forKey: .format)
            try container.encode(self.score, forKey: .score)
            try container.encode(self.downloads, forKey: .downloads)
            try container.encode(self.hearingImpaired, forKey: .hearingImpaired)
            try container.encode(self.uploadDate, forKey: .uploadDate)
        }
    }
}
