// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: bloem/plugin/v1/storage_provider.proto

package storagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryKind int32

const (
	EntryKind_ENTRY_KIND_UNSPECIFIED EntryKind = 0
	EntryKind_ENTRY_KIND_FILE        EntryKind = 1
	EntryKind_ENTRY_KIND_DIRECTORY   EntryKind = 2
)

// Enum value maps for EntryKind.
var (
	EntryKind_name = map[int32]string{
		0: "ENTRY_KIND_UNSPECIFIED",
		1: "ENTRY_KIND_FILE",
		2: "ENTRY_KIND_DIRECTORY",
	}
	EntryKind_value = map[string]int32{
		"ENTRY_KIND_UNSPECIFIED": 0,
		"ENTRY_KIND_FILE":        1,
		"ENTRY_KIND_DIRECTORY":   2,
	}
)

func (x EntryKind) Enum() *EntryKind {
	p := new(EntryKind)
	*p = x
	return p
}

func (x EntryKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryKind) Descriptor() protoreflect.EnumDescriptor {
	return file_bloem_plugin_v1_storage_provider_proto_enumTypes[0].Descriptor()
}

func (EntryKind) Type() protoreflect.EnumType {
	return &file_bloem_plugin_v1_storage_provider_proto_enumTypes[0]
}

func (x EntryKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryKind.Descriptor instead.
func (EntryKind) EnumDescriptor() ([]byte, []int) {
	return file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP(), []int{0}
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP(), []int{0}
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint32                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Sources       []*Source              `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DescribeResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

type Source struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RootEntryId         string                 `protobuf:"bytes,3,opt,name=root_entry_id,json=rootEntryId,proto3" json:"root_entry_id,omitempty"`
	RevisionPinnedReads bool                   `protobuf:"varint,4,opt,name=revision_pinned_reads,json=revisionPinnedReads,proto3" json:"revision_pinned_reads,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP(), []int{2}
}

func (x *Source) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Source) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Source) GetRootEntryId() string {
	if x != nil {
		return x.RootEntryId
	}
	return ""
}

func (x *Source) GetRevisionPinnedReads() bool {
	if x != nil {
		return x.RevisionPinnedReads
	}
	return false
}

type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Display metadata only; never a host operating-system path.
	LogicalPath      string    `protobuf:"bytes,3,opt,name=logical_path,json=logicalPath,proto3" json:"logical_path,omitempty"`
	Kind             EntryKind `protobuf:"varint,4,opt,name=kind,proto3,enum=bloem.plugin.v1.EntryKind" json:"kind,omitempty"`
	Size             int64     `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedUnixNano int64     `protobuf:"varint,6,opt,name=modified_unix_nano,json=modifiedUnixNano,proto3" json:"modified_unix_nano,omitempty"`
	// An opaque content version, separate from stable entry identity.
	Revision      string `protobuf:"bytes,7,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP(), []int{3}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entry) GetLogicalPath() string {
	if x != nil {
		return x.LogicalPath
	}
	return ""
}

func (x *Entry) GetKind() EntryKind {
	if x != nil {
		return x.Kind
	}
	return EntryKind_ENTRY_KIND_UNSPECIFIED
}

func (x *Entry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Entry) GetModifiedUnixNano() int64 {
	if x != nil {
		return x.ModifiedUnixNano
	}
	return 0
}

func (x *Entry) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DirectoryId   string                 `protobuf:"bytes,2,opt,name=directory_id,json=directoryId,proto3" json:"directory_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	MaxEntries    uint32                 `protobuf:"varint,4,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ListRequest) GetDirectoryId() string {
	if x != nil {
		return x.DirectoryId
	}
	return ""
}

func (x *ListRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListRequest) GetMaxEntries() uint32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Complete      bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

type StatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceId         string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	EntryId          string                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	ExpectedRevision string                 `protobuf:"bytes,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP(), []int{6}
}

func (x *StatRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *StatRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *StatRequest) GetExpectedRevision() string {
	if x != nil {
		return x.ExpectedRevision
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP(), []int{7}
}

func (x *StatResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ReadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceId         string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	EntryId          string                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	ExpectedRevision string                 `protobuf:"bytes,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	Offset           int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Length           int64                  `protobuf:"varint,5,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP(), []int{8}
}

func (x *ReadRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ReadRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *ReadRequest) GetExpectedRevision() string {
	if x != nil {
		return x.ExpectedRevision
	}
	return ""
}

func (x *ReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunk) Reset() {
	*x = ReadChunk{}
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunk) ProtoMessage() {}

func (x *ReadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_bloem_plugin_v1_storage_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunk.ProtoReflect.Descriptor instead.
func (*ReadChunk) Descriptor() ([]byte, []int) {
	return file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ReadChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

var File_bloem_plugin_v1_storage_provider_proto protoreflect.FileDescriptor

const file_bloem_plugin_v1_storage_provider_proto_rawDesc = "" +
	"\n" +
	"&bloem/plugin/v1/storage_provider.proto\x12\x0fbloem.plugin.v1\"\x11\n" +
	"\x0fDescribeRequest\"a\n" +
	"\x10DescribeResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\rR\brevision\x121\n" +
	"\asources\x18\x02 \x03(\v2\x17.bloem.plugin.v1.SourceR\asources\"\x84\x01\n" +
	"\x06Source\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rroot_entry_id\x18\x03 \x01(\tR\vrootEntryId\x122\n" +
	"\x15revision_pinned_reads\x18\x04 \x01(\bR\x13revisionPinnedReads\"\xdc\x01\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\flogical_path\x18\x03 \x01(\tR\vlogicalPath\x12.\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1a.bloem.plugin.v1.EntryKindR\x04kind\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x12,\n" +
	"\x12modified_unix_nano\x18\x06 \x01(\x03R\x10modifiedUnixNano\x12\x1a\n" +
	"\brevision\x18\a \x01(\tR\brevision\"\x86\x01\n" +
	"\vListRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12!\n" +
	"\fdirectory_id\x18\x02 \x01(\tR\vdirectoryId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x1f\n" +
	"\vmax_entries\x18\x04 \x01(\rR\n" +
	"maxEntries\"}\n" +
	"\fListResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.bloem.plugin.v1.EntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete\"r\n" +
	"\vStatRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\tR\aentryId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\tR\x10expectedRevision\"<\n" +
	"\fStatResponse\x12,\n" +
	"\x05entry\x18\x01 \x01(\v2\x16.bloem.plugin.v1.EntryR\x05entry\"\xa2\x01\n" +
	"\vReadRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\tR\aentryId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\tR\x10expectedRevision\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x05 \x01(\x03R\x06length\"I\n" +
	"\tReadChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof*V\n" +
	"\tEntryKind\x12\x1a\n" +
	"\x16ENTRY_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fENTRY_KIND_FILE\x10\x01\x12\x18\n" +
	"\x14ENTRY_KIND_DIRECTORY\x10\x022\xb0\x02\n" +
	"\x0fStorageProvider\x12O\n" +
	"\bDescribe\x12 .bloem.plugin.v1.DescribeRequest\x1a!.bloem.plugin.v1.DescribeResponse\x12C\n" +
	"\x04List\x12\x1c.bloem.plugin.v1.ListRequest\x1a\x1d.bloem.plugin.v1.ListResponse\x12C\n" +
	"\x04Stat\x12\x1c.bloem.plugin.v1.StatRequest\x1a\x1d.bloem.plugin.v1.StatResponse\x12B\n" +
	"\x04Read\x12\x1c.bloem.plugin.v1.ReadRequest\x1a\x1a.bloem.plugin.v1.ReadChunk0\x01BUZSgithub.com/Bloem-Studios/bloem-plugin-sdk/pkg/pluginproto/bloem/plugin/v1;storagev1b\x06proto3"

var (
	file_bloem_plugin_v1_storage_provider_proto_rawDescOnce sync.Once
	file_bloem_plugin_v1_storage_provider_proto_rawDescData []byte
)

func file_bloem_plugin_v1_storage_provider_proto_rawDescGZIP() []byte {
	file_bloem_plugin_v1_storage_provider_proto_rawDescOnce.Do(func() {
		file_bloem_plugin_v1_storage_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bloem_plugin_v1_storage_provider_proto_rawDesc), len(file_bloem_plugin_v1_storage_provider_proto_rawDesc)))
	})
	return file_bloem_plugin_v1_storage_provider_proto_rawDescData
}

var file_bloem_plugin_v1_storage_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bloem_plugin_v1_storage_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bloem_plugin_v1_storage_provider_proto_goTypes = []any{
	(EntryKind)(0),           // 0: bloem.plugin.v1.EntryKind
	(*DescribeRequest)(nil),  // 1: bloem.plugin.v1.DescribeRequest
	(*DescribeResponse)(nil), // 2: bloem.plugin.v1.DescribeResponse
	(*Source)(nil),           // 3: bloem.plugin.v1.Source
	(*Entry)(nil),            // 4: bloem.plugin.v1.Entry
	(*ListRequest)(nil),      // 5: bloem.plugin.v1.ListRequest
	(*ListResponse)(nil),     // 6: bloem.plugin.v1.ListResponse
	(*StatRequest)(nil),      // 7: bloem.plugin.v1.StatRequest
	(*StatResponse)(nil),     // 8: bloem.plugin.v1.StatResponse
	(*ReadRequest)(nil),      // 9: bloem.plugin.v1.ReadRequest
	(*ReadChunk)(nil),        // 10: bloem.plugin.v1.ReadChunk
}
var file_bloem_plugin_v1_storage_provider_proto_depIdxs = []int32{
	3,  // 0: bloem.plugin.v1.DescribeResponse.sources:type_name -> bloem.plugin.v1.Source
	0,  // 1: bloem.plugin.v1.Entry.kind:type_name -> bloem.plugin.v1.EntryKind
	4,  // 2: bloem.plugin.v1.ListResponse.entries:type_name -> bloem.plugin.v1.Entry
	4,  // 3: bloem.plugin.v1.StatResponse.entry:type_name -> bloem.plugin.v1.Entry
	1,  // 4: bloem.plugin.v1.StorageProvider.Describe:input_type -> bloem.plugin.v1.DescribeRequest
	5,  // 5: bloem.plugin.v1.StorageProvider.List:input_type -> bloem.plugin.v1.ListRequest
	7,  // 6: bloem.plugin.v1.StorageProvider.Stat:input_type -> bloem.plugin.v1.StatRequest
	9,  // 7: bloem.plugin.v1.StorageProvider.Read:input_type -> bloem.plugin.v1.ReadRequest
	2,  // 8: bloem.plugin.v1.StorageProvider.Describe:output_type -> bloem.plugin.v1.DescribeResponse
	6,  // 9: bloem.plugin.v1.StorageProvider.List:output_type -> bloem.plugin.v1.ListResponse
	8,  // 10: bloem.plugin.v1.StorageProvider.Stat:output_type -> bloem.plugin.v1.StatResponse
	10, // 11: bloem.plugin.v1.StorageProvider.Read:output_type -> bloem.plugin.v1.ReadChunk
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_bloem_plugin_v1_storage_provider_proto_init() }
func file_bloem_plugin_v1_storage_provider_proto_init() {
	if File_bloem_plugin_v1_storage_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bloem_plugin_v1_storage_provider_proto_rawDesc), len(file_bloem_plugin_v1_storage_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bloem_plugin_v1_storage_provider_proto_goTypes,
		DependencyIndexes: file_bloem_plugin_v1_storage_provider_proto_depIdxs,
		EnumInfos:         file_bloem_plugin_v1_storage_provider_proto_enumTypes,
		MessageInfos:      file_bloem_plugin_v1_storage_provider_proto_msgTypes,
	}.Build()
	File_bloem_plugin_v1_storage_provider_proto = out.File
	file_bloem_plugin_v1_storage_provider_proto_goTypes = nil
	file_bloem_plugin_v1_storage_provider_proto_depIdxs = nil
}
