// Code generated by cmd/clientdtogen from bloem-server internal/userstore. DO NOT EDIT.
// Server revision: d66c15d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.userstore

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/userstore.SubtitleTrackSignature`. Direction: both. Dialect: upstream-compat. */
@Serializable
public data class SubtitleTrackSignature(
    @SerialName("source")
    public val source: String = "",
    @SerialName("language")
    public val language: String = "",
    @SerialName("codec")
    public val codec: String = "",
    @SerialName("label")
    public val label: String = "",
    @SerialName("forced")
    public val forced: Boolean = false,
    @SerialName("hearing_impaired")
    public val hearingImpaired: Boolean = false,
)
