// Code generated by cmd/clientdtogen from bloem-server internal/plugins. DO NOT EDIT.
// Server revision: c87b44545228c93f909275c0b5c4fc1d6a289e1b (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.plugins

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/plugins.NativeStorageArtifactView`. Direction: response. Dialect: bloem. Gate: native_storage.source_management. */
@Serializable
public data class NativeStorageArtifactView(
    @SerialName("artifact_key")
    public val artifactKey: String = "",
    @SerialName("plugin_id")
    public val pluginId: String = "",
    @SerialName("version")
    public val version: String = "",
    @SerialName("os")
    public val os: String = "",
    @SerialName("arch")
    public val arch: String = "",
)
