// Code generated by cmd/clientdtogen from bloem-server internal/imagesize. DO NOT EDIT.
// Server revision: 7ef228d3e10c81f166d2445967c7ec6db2bcb102 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/imagesize`.
public enum Imagesize {
    /// Wire type `internal/imagesize.Size`. Direction: response. Dialect: bloem.
    public struct Size: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let UNSET: Size = Size(rawValue: "")
        public static let SMALL: Size = Size(rawValue: "small")
        public static let MEDIUM: Size = Size(rawValue: "medium")
        public static let LARGE: Size = Size(rawValue: "large")
        public static let ORIGINAL: Size = Size(rawValue: "original")
        public static let KNOWN: [Size] = [UNSET, SMALL, MEDIUM, LARGE, ORIGINAL]
    }
}
