// Code generated by cmd/clientdtogen from bloem-server internal/remote. DO NOT EDIT.
// Server revision: 8c612bd9 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.remote

import kotlin.jvm.JvmInline
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import org.bloemserver.bloem.contract.playback.CommandName

/** Wire type `internal/remote.Command`. Direction: response. Dialect: bloem. Gate: notifications.remote_control. */
@Serializable
public data class Command(
    @SerialName("command_id")
    public val id: String = "",
    @SerialName("scope")
    public val scope: Scope = Scope(""),
    @SerialName("session_id")
    public val targetSessionId: String = "",
    @SerialName("device_id")
    public val targetDeviceId: String = "",
    @SerialName("user_id")
    public val targetUserId: Int = 0,
    @SerialName("profile_id")
    public val targetProfileId: String = "",
    @SerialName("tenant_id")
    public val tenantId: String = "",
    @SerialName("name")
    public val name: CommandName = CommandName(""),
    @SerialName("payload")
    public val payload: JsonElement? = null,
    @SerialName("issued_by")
    public val issuedBy: String = "",
    @SerialName("issuer_kind")
    public val issuerKind: IssuerKind = IssuerKind(""),
    @SerialName("reason")
    public val reason: String = "",
    @SerialName("state")
    public val state: State = State(""),
    @SerialName("result")
    public val result: JsonElement? = null,
    @SerialName("error")
    public val error: String = "",
    @SerialName("created_at")
    public val createdAt: String = "",
    @SerialName("sent_at")
    public val sentAt: String? = null,
    @SerialName("acked_at")
    public val ackedAt: String? = null,
    @SerialName("finished_at")
    public val finishedAt: String? = null,
    @SerialName("expires_at")
    public val expiresAt: String? = null,
)

/** Wire type `internal/remote.IssuerKind`. Direction: response. Dialect: bloem. Gate: notifications.remote_control. */
@Serializable
@JvmInline
public value class IssuerKind(public val wire: String) {
    public companion object {
        @SerialName("admin")
        public val ADMIN: IssuerKind = IssuerKind("admin")
        @SerialName("household")
        public val HOUSEHOLD: IssuerKind = IssuerKind("household")
        public val KNOWN: List<IssuerKind> = listOf(ADMIN, HOUSEHOLD)
    }
}

/** Wire type `internal/remote.MessagePayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root. */
@Serializable
public data class MessagePayload(
    @SerialName("title")
    public val title: String = "",
    @SerialName("body")
    public val body: String = "",
    @SerialName("severity")
    public val severity: String = "",
    @SerialName("timeout_ms")
    public val timeoutMs: Int = 0,
)

/** Wire type `internal/remote.ReasonPayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root. */
@Serializable
public data class ReasonPayload(
    @SerialName("reason")
    public val reason: String = "",
)

/** Wire type `internal/remote.ReplanOverrides`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. */
@Serializable
public data class ReplanOverrides(
    @SerialName("transcode")
    public val transcode: TranscodeMode = TranscodeMode(""),
    @SerialName("max_bitrate_kbps")
    public val maxBitrateKbps: Int = 0,
    @SerialName("video_codec")
    public val videoCodec: String = "",
    @SerialName("audio_codec")
    public val audioCodec: String = "",
    @SerialName("container")
    public val container: String = "",
)

/** Wire type `internal/remote.ReplanPayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root. */
@Serializable
public data class ReplanPayload(
    @SerialName("overrides")
    public val overrides: ReplanOverrides = ReplanOverrides(),
    @SerialName("reason")
    public val reason: String = "",
)

/** Wire type `internal/remote.Scope`. Direction: response. Dialect: bloem. Gate: notifications.remote_control. */
@Serializable
@JvmInline
public value class Scope(public val wire: String) {
    public companion object {
        @SerialName("session")
        public val SESSION: Scope = Scope("session")
        @SerialName("device")
        public val DEVICE: Scope = Scope("device")
        public val KNOWN: List<Scope> = listOf(SESSION, DEVICE)
    }
}

/** Wire type `internal/remote.SeekPayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root. */
@Serializable
public data class SeekPayload(
    @SerialName("position_ms")
    public val positionMs: Long = 0L,
)

/** Wire type `internal/remote.State`. Direction: response. Dialect: bloem. Gate: notifications.remote_control. */
@Serializable
@JvmInline
public value class State(public val wire: String) {
    public companion object {
        @SerialName("queued")
        public val QUEUED: State = State("queued")
        @SerialName("sent")
        public val SENT: State = State("sent")
        @SerialName("accepted")
        public val ACCEPTED: State = State("accepted")
        @SerialName("rejected")
        public val REJECTED: State = State("rejected")
        @SerialName("rejected_unsupported")
        public val REJECTED_UNSUPPORTED: State = State("rejected_unsupported")
        @SerialName("done")
        public val DONE: State = State("done")
        @SerialName("failed")
        public val FAILED: State = State("failed")
        @SerialName("expired")
        public val EXPIRED: State = State("expired")
        public val KNOWN: List<State> = listOf(QUEUED, SENT, ACCEPTED, REJECTED, REJECTED_UNSUPPORTED, DONE, FAILED, EXPIRED)
    }
}

/** Wire type `internal/remote.TrackPayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root. */
@Serializable
public data class TrackPayload(
    @SerialName("track_id")
    public val trackId: String = "",
    @SerialName("off")
    public val off: Boolean = false,
)

/** Wire type `internal/remote.TranscodeMode`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. */
@Serializable
@JvmInline
public value class TranscodeMode(public val wire: String) {
    public companion object {
        @SerialName("auto")
        public val AUTO: TranscodeMode = TranscodeMode("auto")
        @SerialName("force")
        public val FORCE: TranscodeMode = TranscodeMode("force")
        @SerialName("direct")
        public val DIRECT: TranscodeMode = TranscodeMode("direct")
        public val KNOWN: List<TranscodeMode> = listOf(AUTO, FORCE, DIRECT)
    }
}

/** Wire type `internal/remote.VolumePayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root. */
@Serializable
public data class VolumePayload(
    @SerialName("level")
    public val level: Int = 0,
)
