-- +goose Up
-- +goose StatementBegin
CREATE TABLE public.admin_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    actor_account_id integer NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    actor_platform_role text NOT NULL CHECK (actor_platform_role = 'platform_admin'),
    authority_context text NOT NULL CHECK (authority_context = 'platform'),
    action text NOT NULL,
    target_type text NOT NULL CHECK (target_type IN ('organization', 'membership')),
    target_id text NOT NULL,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
    subject_id text,
    before_revision bigint NOT NULL CHECK (before_revision >= 0),
    after_revision bigint NOT NULL CHECK (after_revision >= 0),
    outcome text NOT NULL CHECK (outcome IN ('success', 'conflict', 'failure')),
    request_id text,
    before_state jsonb NOT NULL DEFAULT '{}'::jsonb,
    after_state jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX admin_audit_events_organization_created_idx
    ON public.admin_audit_events(organization_id, created_at DESC, id DESC);
CREATE INDEX admin_audit_events_request_id_idx
    ON public.admin_audit_events(request_id)
    WHERE request_id IS NOT NULL;

CREATE FUNCTION public.reject_admin_audit_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'admin audit events are immutable';
END;
$$;

CREATE TRIGGER admin_audit_events_immutable
BEFORE UPDATE OR DELETE ON public.admin_audit_events
FOR EACH ROW EXECUTE FUNCTION public.reject_admin_audit_event_mutation();
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS admin_audit_events_immutable ON public.admin_audit_events;
DROP FUNCTION IF EXISTS public.reject_admin_audit_event_mutation();
DROP TABLE IF EXISTS public.admin_audit_events;
-- +goose StatementEnd
