-- +goose Up
-- +goose StatementBegin
-- Companion enrollment and revocable service trust.
--
-- A compat application is one enrolled companion instance (vondel-jellyfin or
-- vondel-audiobookshelf). Its kind and instance identity are immutable after
-- enrollment; everything the server needs to refuse it later — enablement,
-- revocation, granted capabilities, the API range it registered, an optional
-- bound client-certificate fingerprint — lives on the row. Secrets are never
-- stored: enrollment and credential tables hold SHA-256 digests only, and a
-- CHECK pins the column to digest shape so a direct SQL write cannot park a
-- raw secret at rest.

CREATE TABLE public.compat_applications (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    kind text NOT NULL CHECK (kind IN ('audiobookshelf', 'jellyfin')),
    instance_id text NOT NULL CHECK (btrim(instance_id) <> ''),
    version text NOT NULL CHECK (btrim(version) <> ''),
    -- NULL means the companion reported no resolved image digest (for
    -- example a non-container deployment); a present value must not be blank.
    image_digest text CHECK (image_digest IS NULL OR btrim(image_digest) <> ''),
    api_range_min integer NOT NULL CHECK (api_range_min >= 1),
    api_range_max integer NOT NULL,
    granted_capabilities text[] NOT NULL CHECK (cardinality(granted_capabilities) >= 1),
    -- SHA-256 (hex) of the TLS client certificate presented at enrollment.
    -- NULL means the application enrolled without one (same-host deployment)
    -- and authenticates by credential alone.
    tls_fingerprint text CHECK (tls_fingerprint IS NULL OR tls_fingerprint ~ '^[0-9a-f]{64}$'),
    enabled boolean NOT NULL DEFAULT true,
    health_status text NOT NULL DEFAULT 'unknown'
        CHECK (health_status IN ('unknown', 'healthy', 'degraded', 'unhealthy')),
    last_contact_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT compat_applications_api_range_check CHECK (api_range_max >= api_range_min),
    CONSTRAINT compat_applications_instance_key UNIQUE (kind, instance_id)
);

-- Instance identity and kind are fixed at enrollment. Enforcing it here means
-- a write that never passes through the service cannot re-point an issued
-- credential at a different companion identity.
CREATE FUNCTION public.vondel_compat_application_identity_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.kind IS DISTINCT FROM OLD.kind
       OR NEW.instance_id IS DISTINCT FROM OLD.instance_id THEN
        RAISE EXCEPTION 'compat application identity is immutable';
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER compat_applications_identity_guard
BEFORE UPDATE ON public.compat_applications
FOR EACH ROW EXECUTE FUNCTION public.vondel_compat_application_identity_guard();

CREATE TABLE public.compat_application_enrollments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    kind text NOT NULL CHECK (kind IN ('audiobookshelf', 'jellyfin')),
    secret_digest text NOT NULL CHECK (secret_digest ~ '^[0-9a-f]{64}$'),
    granted_capabilities text[] NOT NULL CHECK (cardinality(granted_capabilities) >= 1),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    application_id uuid REFERENCES public.compat_applications(id) ON DELETE SET NULL,
    CONSTRAINT compat_application_enrollments_secret_key UNIQUE (secret_digest),
    -- An unconsumed enrollment must not point at an application. Both
    -- branches state nullness explicitly so a half-written row cannot make
    -- the predicate evaluate to NULL and slip past the CHECK.
    CONSTRAINT compat_application_enrollments_consumed_pair_check CHECK (
        (consumed_at IS NULL AND application_id IS NULL)
        OR consumed_at IS NOT NULL
    )
);

CREATE TABLE public.compat_application_credentials (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id uuid NOT NULL REFERENCES public.compat_applications(id) ON DELETE CASCADE,
    secret_digest text NOT NULL CHECK (secret_digest ~ '^[0-9a-f]{64}$'),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    CONSTRAINT compat_application_credentials_secret_key UNIQUE (secret_digest)
);

CREATE INDEX compat_application_credentials_active_idx
    ON public.compat_application_credentials (application_id)
    WHERE revoked_at IS NULL;

CREATE TABLE public.compat_application_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    application_id uuid REFERENCES public.compat_applications(id) ON DELETE RESTRICT,
    enrollment_id uuid REFERENCES public.compat_application_enrollments(id) ON DELETE RESTRICT,
    event text NOT NULL CHECK (event IN (
        'enrollment_created', 'enrolled', 'rotated', 'revoked', 'enabled', 'disabled'
    )),
    detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    -- Every audit row names at least one subject; nullness is stated
    -- explicitly on both columns.
    CONSTRAINT compat_application_audit_subject_check CHECK (
        application_id IS NOT NULL OR enrollment_id IS NOT NULL
    )
);

CREATE INDEX compat_application_audit_application_idx
    ON public.compat_application_audit (application_id, id)
    WHERE application_id IS NOT NULL;

CREATE FUNCTION public.vondel_reject_compat_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'compat application audit rows are immutable';
END;
$$;

CREATE TRIGGER compat_application_audit_immutable
BEFORE UPDATE OR DELETE ON public.compat_application_audit
FOR EACH ROW EXECUTE FUNCTION public.vondel_reject_compat_audit_mutation();
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS compat_application_audit_immutable ON public.compat_application_audit;
DROP FUNCTION IF EXISTS public.vondel_reject_compat_audit_mutation();
DROP TABLE IF EXISTS public.compat_application_audit;
DROP TABLE IF EXISTS public.compat_application_credentials;
DROP TABLE IF EXISTS public.compat_application_enrollments;
DROP TRIGGER IF EXISTS compat_applications_identity_guard ON public.compat_applications;
DROP FUNCTION IF EXISTS public.vondel_compat_application_identity_guard();
DROP TABLE IF EXISTS public.compat_applications;
-- +goose StatementEnd
