// Code generated by cmd/clientdtogen from bloem-server internal/imagesize. DO NOT EDIT.
// Server revision: 7ef228d3e10c81f166d2445967c7ec6db2bcb102 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.imagesize

import kotlin.jvm.JvmInline
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/imagesize.Size`. Direction: response. Dialect: bloem. */
@Serializable
@JvmInline
public value class Size(public val wire: String) {
    public companion object {
        @SerialName("")
        public val UNSET: Size = Size("")
        @SerialName("small")
        public val SMALL: Size = Size("small")
        @SerialName("medium")
        public val MEDIUM: Size = Size("medium")
        @SerialName("large")
        public val LARGE: Size = Size("large")
        @SerialName("original")
        public val ORIGINAL: Size = Size("original")
        public val KNOWN: List<Size> = listOf(UNSET, SMALL, MEDIUM, LARGE, ORIGINAL)
    }
}
