// Code generated by cmd/clientdtogen from bloem-server internal/models. DO NOT EDIT.
// Server revision: 6b6f13f180e04ad8e0974ac12ea3b6562fd848d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/models`.
public enum Models {
    /// Wire type `internal/models.AudioTrack`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct AudioTrack: Codable, Hashable, Sendable {
        public let title: String
        public let embeddedTitle: String
        public let language: String
        public let codec: String
        public let profile: String
        public let layout: String
        public let channels: Int
        public let bitrate: Int
        public let sampleRate: Int
        public let bitDepth: Int
        public let defaultValue: Bool

        public enum CodingKeys: String, CodingKey {
            case title = "title"
            case embeddedTitle = "embedded_title"
            case language = "language"
            case codec = "codec"
            case profile = "profile"
            case layout = "layout"
            case channels = "channels"
            case bitrate = "bitrate"
            case sampleRate = "sample_rate"
            case bitDepth = "bit_depth"
            case defaultValue = "default"
        }

        public init(
            title: String = "",
            embeddedTitle: String = "",
            language: String = "",
            codec: String = "",
            profile: String = "",
            layout: String = "",
            channels: Int = 0,
            bitrate: Int = 0,
            sampleRate: Int = 0,
            bitDepth: Int = 0,
            defaultValue: Bool = false
        ) {
            self.title = title
            self.embeddedTitle = embeddedTitle
            self.language = language
            self.codec = codec
            self.profile = profile
            self.layout = layout
            self.channels = channels
            self.bitrate = bitrate
            self.sampleRate = sampleRate
            self.bitDepth = bitDepth
            self.defaultValue = defaultValue
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? ""
            self.embeddedTitle = try container.decodeIfPresent(String.self, forKey: .embeddedTitle) ?? ""
            self.language = try container.decodeIfPresent(String.self, forKey: .language) ?? ""
            self.codec = try container.decodeIfPresent(String.self, forKey: .codec) ?? ""
            self.profile = try container.decodeIfPresent(String.self, forKey: .profile) ?? ""
            self.layout = try container.decodeIfPresent(String.self, forKey: .layout) ?? ""
            self.channels = try container.decodeIfPresent(Int.self, forKey: .channels) ?? 0
            self.bitrate = try container.decodeIfPresent(Int.self, forKey: .bitrate) ?? 0
            self.sampleRate = try container.decodeIfPresent(Int.self, forKey: .sampleRate) ?? 0
            self.bitDepth = try container.decodeIfPresent(Int.self, forKey: .bitDepth) ?? 0
            self.defaultValue = try container.decodeIfPresent(Bool.self, forKey: .defaultValue) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.embeddedTitle, forKey: .embeddedTitle)
            try container.encode(self.language, forKey: .language)
            try container.encode(self.codec, forKey: .codec)
            try container.encode(self.profile, forKey: .profile)
            try container.encode(self.layout, forKey: .layout)
            try container.encode(self.channels, forKey: .channels)
            try container.encode(self.bitrate, forKey: .bitrate)
            try container.encode(self.sampleRate, forKey: .sampleRate)
            try container.encode(self.bitDepth, forKey: .bitDepth)
            try container.encode(self.defaultValue, forKey: .defaultValue)
        }
    }

    /// Wire type `internal/models.OverlaySummary`. Direction: response. Dialect: upstream-compat.
    public struct OverlaySummary: Codable, Hashable, Sendable {
        public let resolution: String
        public let hdr: String
        public let audio: String
        public let audioChannels: String
        public let videoCodec: String
        public let container: String
        public let aspectRatio: String
        public let releaseType: String
        public let edition: String
        public let multiAudio: Bool
        public let multiSub: Bool

        public enum CodingKeys: String, CodingKey {
            case resolution = "resolution"
            case hdr = "hdr"
            case audio = "audio"
            case audioChannels = "audio_channels"
            case videoCodec = "video_codec"
            case container = "container"
            case aspectRatio = "aspect_ratio"
            case releaseType = "release_type"
            case edition = "edition"
            case multiAudio = "multi_audio"
            case multiSub = "multi_sub"
        }

        public init(
            resolution: String = "",
            hdr: String = "",
            audio: String = "",
            audioChannels: String = "",
            videoCodec: String = "",
            container: String = "",
            aspectRatio: String = "",
            releaseType: String = "",
            edition: String = "",
            multiAudio: Bool = false,
            multiSub: Bool = false
        ) {
            self.resolution = resolution
            self.hdr = hdr
            self.audio = audio
            self.audioChannels = audioChannels
            self.videoCodec = videoCodec
            self.container = container
            self.aspectRatio = aspectRatio
            self.releaseType = releaseType
            self.edition = edition
            self.multiAudio = multiAudio
            self.multiSub = multiSub
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.resolution = try container.decodeIfPresent(String.self, forKey: .resolution) ?? ""
            self.hdr = try container.decodeIfPresent(String.self, forKey: .hdr) ?? ""
            self.audio = try container.decodeIfPresent(String.self, forKey: .audio) ?? ""
            self.audioChannels = try container.decodeIfPresent(String.self, forKey: .audioChannels) ?? ""
            self.videoCodec = try container.decodeIfPresent(String.self, forKey: .videoCodec) ?? ""
            self.container = try container.decodeIfPresent(String.self, forKey: .container) ?? ""
            self.aspectRatio = try container.decodeIfPresent(String.self, forKey: .aspectRatio) ?? ""
            self.releaseType = try container.decodeIfPresent(String.self, forKey: .releaseType) ?? ""
            self.edition = try container.decodeIfPresent(String.self, forKey: .edition) ?? ""
            self.multiAudio = try container.decodeIfPresent(Bool.self, forKey: .multiAudio) ?? false
            self.multiSub = try container.decodeIfPresent(Bool.self, forKey: .multiSub) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.resolution, forKey: .resolution)
            try container.encode(self.hdr, forKey: .hdr)
            try container.encode(self.audio, forKey: .audio)
            try container.encode(self.audioChannels, forKey: .audioChannels)
            try container.encode(self.videoCodec, forKey: .videoCodec)
            try container.encode(self.container, forKey: .container)
            try container.encode(self.aspectRatio, forKey: .aspectRatio)
            try container.encode(self.releaseType, forKey: .releaseType)
            try container.encode(self.edition, forKey: .edition)
            try container.encode(self.multiAudio, forKey: .multiAudio)
            try container.encode(self.multiSub, forKey: .multiSub)
        }
    }

    /// Wire type `internal/models.SubtitleTrack`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct SubtitleTrack: Codable, Hashable, Sendable {
        public let index: Int
        public let language: String
        public let codec: String
        public let title: String
        public let embeddedTitle: String
        public let resolution: String
        public let forced: Bool
        public let defaultValue: Bool
        public let hearingImpaired: Bool
        public let external: Bool
        public let fileName: String

        public enum CodingKeys: String, CodingKey {
            case index = "index"
            case language = "language"
            case codec = "codec"
            case title = "title"
            case embeddedTitle = "embedded_title"
            case resolution = "resolution"
            case forced = "forced"
            case defaultValue = "default"
            case hearingImpaired = "hearing_impaired"
            case external = "external"
            case fileName = "file_name"
        }

        public init(
            index: Int = 0,
            language: String = "",
            codec: String = "",
            title: String = "",
            embeddedTitle: String = "",
            resolution: String = "",
            forced: Bool = false,
            defaultValue: Bool = false,
            hearingImpaired: Bool = false,
            external: Bool = false,
            fileName: String = ""
        ) {
            self.index = index
            self.language = language
            self.codec = codec
            self.title = title
            self.embeddedTitle = embeddedTitle
            self.resolution = resolution
            self.forced = forced
            self.defaultValue = defaultValue
            self.hearingImpaired = hearingImpaired
            self.external = external
            self.fileName = fileName
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.index = try container.decodeIfPresent(Int.self, forKey: .index) ?? 0
            self.language = try container.decodeIfPresent(String.self, forKey: .language) ?? ""
            self.codec = try container.decodeIfPresent(String.self, forKey: .codec) ?? ""
            self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? ""
            self.embeddedTitle = try container.decodeIfPresent(String.self, forKey: .embeddedTitle) ?? ""
            self.resolution = try container.decodeIfPresent(String.self, forKey: .resolution) ?? ""
            self.forced = try container.decodeIfPresent(Bool.self, forKey: .forced) ?? false
            self.defaultValue = try container.decodeIfPresent(Bool.self, forKey: .defaultValue) ?? false
            self.hearingImpaired = try container.decodeIfPresent(Bool.self, forKey: .hearingImpaired) ?? false
            self.external = try container.decodeIfPresent(Bool.self, forKey: .external) ?? false
            self.fileName = try container.decodeIfPresent(String.self, forKey: .fileName) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.index, forKey: .index)
            try container.encode(self.language, forKey: .language)
            try container.encode(self.codec, forKey: .codec)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.embeddedTitle, forKey: .embeddedTitle)
            try container.encode(self.resolution, forKey: .resolution)
            try container.encode(self.forced, forKey: .forced)
            try container.encode(self.defaultValue, forKey: .defaultValue)
            try container.encode(self.hearingImpaired, forKey: .hearingImpaired)
            try container.encode(self.external, forKey: .external)
            try container.encode(self.fileName, forKey: .fileName)
        }
    }

    /// Wire type `internal/models.VideoTrack`. Direction: response. Dialect: upstream-compat. Registered root.
    public struct VideoTrack: Codable, Hashable, Sendable {
        public let title: String
        public let codec: String
        public let dolbyVision: String
        public let dvProfile: Int
        public let dvLevel: Int
        public let dvblCompatId: Int
        public let dvConfigPresent: Bool
        public let dvblCompatIdPresent: Bool
        public let dvblPresent: Bool
        public let dvrpuPresent: Bool
        public let dvelPresent: Bool
        public let dvEnhancementLayer: String
        public let hdr10Plus: Bool
        public let profile: String
        public let level: Int
        public let width: Int
        public let height: Int
        public let aspectRatio: String
        public let interlaced: Bool
        public let frameRate: FrameRateWire?
        public let bitrate: Int
        public let videoRange: String
        public let videoRangeType: String
        public let colorRange: String
        public let colorPrimaries: String
        public let colorSpace: String
        public let colorTransfer: String
        public let bitDepth: Int
        public let pixelFormat: String
        public let referenceFrames: Int

        public enum CodingKeys: String, CodingKey {
            case title = "title"
            case codec = "codec"
            case dolbyVision = "dolby_vision"
            case dvProfile = "dv_profile"
            case dvLevel = "dv_level"
            case dvblCompatId = "dv_bl_compat_id"
            case dvConfigPresent = "dv_config_present"
            case dvblCompatIdPresent = "dv_bl_compat_id_present"
            case dvblPresent = "dv_bl_present"
            case dvrpuPresent = "dv_rpu_present"
            case dvelPresent = "dv_el_present"
            case dvEnhancementLayer = "dv_enhancement_layer"
            case hdr10Plus = "hdr10_plus"
            case profile = "profile"
            case level = "level"
            case width = "width"
            case height = "height"
            case aspectRatio = "aspect_ratio"
            case interlaced = "interlaced"
            case frameRate = "frame_rate"
            case bitrate = "bitrate"
            case videoRange = "video_range"
            case videoRangeType = "video_range_type"
            case colorRange = "color_range"
            case colorPrimaries = "color_primaries"
            case colorSpace = "color_space"
            case colorTransfer = "color_transfer"
            case bitDepth = "bit_depth"
            case pixelFormat = "pixel_format"
            case referenceFrames = "reference_frames"
        }

        public init(
            title: String = "",
            codec: String = "",
            dolbyVision: String = "",
            dvProfile: Int = 0,
            dvLevel: Int = 0,
            dvblCompatId: Int = 0,
            dvConfigPresent: Bool = false,
            dvblCompatIdPresent: Bool = false,
            dvblPresent: Bool = false,
            dvrpuPresent: Bool = false,
            dvelPresent: Bool = false,
            dvEnhancementLayer: String = "",
            hdr10Plus: Bool = false,
            profile: String = "",
            level: Int = 0,
            width: Int = 0,
            height: Int = 0,
            aspectRatio: String = "",
            interlaced: Bool = false,
            frameRate: FrameRateWire? = nil,
            bitrate: Int = 0,
            videoRange: String = "",
            videoRangeType: String = "",
            colorRange: String = "",
            colorPrimaries: String = "",
            colorSpace: String = "",
            colorTransfer: String = "",
            bitDepth: Int = 0,
            pixelFormat: String = "",
            referenceFrames: Int = 0
        ) {
            self.title = title
            self.codec = codec
            self.dolbyVision = dolbyVision
            self.dvProfile = dvProfile
            self.dvLevel = dvLevel
            self.dvblCompatId = dvblCompatId
            self.dvConfigPresent = dvConfigPresent
            self.dvblCompatIdPresent = dvblCompatIdPresent
            self.dvblPresent = dvblPresent
            self.dvrpuPresent = dvrpuPresent
            self.dvelPresent = dvelPresent
            self.dvEnhancementLayer = dvEnhancementLayer
            self.hdr10Plus = hdr10Plus
            self.profile = profile
            self.level = level
            self.width = width
            self.height = height
            self.aspectRatio = aspectRatio
            self.interlaced = interlaced
            self.frameRate = frameRate
            self.bitrate = bitrate
            self.videoRange = videoRange
            self.videoRangeType = videoRangeType
            self.colorRange = colorRange
            self.colorPrimaries = colorPrimaries
            self.colorSpace = colorSpace
            self.colorTransfer = colorTransfer
            self.bitDepth = bitDepth
            self.pixelFormat = pixelFormat
            self.referenceFrames = referenceFrames
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? ""
            self.codec = try container.decodeIfPresent(String.self, forKey: .codec) ?? ""
            self.dolbyVision = try container.decodeIfPresent(String.self, forKey: .dolbyVision) ?? ""
            self.dvProfile = try container.decodeIfPresent(Int.self, forKey: .dvProfile) ?? 0
            self.dvLevel = try container.decodeIfPresent(Int.self, forKey: .dvLevel) ?? 0
            self.dvblCompatId = try container.decodeIfPresent(Int.self, forKey: .dvblCompatId) ?? 0
            self.dvConfigPresent = try container.decodeIfPresent(Bool.self, forKey: .dvConfigPresent) ?? false
            self.dvblCompatIdPresent = try container.decodeIfPresent(Bool.self, forKey: .dvblCompatIdPresent) ?? false
            self.dvblPresent = try container.decodeIfPresent(Bool.self, forKey: .dvblPresent) ?? false
            self.dvrpuPresent = try container.decodeIfPresent(Bool.self, forKey: .dvrpuPresent) ?? false
            self.dvelPresent = try container.decodeIfPresent(Bool.self, forKey: .dvelPresent) ?? false
            self.dvEnhancementLayer = try container.decodeIfPresent(String.self, forKey: .dvEnhancementLayer) ?? ""
            self.hdr10Plus = try container.decodeIfPresent(Bool.self, forKey: .hdr10Plus) ?? false
            self.profile = try container.decodeIfPresent(String.self, forKey: .profile) ?? ""
            self.level = try container.decodeIfPresent(Int.self, forKey: .level) ?? 0
            self.width = try container.decodeIfPresent(Int.self, forKey: .width) ?? 0
            self.height = try container.decodeIfPresent(Int.self, forKey: .height) ?? 0
            self.aspectRatio = try container.decodeIfPresent(String.self, forKey: .aspectRatio) ?? ""
            self.interlaced = try container.decodeIfPresent(Bool.self, forKey: .interlaced) ?? false
            self.frameRate = try container.decodeIfPresent(FrameRateWire.self, forKey: .frameRate)
            self.bitrate = try container.decodeIfPresent(Int.self, forKey: .bitrate) ?? 0
            self.videoRange = try container.decodeIfPresent(String.self, forKey: .videoRange) ?? ""
            self.videoRangeType = try container.decodeIfPresent(String.self, forKey: .videoRangeType) ?? ""
            self.colorRange = try container.decodeIfPresent(String.self, forKey: .colorRange) ?? ""
            self.colorPrimaries = try container.decodeIfPresent(String.self, forKey: .colorPrimaries) ?? ""
            self.colorSpace = try container.decodeIfPresent(String.self, forKey: .colorSpace) ?? ""
            self.colorTransfer = try container.decodeIfPresent(String.self, forKey: .colorTransfer) ?? ""
            self.bitDepth = try container.decodeIfPresent(Int.self, forKey: .bitDepth) ?? 0
            self.pixelFormat = try container.decodeIfPresent(String.self, forKey: .pixelFormat) ?? ""
            self.referenceFrames = try container.decodeIfPresent(Int.self, forKey: .referenceFrames) ?? 0
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.codec, forKey: .codec)
            try container.encode(self.dolbyVision, forKey: .dolbyVision)
            try container.encode(self.dvProfile, forKey: .dvProfile)
            try container.encode(self.dvLevel, forKey: .dvLevel)
            try container.encode(self.dvblCompatId, forKey: .dvblCompatId)
            try container.encode(self.dvConfigPresent, forKey: .dvConfigPresent)
            try container.encode(self.dvblCompatIdPresent, forKey: .dvblCompatIdPresent)
            try container.encode(self.dvblPresent, forKey: .dvblPresent)
            try container.encode(self.dvrpuPresent, forKey: .dvrpuPresent)
            try container.encode(self.dvelPresent, forKey: .dvelPresent)
            try container.encode(self.dvEnhancementLayer, forKey: .dvEnhancementLayer)
            try container.encode(self.hdr10Plus, forKey: .hdr10Plus)
            try container.encode(self.profile, forKey: .profile)
            try container.encode(self.level, forKey: .level)
            try container.encode(self.width, forKey: .width)
            try container.encode(self.height, forKey: .height)
            try container.encode(self.aspectRatio, forKey: .aspectRatio)
            try container.encode(self.interlaced, forKey: .interlaced)
            try container.encodeIfPresent(self.frameRate, forKey: .frameRate)
            try container.encode(self.bitrate, forKey: .bitrate)
            try container.encode(self.videoRange, forKey: .videoRange)
            try container.encode(self.videoRangeType, forKey: .videoRangeType)
            try container.encode(self.colorRange, forKey: .colorRange)
            try container.encode(self.colorPrimaries, forKey: .colorPrimaries)
            try container.encode(self.colorSpace, forKey: .colorSpace)
            try container.encode(self.colorTransfer, forKey: .colorTransfer)
            try container.encode(self.bitDepth, forKey: .bitDepth)
            try container.encode(self.pixelFormat, forKey: .pixelFormat)
            try container.encode(self.referenceFrames, forKey: .referenceFrames)
        }
    }
}
