// Code generated by cmd/clientdtogen from bloem-server internal/watchsync. DO NOT EDIT.
// Server revision: 7ef228d3e10c81f166d2445967c7ec6db2bcb102 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/watchsync`.
public enum Watchsync {
    /// Wire type `internal/watchsync.Capabilities`. Direction: response. Dialect: bloem.
    public struct Capabilities: Codable, Hashable, Sendable {
        public let importWatched: Bool
        public let importProgress: Bool
        public let exportWatched: Bool
        public let exportUnwatched: Bool
        public let importFavorites: Bool
        public let exportFavorites: Bool
        public let removeFavorites: Bool
        public let importWatchlist: Bool
        public let exportWatchlist: Bool
        public let removeWatchlist: Bool
        public let providesWatchlistOrder: Bool
        public let scrobblePlayback: Bool

        public enum CodingKeys: String, CodingKey {
            case importWatched = "import_watched"
            case importProgress = "import_progress"
            case exportWatched = "export_watched"
            case exportUnwatched = "export_unwatched"
            case importFavorites = "import_favorites"
            case exportFavorites = "export_favorites"
            case removeFavorites = "remove_favorites"
            case importWatchlist = "import_watchlist"
            case exportWatchlist = "export_watchlist"
            case removeWatchlist = "remove_watchlist"
            case providesWatchlistOrder = "provides_watchlist_order"
            case scrobblePlayback = "scrobble_playback"
        }

        public init(
            importWatched: Bool = false,
            importProgress: Bool = false,
            exportWatched: Bool = false,
            exportUnwatched: Bool = false,
            importFavorites: Bool = false,
            exportFavorites: Bool = false,
            removeFavorites: Bool = false,
            importWatchlist: Bool = false,
            exportWatchlist: Bool = false,
            removeWatchlist: Bool = false,
            providesWatchlistOrder: Bool = false,
            scrobblePlayback: Bool = false
        ) {
            self.importWatched = importWatched
            self.importProgress = importProgress
            self.exportWatched = exportWatched
            self.exportUnwatched = exportUnwatched
            self.importFavorites = importFavorites
            self.exportFavorites = exportFavorites
            self.removeFavorites = removeFavorites
            self.importWatchlist = importWatchlist
            self.exportWatchlist = exportWatchlist
            self.removeWatchlist = removeWatchlist
            self.providesWatchlistOrder = providesWatchlistOrder
            self.scrobblePlayback = scrobblePlayback
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.importWatched = try container.decodeIfPresent(Bool.self, forKey: .importWatched) ?? false
            self.importProgress = try container.decodeIfPresent(Bool.self, forKey: .importProgress) ?? false
            self.exportWatched = try container.decodeIfPresent(Bool.self, forKey: .exportWatched) ?? false
            self.exportUnwatched = try container.decodeIfPresent(Bool.self, forKey: .exportUnwatched) ?? false
            self.importFavorites = try container.decodeIfPresent(Bool.self, forKey: .importFavorites) ?? false
            self.exportFavorites = try container.decodeIfPresent(Bool.self, forKey: .exportFavorites) ?? false
            self.removeFavorites = try container.decodeIfPresent(Bool.self, forKey: .removeFavorites) ?? false
            self.importWatchlist = try container.decodeIfPresent(Bool.self, forKey: .importWatchlist) ?? false
            self.exportWatchlist = try container.decodeIfPresent(Bool.self, forKey: .exportWatchlist) ?? false
            self.removeWatchlist = try container.decodeIfPresent(Bool.self, forKey: .removeWatchlist) ?? false
            self.providesWatchlistOrder = try container.decodeIfPresent(Bool.self, forKey: .providesWatchlistOrder) ?? false
            self.scrobblePlayback = try container.decodeIfPresent(Bool.self, forKey: .scrobblePlayback) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.importWatched, forKey: .importWatched)
            try container.encode(self.importProgress, forKey: .importProgress)
            try container.encode(self.exportWatched, forKey: .exportWatched)
            try container.encode(self.exportUnwatched, forKey: .exportUnwatched)
            try container.encode(self.importFavorites, forKey: .importFavorites)
            try container.encode(self.exportFavorites, forKey: .exportFavorites)
            try container.encode(self.removeFavorites, forKey: .removeFavorites)
            try container.encode(self.importWatchlist, forKey: .importWatchlist)
            try container.encode(self.exportWatchlist, forKey: .exportWatchlist)
            try container.encode(self.removeWatchlist, forKey: .removeWatchlist)
            try container.encode(self.providesWatchlistOrder, forKey: .providesWatchlistOrder)
            try container.encode(self.scrobblePlayback, forKey: .scrobblePlayback)
        }
    }
}
