// Code generated by cmd/clientdtogen from bloem-server internal/watchtogether. DO NOT EDIT.
// Server revision: 6b6f13f180e04ad8e0974ac12ea3b6562fd848d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/watchtogether`.
public enum Watchtogether {
    /// Wire type `internal/watchtogether.GuestControlPolicy`. Direction: both. Dialect: upstream-compat.
    public struct GuestControlPolicy: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let HOST_ONLY: GuestControlPolicy = GuestControlPolicy(rawValue: "host_only")
        public static let GUEST_PLAY_PAUSE: GuestControlPolicy = GuestControlPolicy(rawValue: "guest_play_pause")
        public static let KNOWN: [GuestControlPolicy] = [HOST_ONLY, GUEST_PLAY_PAUSE]
    }

    /// Wire type `internal/watchtogether.MemberRole`. Direction: response. Dialect: upstream-compat.
    public struct MemberRole: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let HOST: MemberRole = MemberRole(rawValue: "host")
        public static let GUEST: MemberRole = MemberRole(rawValue: "guest")
        public static let KNOWN: [MemberRole] = [HOST, GUEST]
    }

    /// Wire type `internal/watchtogether.MemberSummary`. Direction: response. Dialect: upstream-compat.
    public struct MemberSummary: Codable, Hashable, Sendable {
        public let userId: Int
        public let profileId: String
        public let displayName: String
        public let isHost: Bool
        public let isSelf: Bool
        public let connected: Bool

        public enum CodingKeys: String, CodingKey {
            case userId = "user_id"
            case profileId = "profile_id"
            case displayName = "display_name"
            case isHost = "is_host"
            case isSelf = "is_self"
            case connected = "connected"
        }

        public init(
            userId: Int = 0,
            profileId: String = "",
            displayName: String = "",
            isHost: Bool = false,
            isSelf: Bool = false,
            connected: Bool = false
        ) {
            self.userId = userId
            self.profileId = profileId
            self.displayName = displayName
            self.isHost = isHost
            self.isSelf = isSelf
            self.connected = connected
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.userId = try container.decodeIfPresent(Int.self, forKey: .userId) ?? 0
            self.profileId = try container.decodeIfPresent(String.self, forKey: .profileId) ?? ""
            self.displayName = try container.decodeIfPresent(String.self, forKey: .displayName) ?? ""
            self.isHost = try container.decodeIfPresent(Bool.self, forKey: .isHost) ?? false
            self.isSelf = try container.decodeIfPresent(Bool.self, forKey: .isSelf) ?? false
            self.connected = try container.decodeIfPresent(Bool.self, forKey: .connected) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.userId, forKey: .userId)
            try container.encode(self.profileId, forKey: .profileId)
            try container.encode(self.displayName, forKey: .displayName)
            try container.encode(self.isHost, forKey: .isHost)
            try container.encode(self.isSelf, forKey: .isSelf)
            try container.encode(self.connected, forKey: .connected)
        }
    }

    /// Wire type `internal/watchtogether.RoomPhase`. Direction: response. Dialect: upstream-compat.
    public struct RoomPhase: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let LOBBY: RoomPhase = RoomPhase(rawValue: "lobby")
        public static let PLAYING: RoomPhase = RoomPhase(rawValue: "playing")
        public static let ENDED: RoomPhase = RoomPhase(rawValue: "ended")
        public static let KNOWN: [RoomPhase] = [LOBBY, PLAYING, ENDED]
    }

    /// Wire type `internal/watchtogether.RoomPlaybackState`. Direction: response. Dialect: upstream-compat.
    public struct RoomPlaybackState: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let IDLE: RoomPlaybackState = RoomPlaybackState(rawValue: "idle")
        public static let WAITING: RoomPlaybackState = RoomPlaybackState(rawValue: "waiting")
        public static let PAUSED: RoomPlaybackState = RoomPlaybackState(rawValue: "paused")
        public static let PLAYING: RoomPlaybackState = RoomPlaybackState(rawValue: "playing")
        public static let KNOWN: [RoomPlaybackState] = [IDLE, WAITING, PAUSED, PLAYING]
    }

    /// Wire type `internal/watchtogether.RoomSelectionMode`. Direction: response. Dialect: upstream-compat.
    public struct RoomSelectionMode: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let HOST_PICK: RoomSelectionMode = RoomSelectionMode(rawValue: "host_pick")
        public static let VOTE: RoomSelectionMode = RoomSelectionMode(rawValue: "vote")
        public static let KNOWN: [RoomSelectionMode] = [HOST_PICK, VOTE]
    }

    /// Wire type `internal/watchtogether.Snapshot`. Direction: response. Dialect: upstream-compat.
    public struct Snapshot: Codable, Hashable, Sendable {
        public let roomId: String
        public let phase: RoomPhase
        public let playbackState: RoomPlaybackState
        public let selectionMode: RoomSelectionMode
        public let selectionRevision: Int64
        public let selectedContentId: String?
        public let selectedFileId: Int?
        public let selectedLibraryId: Int?
        public let code: String
        public let guestControlPolicy: GuestControlPolicy
        public let isPaused: Bool
        public let anchorPositionSeconds: Double
        public let anchorUpdatedAt: String
        public let generation: Int64
        public let ownerGeneration: Int64
        public let memberCount: Int
        public let hostConnected: Bool
        public let selfRole: MemberRole
        public let selfCanControlTransport: Bool
        public let selfCanManageRoom: Bool
        public let selfIgnoreWait: Bool
        public let attachedSessionId: String
        public let invitePath: String
        public let members: [MemberSummary]

        public enum CodingKeys: String, CodingKey {
            case roomId = "room_id"
            case phase = "phase"
            case playbackState = "playback_state"
            case selectionMode = "selection_mode"
            case selectionRevision = "selection_revision"
            case selectedContentId = "selected_content_id"
            case selectedFileId = "selected_file_id"
            case selectedLibraryId = "selected_library_id"
            case code = "code"
            case guestControlPolicy = "guest_control_policy"
            case isPaused = "is_paused"
            case anchorPositionSeconds = "anchor_position_seconds"
            case anchorUpdatedAt = "anchor_updated_at"
            case generation = "generation"
            case ownerGeneration = "owner_generation"
            case memberCount = "member_count"
            case hostConnected = "host_connected"
            case selfRole = "self_role"
            case selfCanControlTransport = "self_can_control_transport"
            case selfCanManageRoom = "self_can_manage_room"
            case selfIgnoreWait = "self_ignore_wait"
            case attachedSessionId = "attached_session_id"
            case invitePath = "invite_path"
            case members = "members"
        }

        public init(
            roomId: String = "",
            phase: RoomPhase = RoomPhase(rawValue: ""),
            playbackState: RoomPlaybackState = RoomPlaybackState(rawValue: ""),
            selectionMode: RoomSelectionMode = RoomSelectionMode(rawValue: ""),
            selectionRevision: Int64 = 0,
            selectedContentId: String? = nil,
            selectedFileId: Int? = nil,
            selectedLibraryId: Int? = nil,
            code: String = "",
            guestControlPolicy: GuestControlPolicy = GuestControlPolicy(rawValue: ""),
            isPaused: Bool = false,
            anchorPositionSeconds: Double = 0.0,
            anchorUpdatedAt: String = "",
            generation: Int64 = 0,
            ownerGeneration: Int64 = 0,
            memberCount: Int = 0,
            hostConnected: Bool = false,
            selfRole: MemberRole = MemberRole(rawValue: ""),
            selfCanControlTransport: Bool = false,
            selfCanManageRoom: Bool = false,
            selfIgnoreWait: Bool = false,
            attachedSessionId: String = "",
            invitePath: String = "",
            members: [MemberSummary] = []
        ) {
            self.roomId = roomId
            self.phase = phase
            self.playbackState = playbackState
            self.selectionMode = selectionMode
            self.selectionRevision = selectionRevision
            self.selectedContentId = selectedContentId
            self.selectedFileId = selectedFileId
            self.selectedLibraryId = selectedLibraryId
            self.code = code
            self.guestControlPolicy = guestControlPolicy
            self.isPaused = isPaused
            self.anchorPositionSeconds = anchorPositionSeconds
            self.anchorUpdatedAt = anchorUpdatedAt
            self.generation = generation
            self.ownerGeneration = ownerGeneration
            self.memberCount = memberCount
            self.hostConnected = hostConnected
            self.selfRole = selfRole
            self.selfCanControlTransport = selfCanControlTransport
            self.selfCanManageRoom = selfCanManageRoom
            self.selfIgnoreWait = selfIgnoreWait
            self.attachedSessionId = attachedSessionId
            self.invitePath = invitePath
            self.members = members
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.roomId = try container.decodeIfPresent(String.self, forKey: .roomId) ?? ""
            self.phase = try container.decodeIfPresent(RoomPhase.self, forKey: .phase) ?? RoomPhase(rawValue: "")
            self.playbackState = try container.decodeIfPresent(RoomPlaybackState.self, forKey: .playbackState) ?? RoomPlaybackState(rawValue: "")
            self.selectionMode = try container.decodeIfPresent(RoomSelectionMode.self, forKey: .selectionMode) ?? RoomSelectionMode(rawValue: "")
            self.selectionRevision = try container.decodeIfPresent(Int64.self, forKey: .selectionRevision) ?? 0
            self.selectedContentId = try container.decodeIfPresent(String.self, forKey: .selectedContentId)
            self.selectedFileId = try container.decodeIfPresent(Int.self, forKey: .selectedFileId)
            self.selectedLibraryId = try container.decodeIfPresent(Int.self, forKey: .selectedLibraryId)
            self.code = try container.decodeIfPresent(String.self, forKey: .code) ?? ""
            self.guestControlPolicy = try container.decodeIfPresent(GuestControlPolicy.self, forKey: .guestControlPolicy) ?? GuestControlPolicy(rawValue: "")
            self.isPaused = try container.decodeIfPresent(Bool.self, forKey: .isPaused) ?? false
            self.anchorPositionSeconds = try container.decodeIfPresent(Double.self, forKey: .anchorPositionSeconds) ?? 0.0
            self.anchorUpdatedAt = try container.decodeIfPresent(String.self, forKey: .anchorUpdatedAt) ?? ""
            self.generation = try container.decodeIfPresent(Int64.self, forKey: .generation) ?? 0
            self.ownerGeneration = try container.decodeIfPresent(Int64.self, forKey: .ownerGeneration) ?? 0
            self.memberCount = try container.decodeIfPresent(Int.self, forKey: .memberCount) ?? 0
            self.hostConnected = try container.decodeIfPresent(Bool.self, forKey: .hostConnected) ?? false
            self.selfRole = try container.decodeIfPresent(MemberRole.self, forKey: .selfRole) ?? MemberRole(rawValue: "")
            self.selfCanControlTransport = try container.decodeIfPresent(Bool.self, forKey: .selfCanControlTransport) ?? false
            self.selfCanManageRoom = try container.decodeIfPresent(Bool.self, forKey: .selfCanManageRoom) ?? false
            self.selfIgnoreWait = try container.decodeIfPresent(Bool.self, forKey: .selfIgnoreWait) ?? false
            self.attachedSessionId = try container.decodeIfPresent(String.self, forKey: .attachedSessionId) ?? ""
            self.invitePath = try container.decodeIfPresent(String.self, forKey: .invitePath) ?? ""
            self.members = try container.decodeIfPresent([MemberSummary].self, forKey: .members) ?? []
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.roomId, forKey: .roomId)
            try container.encode(self.phase, forKey: .phase)
            try container.encode(self.playbackState, forKey: .playbackState)
            try container.encode(self.selectionMode, forKey: .selectionMode)
            try container.encode(self.selectionRevision, forKey: .selectionRevision)
            try container.encodeIfPresent(self.selectedContentId, forKey: .selectedContentId)
            try container.encodeIfPresent(self.selectedFileId, forKey: .selectedFileId)
            try container.encodeIfPresent(self.selectedLibraryId, forKey: .selectedLibraryId)
            try container.encode(self.code, forKey: .code)
            try container.encode(self.guestControlPolicy, forKey: .guestControlPolicy)
            try container.encode(self.isPaused, forKey: .isPaused)
            try container.encode(self.anchorPositionSeconds, forKey: .anchorPositionSeconds)
            try container.encode(self.anchorUpdatedAt, forKey: .anchorUpdatedAt)
            try container.encode(self.generation, forKey: .generation)
            try container.encode(self.ownerGeneration, forKey: .ownerGeneration)
            try container.encode(self.memberCount, forKey: .memberCount)
            try container.encode(self.hostConnected, forKey: .hostConnected)
            try container.encode(self.selfRole, forKey: .selfRole)
            try container.encode(self.selfCanControlTransport, forKey: .selfCanControlTransport)
            try container.encode(self.selfCanManageRoom, forKey: .selfCanManageRoom)
            try container.encode(self.selfIgnoreWait, forKey: .selfIgnoreWait)
            try container.encode(self.attachedSessionId, forKey: .attachedSessionId)
            try container.encode(self.invitePath, forKey: .invitePath)
            try container.encode(self.members, forKey: .members)
        }
    }

    /// Wire type `internal/watchtogether.Suggestion`. Direction: response. Dialect: upstream-compat.
    public struct Suggestion: Codable, Hashable, Sendable {
        public let id: String
        public let roomId: String
        public let suggesterUserId: Int
        public let suggesterProfileId: String
        public let contentId: String
        public let contentType: String
        public let title: String
        public let subtitle: String
        public let posterUrl: String
        public let note: String
        public let voteCount: Int
        public let votedByMe: Bool
        public let createdAt: String

        public enum CodingKeys: String, CodingKey {
            case id = "id"
            case roomId = "room_id"
            case suggesterUserId = "suggester_user_id"
            case suggesterProfileId = "suggester_profile_id"
            case contentId = "content_id"
            case contentType = "content_type"
            case title = "title"
            case subtitle = "subtitle"
            case posterUrl = "poster_url"
            case note = "note"
            case voteCount = "vote_count"
            case votedByMe = "voted_by_me"
            case createdAt = "created_at"
        }

        public init(
            id: String = "",
            roomId: String = "",
            suggesterUserId: Int = 0,
            suggesterProfileId: String = "",
            contentId: String = "",
            contentType: String = "",
            title: String = "",
            subtitle: String = "",
            posterUrl: String = "",
            note: String = "",
            voteCount: Int = 0,
            votedByMe: Bool = false,
            createdAt: String = ""
        ) {
            self.id = id
            self.roomId = roomId
            self.suggesterUserId = suggesterUserId
            self.suggesterProfileId = suggesterProfileId
            self.contentId = contentId
            self.contentType = contentType
            self.title = title
            self.subtitle = subtitle
            self.posterUrl = posterUrl
            self.note = note
            self.voteCount = voteCount
            self.votedByMe = votedByMe
            self.createdAt = createdAt
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.id = try container.decodeIfPresent(String.self, forKey: .id) ?? ""
            self.roomId = try container.decodeIfPresent(String.self, forKey: .roomId) ?? ""
            self.suggesterUserId = try container.decodeIfPresent(Int.self, forKey: .suggesterUserId) ?? 0
            self.suggesterProfileId = try container.decodeIfPresent(String.self, forKey: .suggesterProfileId) ?? ""
            self.contentId = try container.decodeIfPresent(String.self, forKey: .contentId) ?? ""
            self.contentType = try container.decodeIfPresent(String.self, forKey: .contentType) ?? ""
            self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? ""
            self.subtitle = try container.decodeIfPresent(String.self, forKey: .subtitle) ?? ""
            self.posterUrl = try container.decodeIfPresent(String.self, forKey: .posterUrl) ?? ""
            self.note = try container.decodeIfPresent(String.self, forKey: .note) ?? ""
            self.voteCount = try container.decodeIfPresent(Int.self, forKey: .voteCount) ?? 0
            self.votedByMe = try container.decodeIfPresent(Bool.self, forKey: .votedByMe) ?? false
            self.createdAt = try container.decodeIfPresent(String.self, forKey: .createdAt) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.id, forKey: .id)
            try container.encode(self.roomId, forKey: .roomId)
            try container.encode(self.suggesterUserId, forKey: .suggesterUserId)
            try container.encode(self.suggesterProfileId, forKey: .suggesterProfileId)
            try container.encode(self.contentId, forKey: .contentId)
            try container.encode(self.contentType, forKey: .contentType)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.subtitle, forKey: .subtitle)
            try container.encode(self.posterUrl, forKey: .posterUrl)
            try container.encode(self.note, forKey: .note)
            try container.encode(self.voteCount, forKey: .voteCount)
            try container.encode(self.votedByMe, forKey: .votedByMe)
            try container.encode(self.createdAt, forKey: .createdAt)
        }
    }
}
