// Code generated by cmd/clientdtogen from bloem-server internal/subtitles. DO NOT EDIT.
// Server revision: d66c15d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.subtitles

import kotlin.jvm.JvmInline
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/subtitles.DownloadedSubtitle`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class DownloadedSubtitle(
    @SerialName("id")
    public val id: Int = 0,
    @SerialName("media_file_id")
    public val mediaFileId: Int = 0,
    @SerialName("provider")
    public val provider: String = "",
    @SerialName("language")
    public val language: String = "",
    @SerialName("format")
    public val format: SubtitleFormat = SubtitleFormat(""),
    @SerialName("release_name")
    public val releaseName: String = "",
    @SerialName("score")
    public val score: Double = 0.0,
    @SerialName("hearing_impaired")
    public val hearingImpaired: Boolean = false,
    @SerialName("created_at")
    public val createdAt: String = "",
)

/** Wire type `internal/subtitles.LanguageDetection`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class LanguageDetection(
    @SerialName("language")
    public val language: String = "",
    @SerialName("source")
    public val source: LanguageDetectionSource = LanguageDetectionSource(""),
)

/** Wire type `internal/subtitles.LanguageDetectionSource`. Direction: response. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class LanguageDetectionSource(public val wire: String) {
    public companion object {
        @SerialName("filename")
        public val FILENAME: LanguageDetectionSource = LanguageDetectionSource("filename")
        @SerialName("metadata")
        public val METADATA: LanguageDetectionSource = LanguageDetectionSource("metadata")
        @SerialName("content")
        public val CONTENT: LanguageDetectionSource = LanguageDetectionSource("content")
        @SerialName("manual")
        public val MANUAL: LanguageDetectionSource = LanguageDetectionSource("manual")
        public val KNOWN: List<LanguageDetectionSource> = listOf(FILENAME, METADATA, CONTENT, MANUAL)
    }
}

/** Wire type `internal/subtitles.SearchResponse`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class SearchResponse(
    @SerialName("results")
    public val results: List<SubtitleResult> = emptyList(),
    @SerialName("warnings")
    public val warnings: List<String> = emptyList(),
)

/** Wire type `internal/subtitles.SubtitleFormat`. Direction: response. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class SubtitleFormat(public val wire: String) {
    public companion object {
        @SerialName("srt")
        public val SRT: SubtitleFormat = SubtitleFormat("srt")
        @SerialName("ass")
        public val ASS: SubtitleFormat = SubtitleFormat("ass")
        @SerialName("ssa")
        public val SSA: SubtitleFormat = SubtitleFormat("ssa")
        @SerialName("vtt")
        public val VTT: SubtitleFormat = SubtitleFormat("vtt")
        @SerialName("sub")
        public val SUB: SubtitleFormat = SubtitleFormat("sub")
        public val KNOWN: List<SubtitleFormat> = listOf(SRT, ASS, SSA, VTT, SUB)
    }
}

/** Wire type `internal/subtitles.SubtitleResult`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class SubtitleResult(
    @SerialName("id")
    public val id: String = "",
    @SerialName("provider")
    public val provider: String = "",
    @SerialName("language")
    public val language: String = "",
    @SerialName("release_name")
    public val releaseName: String = "",
    @SerialName("format")
    public val format: SubtitleFormat = SubtitleFormat(""),
    @SerialName("score")
    public val score: Double = 0.0,
    @SerialName("downloads")
    public val downloads: Int = 0,
    @SerialName("hearing_impaired")
    public val hearingImpaired: Boolean = false,
    @SerialName("upload_date")
    public val uploadDate: String = "",
)
