// Code generated by cmd/clientdtogen from bloem-server internal/remote. DO NOT EDIT.
// Server revision: 6b6f13f180e04ad8e0974ac12ea3b6562fd848d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/remote`.
public enum Remote {
    /// Wire type `internal/remote.Command`. Direction: response. Dialect: bloem. Gate: notifications.remote_control.
    public struct Command: Codable, Hashable, Sendable {
        public let id: String
        public let scope: Scope
        public let targetSessionId: String
        public let targetDeviceId: String
        public let targetUserId: Int
        public let targetProfileId: String
        public let tenantId: String
        public let name: Playback.CommandName
        public let payload: BloemJSONValue?
        public let issuedBy: String
        public let issuerKind: IssuerKind
        public let reason: String
        public let state: State
        public let result: BloemJSONValue?
        public let error: String
        public let createdAt: String
        public let sentAt: String?
        public let ackedAt: String?
        public let finishedAt: String?
        public let expiresAt: String?

        public enum CodingKeys: String, CodingKey {
            case id = "command_id"
            case scope = "scope"
            case targetSessionId = "session_id"
            case targetDeviceId = "device_id"
            case targetUserId = "user_id"
            case targetProfileId = "profile_id"
            case tenantId = "tenant_id"
            case name = "name"
            case payload = "payload"
            case issuedBy = "issued_by"
            case issuerKind = "issuer_kind"
            case reason = "reason"
            case state = "state"
            case result = "result"
            case error = "error"
            case createdAt = "created_at"
            case sentAt = "sent_at"
            case ackedAt = "acked_at"
            case finishedAt = "finished_at"
            case expiresAt = "expires_at"
        }

        public init(
            id: String = "",
            scope: Scope = Scope(rawValue: ""),
            targetSessionId: String = "",
            targetDeviceId: String = "",
            targetUserId: Int = 0,
            targetProfileId: String = "",
            tenantId: String = "",
            name: Playback.CommandName = Playback.CommandName(rawValue: ""),
            payload: BloemJSONValue? = nil,
            issuedBy: String = "",
            issuerKind: IssuerKind = IssuerKind(rawValue: ""),
            reason: String = "",
            state: State = State(rawValue: ""),
            result: BloemJSONValue? = nil,
            error: String = "",
            createdAt: String = "",
            sentAt: String? = nil,
            ackedAt: String? = nil,
            finishedAt: String? = nil,
            expiresAt: String? = nil
        ) {
            self.id = id
            self.scope = scope
            self.targetSessionId = targetSessionId
            self.targetDeviceId = targetDeviceId
            self.targetUserId = targetUserId
            self.targetProfileId = targetProfileId
            self.tenantId = tenantId
            self.name = name
            self.payload = payload
            self.issuedBy = issuedBy
            self.issuerKind = issuerKind
            self.reason = reason
            self.state = state
            self.result = result
            self.error = error
            self.createdAt = createdAt
            self.sentAt = sentAt
            self.ackedAt = ackedAt
            self.finishedAt = finishedAt
            self.expiresAt = expiresAt
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.id = try container.decodeIfPresent(String.self, forKey: .id) ?? ""
            self.scope = try container.decodeIfPresent(Scope.self, forKey: .scope) ?? Scope(rawValue: "")
            self.targetSessionId = try container.decodeIfPresent(String.self, forKey: .targetSessionId) ?? ""
            self.targetDeviceId = try container.decodeIfPresent(String.self, forKey: .targetDeviceId) ?? ""
            self.targetUserId = try container.decodeIfPresent(Int.self, forKey: .targetUserId) ?? 0
            self.targetProfileId = try container.decodeIfPresent(String.self, forKey: .targetProfileId) ?? ""
            self.tenantId = try container.decodeIfPresent(String.self, forKey: .tenantId) ?? ""
            self.name = try container.decodeIfPresent(Playback.CommandName.self, forKey: .name) ?? Playback.CommandName(rawValue: "")
            self.payload = try container.decodeIfPresent(BloemJSONValue.self, forKey: .payload)
            self.issuedBy = try container.decodeIfPresent(String.self, forKey: .issuedBy) ?? ""
            self.issuerKind = try container.decodeIfPresent(IssuerKind.self, forKey: .issuerKind) ?? IssuerKind(rawValue: "")
            self.reason = try container.decodeIfPresent(String.self, forKey: .reason) ?? ""
            self.state = try container.decodeIfPresent(State.self, forKey: .state) ?? State(rawValue: "")
            self.result = try container.decodeIfPresent(BloemJSONValue.self, forKey: .result)
            self.error = try container.decodeIfPresent(String.self, forKey: .error) ?? ""
            self.createdAt = try container.decodeIfPresent(String.self, forKey: .createdAt) ?? ""
            self.sentAt = try container.decodeIfPresent(String.self, forKey: .sentAt)
            self.ackedAt = try container.decodeIfPresent(String.self, forKey: .ackedAt)
            self.finishedAt = try container.decodeIfPresent(String.self, forKey: .finishedAt)
            self.expiresAt = try container.decodeIfPresent(String.self, forKey: .expiresAt)
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.id, forKey: .id)
            try container.encode(self.scope, forKey: .scope)
            try container.encode(self.targetSessionId, forKey: .targetSessionId)
            try container.encode(self.targetDeviceId, forKey: .targetDeviceId)
            try container.encode(self.targetUserId, forKey: .targetUserId)
            try container.encode(self.targetProfileId, forKey: .targetProfileId)
            try container.encode(self.tenantId, forKey: .tenantId)
            try container.encode(self.name, forKey: .name)
            try container.encodeIfPresent(self.payload, forKey: .payload)
            try container.encode(self.issuedBy, forKey: .issuedBy)
            try container.encode(self.issuerKind, forKey: .issuerKind)
            try container.encode(self.reason, forKey: .reason)
            try container.encode(self.state, forKey: .state)
            try container.encodeIfPresent(self.result, forKey: .result)
            try container.encode(self.error, forKey: .error)
            try container.encode(self.createdAt, forKey: .createdAt)
            try container.encodeIfPresent(self.sentAt, forKey: .sentAt)
            try container.encodeIfPresent(self.ackedAt, forKey: .ackedAt)
            try container.encodeIfPresent(self.finishedAt, forKey: .finishedAt)
            try container.encodeIfPresent(self.expiresAt, forKey: .expiresAt)
        }
    }

    /// Wire type `internal/remote.IssuerKind`. Direction: response. Dialect: bloem. Gate: notifications.remote_control.
    public struct IssuerKind: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let ADMIN: IssuerKind = IssuerKind(rawValue: "admin")
        public static let HOUSEHOLD: IssuerKind = IssuerKind(rawValue: "household")
        public static let KNOWN: [IssuerKind] = [ADMIN, HOUSEHOLD]
    }

    /// Wire type `internal/remote.MessagePayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root.
    public struct MessagePayload: Codable, Hashable, Sendable {
        public let title: String
        public let body: String
        public let severity: String
        public let timeoutMs: Int

        public enum CodingKeys: String, CodingKey {
            case title = "title"
            case body = "body"
            case severity = "severity"
            case timeoutMs = "timeout_ms"
        }

        public init(
            title: String = "",
            body: String = "",
            severity: String = "",
            timeoutMs: Int = 0
        ) {
            self.title = title
            self.body = body
            self.severity = severity
            self.timeoutMs = timeoutMs
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? ""
            self.body = try container.decodeIfPresent(String.self, forKey: .body) ?? ""
            self.severity = try container.decodeIfPresent(String.self, forKey: .severity) ?? ""
            self.timeoutMs = try container.decodeIfPresent(Int.self, forKey: .timeoutMs) ?? 0
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.body, forKey: .body)
            try container.encode(self.severity, forKey: .severity)
            try container.encode(self.timeoutMs, forKey: .timeoutMs)
        }
    }

    /// Wire type `internal/remote.ReasonPayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root.
    public struct ReasonPayload: Codable, Hashable, Sendable {
        public let reason: String

        public enum CodingKeys: String, CodingKey {
            case reason = "reason"
        }

        public init(
            reason: String = ""
        ) {
            self.reason = reason
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.reason = try container.decodeIfPresent(String.self, forKey: .reason) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.reason, forKey: .reason)
        }
    }

    /// Wire type `internal/remote.ReplanOverrides`. Direction: both. Dialect: bloem. Gate: notifications.remote_control.
    public struct ReplanOverrides: Codable, Hashable, Sendable {
        public let transcode: TranscodeMode
        public let maxBitrateKbps: Int
        public let videoCodec: String
        public let audioCodec: String
        public let container: String

        public enum CodingKeys: String, CodingKey {
            case transcode = "transcode"
            case maxBitrateKbps = "max_bitrate_kbps"
            case videoCodec = "video_codec"
            case audioCodec = "audio_codec"
            case container = "container"
        }

        public init(
            transcode: TranscodeMode = TranscodeMode(rawValue: ""),
            maxBitrateKbps: Int = 0,
            videoCodec: String = "",
            audioCodec: String = "",
            container: String = ""
        ) {
            self.transcode = transcode
            self.maxBitrateKbps = maxBitrateKbps
            self.videoCodec = videoCodec
            self.audioCodec = audioCodec
            self.container = container
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.transcode = try container.decodeIfPresent(TranscodeMode.self, forKey: .transcode) ?? TranscodeMode(rawValue: "")
            self.maxBitrateKbps = try container.decodeIfPresent(Int.self, forKey: .maxBitrateKbps) ?? 0
            self.videoCodec = try container.decodeIfPresent(String.self, forKey: .videoCodec) ?? ""
            self.audioCodec = try container.decodeIfPresent(String.self, forKey: .audioCodec) ?? ""
            self.container = try container.decodeIfPresent(String.self, forKey: .container) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.transcode, forKey: .transcode)
            try container.encode(self.maxBitrateKbps, forKey: .maxBitrateKbps)
            try container.encode(self.videoCodec, forKey: .videoCodec)
            try container.encode(self.audioCodec, forKey: .audioCodec)
            try container.encode(self.container, forKey: .container)
        }
    }

    /// Wire type `internal/remote.ReplanPayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root.
    public struct ReplanPayload: Codable, Hashable, Sendable {
        public let overrides: ReplanOverrides
        public let reason: String

        public enum CodingKeys: String, CodingKey {
            case overrides = "overrides"
            case reason = "reason"
        }

        public init(
            overrides: ReplanOverrides = ReplanOverrides(),
            reason: String = ""
        ) {
            self.overrides = overrides
            self.reason = reason
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.overrides = try container.decodeIfPresent(ReplanOverrides.self, forKey: .overrides) ?? ReplanOverrides()
            self.reason = try container.decodeIfPresent(String.self, forKey: .reason) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.overrides, forKey: .overrides)
            try container.encode(self.reason, forKey: .reason)
        }
    }

    /// Wire type `internal/remote.Scope`. Direction: response. Dialect: bloem. Gate: notifications.remote_control.
    public struct Scope: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let SESSION: Scope = Scope(rawValue: "session")
        public static let DEVICE: Scope = Scope(rawValue: "device")
        public static let KNOWN: [Scope] = [SESSION, DEVICE]
    }

    /// Wire type `internal/remote.SeekPayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root.
    public struct SeekPayload: Codable, Hashable, Sendable {
        public let positionMs: Int64

        public enum CodingKeys: String, CodingKey {
            case positionMs = "position_ms"
        }

        public init(
            positionMs: Int64 = 0
        ) {
            self.positionMs = positionMs
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.positionMs = try container.decodeIfPresent(Int64.self, forKey: .positionMs) ?? 0
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.positionMs, forKey: .positionMs)
        }
    }

    /// Wire type `internal/remote.State`. Direction: response. Dialect: bloem. Gate: notifications.remote_control.
    public struct State: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let QUEUED: State = State(rawValue: "queued")
        public static let SENT: State = State(rawValue: "sent")
        public static let ACCEPTED: State = State(rawValue: "accepted")
        public static let REJECTED: State = State(rawValue: "rejected")
        public static let REJECTED_UNSUPPORTED: State = State(rawValue: "rejected_unsupported")
        public static let DONE: State = State(rawValue: "done")
        public static let FAILED: State = State(rawValue: "failed")
        public static let EXPIRED: State = State(rawValue: "expired")
        public static let KNOWN: [State] = [QUEUED, SENT, ACCEPTED, REJECTED, REJECTED_UNSUPPORTED, DONE, FAILED, EXPIRED]
    }

    /// Wire type `internal/remote.TrackPayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root.
    public struct TrackPayload: Codable, Hashable, Sendable {
        public let trackId: String
        public let off: Bool

        public enum CodingKeys: String, CodingKey {
            case trackId = "track_id"
            case off = "off"
        }

        public init(
            trackId: String = "",
            off: Bool = false
        ) {
            self.trackId = trackId
            self.off = off
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.trackId = try container.decodeIfPresent(String.self, forKey: .trackId) ?? ""
            self.off = try container.decodeIfPresent(Bool.self, forKey: .off) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.trackId, forKey: .trackId)
            try container.encode(self.off, forKey: .off)
        }
    }

    /// Wire type `internal/remote.TranscodeMode`. Direction: both. Dialect: bloem. Gate: notifications.remote_control.
    public struct TranscodeMode: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let AUTO: TranscodeMode = TranscodeMode(rawValue: "auto")
        public static let FORCE: TranscodeMode = TranscodeMode(rawValue: "force")
        public static let DIRECT: TranscodeMode = TranscodeMode(rawValue: "direct")
        public static let KNOWN: [TranscodeMode] = [AUTO, FORCE, DIRECT]
    }

    /// Wire type `internal/remote.VolumePayload`. Direction: both. Dialect: bloem. Gate: notifications.remote_control. Registered root.
    public struct VolumePayload: Codable, Hashable, Sendable {
        public let level: Int

        public enum CodingKeys: String, CodingKey {
            case level = "level"
        }

        public init(
            level: Int = 0
        ) {
            self.level = level
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.level = try container.decodeIfPresent(Int.self, forKey: .level) ?? 0
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.level, forKey: .level)
        }
    }
}
