// Code generated by cmd/clientdtogen from bloem-server internal/onboarding. DO NOT EDIT.
// Server revision: 6b6f13f180e04ad8e0974ac12ea3b6562fd848d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.onboarding

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/onboarding.Flow`. Direction: response. Dialect: bloem. Registered root. */
@Serializable
public data class Flow(
    @SerialName("version")
    public val version: Int = 0,
    @SerialName("tour_id")
    public val tourId: String = "",
    @SerialName("steps")
    public val steps: List<Step> = emptyList(),
)

/** Wire type `internal/onboarding.SettingOption`. Direction: response. Dialect: bloem. */
@Serializable
public data class SettingOption(
    @SerialName("value")
    public val value: String = "",
    @SerialName("label")
    public val label: String = "",
)

/** Wire type `internal/onboarding.SettingSpec`. Direction: response. Dialect: bloem. */
@Serializable
public data class SettingSpec(
    @SerialName("target")
    public val target: String = "",
    @SerialName("key")
    public val key: String = "",
    @SerialName("control")
    public val control: String = "",
    @SerialName("options")
    public val options: List<SettingOption> = emptyList(),
    @SerialName("default")
    public val default: String = "",
    @SerialName("label")
    public val label: String = "",
)

/** Wire type `internal/onboarding.Step`. Direction: response. Dialect: bloem. */
@Serializable
public data class Step(
    @SerialName("id")
    public val id: String = "",
    @SerialName("kind")
    public val kind: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("body")
    public val body: String = "",
    @SerialName("illustration")
    public val illustration: String = "",
    @SerialName("setting")
    public val setting: SettingSpec? = null,
    @SerialName("route")
    public val route: String = "",
    @SerialName("action_label")
    public val actionLabel: String = "",
    @SerialName("links")
    public val links: List<StepLink> = emptyList(),
)

/** Wire type `internal/onboarding.StepLink`. Direction: response. Dialect: bloem. */
@Serializable
public data class StepLink(
    @SerialName("label")
    public val label: String = "",
    @SerialName("url")
    public val url: String = "",
)
