// Code generated by cmd/clientdtogen from bloem-server internal/resourcetenancy. DO NOT EDIT.
// Server revision: cdbeda7d1f2ecd38ba88f5633c35aec8ff77999d (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/resourcetenancy`.
public enum Resourcetenancy {
    /// Wire type `internal/resourcetenancy.OwnerKind`. Direction: response. Dialect: bloem. Gate: native_storage.source_management.
    public struct OwnerKind: RawRepresentable, Codable, Hashable, Sendable {
        public let wire: String
        public var rawValue: String { wire }
        public init(rawValue: String) { self.wire = rawValue }

        public static let PLATFORM: OwnerKind = OwnerKind(rawValue: "platform")
        public static let ORGANIZATION: OwnerKind = OwnerKind(rawValue: "organization")
        public static let KNOWN: [OwnerKind] = [PLATFORM, ORGANIZATION]
    }
}
