// Code generated by cmd/clientdtogen from bloem-server internal/watchtogether. DO NOT EDIT.
// Server revision: d66c15d8 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.watchtogether

import kotlin.jvm.JvmInline
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/watchtogether.GuestControlPolicy`. Direction: both. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class GuestControlPolicy(public val wire: String) {
    public companion object {
        @SerialName("host_only")
        public val HOST_ONLY: GuestControlPolicy = GuestControlPolicy("host_only")
        @SerialName("guest_play_pause")
        public val GUEST_PLAY_PAUSE: GuestControlPolicy = GuestControlPolicy("guest_play_pause")
        public val KNOWN: List<GuestControlPolicy> = listOf(HOST_ONLY, GUEST_PLAY_PAUSE)
    }
}

/** Wire type `internal/watchtogether.MemberRole`. Direction: response. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class MemberRole(public val wire: String) {
    public companion object {
        @SerialName("host")
        public val HOST: MemberRole = MemberRole("host")
        @SerialName("guest")
        public val GUEST: MemberRole = MemberRole("guest")
        public val KNOWN: List<MemberRole> = listOf(HOST, GUEST)
    }
}

/** Wire type `internal/watchtogether.MemberSummary`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class MemberSummary(
    @SerialName("user_id")
    public val userId: Int = 0,
    @SerialName("profile_id")
    public val profileId: String = "",
    @SerialName("display_name")
    public val displayName: String = "",
    @SerialName("is_host")
    public val isHost: Boolean = false,
    @SerialName("is_self")
    public val isSelf: Boolean = false,
    @SerialName("connected")
    public val connected: Boolean = false,
)

/** Wire type `internal/watchtogether.RoomPhase`. Direction: response. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class RoomPhase(public val wire: String) {
    public companion object {
        @SerialName("lobby")
        public val LOBBY: RoomPhase = RoomPhase("lobby")
        @SerialName("playing")
        public val PLAYING: RoomPhase = RoomPhase("playing")
        @SerialName("ended")
        public val ENDED: RoomPhase = RoomPhase("ended")
        public val KNOWN: List<RoomPhase> = listOf(LOBBY, PLAYING, ENDED)
    }
}

/** Wire type `internal/watchtogether.RoomPlaybackState`. Direction: response. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class RoomPlaybackState(public val wire: String) {
    public companion object {
        @SerialName("idle")
        public val IDLE: RoomPlaybackState = RoomPlaybackState("idle")
        @SerialName("waiting")
        public val WAITING: RoomPlaybackState = RoomPlaybackState("waiting")
        @SerialName("paused")
        public val PAUSED: RoomPlaybackState = RoomPlaybackState("paused")
        @SerialName("playing")
        public val PLAYING: RoomPlaybackState = RoomPlaybackState("playing")
        public val KNOWN: List<RoomPlaybackState> = listOf(IDLE, WAITING, PAUSED, PLAYING)
    }
}

/** Wire type `internal/watchtogether.RoomSelectionMode`. Direction: response. Dialect: upstream-compat. */
@Serializable
@JvmInline
public value class RoomSelectionMode(public val wire: String) {
    public companion object {
        @SerialName("host_pick")
        public val HOST_PICK: RoomSelectionMode = RoomSelectionMode("host_pick")
        @SerialName("vote")
        public val VOTE: RoomSelectionMode = RoomSelectionMode("vote")
        public val KNOWN: List<RoomSelectionMode> = listOf(HOST_PICK, VOTE)
    }
}

/** Wire type `internal/watchtogether.Snapshot`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class Snapshot(
    @SerialName("room_id")
    public val roomId: String = "",
    @SerialName("phase")
    public val phase: RoomPhase = RoomPhase(""),
    @SerialName("playback_state")
    public val playbackState: RoomPlaybackState = RoomPlaybackState(""),
    @SerialName("selection_mode")
    public val selectionMode: RoomSelectionMode = RoomSelectionMode(""),
    @SerialName("selection_revision")
    public val selectionRevision: Long = 0L,
    @SerialName("selected_content_id")
    public val selectedContentId: String? = null,
    @SerialName("selected_file_id")
    public val selectedFileId: Int? = null,
    @SerialName("selected_library_id")
    public val selectedLibraryId: Int? = null,
    @SerialName("code")
    public val code: String = "",
    @SerialName("guest_control_policy")
    public val guestControlPolicy: GuestControlPolicy = GuestControlPolicy(""),
    @SerialName("is_paused")
    public val isPaused: Boolean = false,
    @SerialName("anchor_position_seconds")
    public val anchorPositionSeconds: Double = 0.0,
    @SerialName("anchor_updated_at")
    public val anchorUpdatedAt: String = "",
    @SerialName("generation")
    public val generation: Long = 0L,
    @SerialName("owner_generation")
    public val ownerGeneration: Long = 0L,
    @SerialName("member_count")
    public val memberCount: Int = 0,
    @SerialName("host_connected")
    public val hostConnected: Boolean = false,
    @SerialName("self_role")
    public val selfRole: MemberRole = MemberRole(""),
    @SerialName("self_can_control_transport")
    public val selfCanControlTransport: Boolean = false,
    @SerialName("self_can_manage_room")
    public val selfCanManageRoom: Boolean = false,
    @SerialName("self_ignore_wait")
    public val selfIgnoreWait: Boolean = false,
    @SerialName("attached_session_id")
    public val attachedSessionId: String = "",
    @SerialName("invite_path")
    public val invitePath: String = "",
    @SerialName("members")
    public val members: List<MemberSummary> = emptyList(),
)

/** Wire type `internal/watchtogether.Suggestion`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class Suggestion(
    @SerialName("id")
    public val id: String = "",
    @SerialName("room_id")
    public val roomId: String = "",
    @SerialName("suggester_user_id")
    public val suggesterUserId: Int = 0,
    @SerialName("suggester_profile_id")
    public val suggesterProfileId: String = "",
    @SerialName("content_id")
    public val contentId: String = "",
    @SerialName("content_type")
    public val contentType: String = "",
    @SerialName("title")
    public val title: String = "",
    @SerialName("subtitle")
    public val subtitle: String = "",
    @SerialName("poster_url")
    public val posterUrl: String = "",
    @SerialName("note")
    public val note: String = "",
    @SerialName("vote_count")
    public val voteCount: Int = 0,
    @SerialName("voted_by_me")
    public val votedByMe: Boolean = false,
    @SerialName("created_at")
    public val createdAt: String = "",
)
