// Code generated by cmd/clientdtogen from bloem-server internal/downloads. DO NOT EDIT.
// Server revision: 7ef228d3e10c81f166d2445967c7ec6db2bcb102 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/downloads`.
public enum Downloads {
    /// Wire type `internal/downloads.OfflineAudioTrack`. Direction: response. Dialect: bloem.
    public struct OfflineAudioTrack: Codable, Hashable, Sendable {
        public let index: Int
        public let title: String
        public let language: String
        public let codec: String
        public let layout: String
        public let channels: Int
        public let bitrate: Int
        public let sampleRate: Int
        public let defaultValue: Bool

        public enum CodingKeys: String, CodingKey {
            case index = "index"
            case title = "title"
            case language = "language"
            case codec = "codec"
            case layout = "layout"
            case channels = "channels"
            case bitrate = "bitrate"
            case sampleRate = "sample_rate"
            case defaultValue = "default"
        }

        public init(
            index: Int = 0,
            title: String = "",
            language: String = "",
            codec: String = "",
            layout: String = "",
            channels: Int = 0,
            bitrate: Int = 0,
            sampleRate: Int = 0,
            defaultValue: Bool = false
        ) {
            self.index = index
            self.title = title
            self.language = language
            self.codec = codec
            self.layout = layout
            self.channels = channels
            self.bitrate = bitrate
            self.sampleRate = sampleRate
            self.defaultValue = defaultValue
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.index = try container.decodeIfPresent(Int.self, forKey: .index) ?? 0
            self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? ""
            self.language = try container.decodeIfPresent(String.self, forKey: .language) ?? ""
            self.codec = try container.decodeIfPresent(String.self, forKey: .codec) ?? ""
            self.layout = try container.decodeIfPresent(String.self, forKey: .layout) ?? ""
            self.channels = try container.decodeIfPresent(Int.self, forKey: .channels) ?? 0
            self.bitrate = try container.decodeIfPresent(Int.self, forKey: .bitrate) ?? 0
            self.sampleRate = try container.decodeIfPresent(Int.self, forKey: .sampleRate) ?? 0
            self.defaultValue = try container.decodeIfPresent(Bool.self, forKey: .defaultValue) ?? false
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.index, forKey: .index)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.language, forKey: .language)
            try container.encode(self.codec, forKey: .codec)
            try container.encode(self.layout, forKey: .layout)
            try container.encode(self.channels, forKey: .channels)
            try container.encode(self.bitrate, forKey: .bitrate)
            try container.encode(self.sampleRate, forKey: .sampleRate)
            try container.encode(self.defaultValue, forKey: .defaultValue)
        }
    }

    /// Wire type `internal/downloads.OfflineChapter`. Direction: response. Dialect: bloem.
    public struct OfflineChapter: Codable, Hashable, Sendable {
        public let index: Int
        public let title: String
        public let startSeconds: Double
        public let endSeconds: Double
        public let thumbnailThumbhash: String

        public enum CodingKeys: String, CodingKey {
            case index = "index"
            case title = "title"
            case startSeconds = "start_seconds"
            case endSeconds = "end_seconds"
            case thumbnailThumbhash = "thumbnail_thumbhash"
        }

        public init(
            index: Int = 0,
            title: String = "",
            startSeconds: Double = 0.0,
            endSeconds: Double = 0.0,
            thumbnailThumbhash: String = ""
        ) {
            self.index = index
            self.title = title
            self.startSeconds = startSeconds
            self.endSeconds = endSeconds
            self.thumbnailThumbhash = thumbnailThumbhash
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.index = try container.decodeIfPresent(Int.self, forKey: .index) ?? 0
            self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? ""
            self.startSeconds = try container.decodeIfPresent(Double.self, forKey: .startSeconds) ?? 0.0
            self.endSeconds = try container.decodeIfPresent(Double.self, forKey: .endSeconds) ?? 0.0
            self.thumbnailThumbhash = try container.decodeIfPresent(String.self, forKey: .thumbnailThumbhash) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.index, forKey: .index)
            try container.encode(self.title, forKey: .title)
            try container.encode(self.startSeconds, forKey: .startSeconds)
            try container.encode(self.endSeconds, forKey: .endSeconds)
            try container.encode(self.thumbnailThumbhash, forKey: .thumbnailThumbhash)
        }
    }

    /// Wire type `internal/downloads.OfflineIdentity`. Direction: response. Dialect: bloem.
    public struct OfflineIdentity: Codable, Hashable, Sendable {
        public let stableType: String
        public let providerIds: [String: String]
        public let seriesProviderIds: [String: String]
        public let season: Int?
        public let episode: Int?

        public enum CodingKeys: String, CodingKey {
            case stableType = "stable_type"
            case providerIds = "provider_ids"
            case seriesProviderIds = "series_provider_ids"
            case season = "season"
            case episode = "episode"
        }

        public init(
            stableType: String = "",
            providerIds: [String: String] = [:],
            seriesProviderIds: [String: String] = [:],
            season: Int? = nil,
            episode: Int? = nil
        ) {
            self.stableType = stableType
            self.providerIds = providerIds
            self.seriesProviderIds = seriesProviderIds
            self.season = season
            self.episode = episode
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.stableType = try container.decodeIfPresent(String.self, forKey: .stableType) ?? ""
            self.providerIds = try container.decodeIfPresent([String: String].self, forKey: .providerIds) ?? [:]
            self.seriesProviderIds = try container.decodeIfPresent([String: String].self, forKey: .seriesProviderIds) ?? [:]
            self.season = try container.decodeIfPresent(Int.self, forKey: .season)
            self.episode = try container.decodeIfPresent(Int.self, forKey: .episode)
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.stableType, forKey: .stableType)
            try container.encode(self.providerIds, forKey: .providerIds)
            try container.encode(self.seriesProviderIds, forKey: .seriesProviderIds)
            try container.encodeIfPresent(self.season, forKey: .season)
            try container.encodeIfPresent(self.episode, forKey: .episode)
        }
    }

    /// Wire type `internal/downloads.OfflineIntegrity`. Direction: response. Dialect: bloem.
    public struct OfflineIntegrity: Codable, Hashable, Sendable {
        public let expectedBytes: Int64
        public let mediaFileHash: String
        public let metadataETag: String

        public enum CodingKeys: String, CodingKey {
            case expectedBytes = "expected_bytes"
            case mediaFileHash = "media_file_hash"
            case metadataETag = "metadata_etag"
        }

        public init(
            expectedBytes: Int64 = 0,
            mediaFileHash: String = "",
            metadataETag: String = ""
        ) {
            self.expectedBytes = expectedBytes
            self.mediaFileHash = mediaFileHash
            self.metadataETag = metadataETag
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.expectedBytes = try container.decodeIfPresent(Int64.self, forKey: .expectedBytes) ?? 0
            self.mediaFileHash = try container.decodeIfPresent(String.self, forKey: .mediaFileHash) ?? ""
            self.metadataETag = try container.decodeIfPresent(String.self, forKey: .metadataETag) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.expectedBytes, forKey: .expectedBytes)
            try container.encode(self.mediaFileHash, forKey: .mediaFileHash)
            try container.encode(self.metadataETag, forKey: .metadataETag)
        }
    }

    /// Wire type `internal/downloads.OfflineSubtitle`. Direction: response. Dialect: bloem.
    public struct OfflineSubtitle: Codable, Hashable, Sendable {
        public let language: String
        public let format: String
        public let forced: Bool
        public let hearingImpaired: Bool
        public let external: Bool
        public let fetchUrl: String
        public let fileSize: Int64

        public enum CodingKeys: String, CodingKey {
            case language = "language"
            case format = "format"
            case forced = "forced"
            case hearingImpaired = "hearing_impaired"
            case external = "external"
            case fetchUrl = "fetch_url"
            case fileSize = "file_size"
        }

        public init(
            language: String = "",
            format: String = "",
            forced: Bool = false,
            hearingImpaired: Bool = false,
            external: Bool = false,
            fetchUrl: String = "",
            fileSize: Int64 = 0
        ) {
            self.language = language
            self.format = format
            self.forced = forced
            self.hearingImpaired = hearingImpaired
            self.external = external
            self.fetchUrl = fetchUrl
            self.fileSize = fileSize
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.language = try container.decodeIfPresent(String.self, forKey: .language) ?? ""
            self.format = try container.decodeIfPresent(String.self, forKey: .format) ?? ""
            self.forced = try container.decodeIfPresent(Bool.self, forKey: .forced) ?? false
            self.hearingImpaired = try container.decodeIfPresent(Bool.self, forKey: .hearingImpaired) ?? false
            self.external = try container.decodeIfPresent(Bool.self, forKey: .external) ?? false
            self.fetchUrl = try container.decodeIfPresent(String.self, forKey: .fetchUrl) ?? ""
            self.fileSize = try container.decodeIfPresent(Int64.self, forKey: .fileSize) ?? 0
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.language, forKey: .language)
            try container.encode(self.format, forKey: .format)
            try container.encode(self.forced, forKey: .forced)
            try container.encode(self.hearingImpaired, forKey: .hearingImpaired)
            try container.encode(self.external, forKey: .external)
            try container.encode(self.fetchUrl, forKey: .fetchUrl)
            try container.encode(self.fileSize, forKey: .fileSize)
        }
    }

    /// Wire type `internal/downloads.SkippedDownload`. Direction: response. Dialect: upstream-compat.
    public struct SkippedDownload: Codable, Hashable, Sendable {
        public let episodeId: String
        public let reason: String

        public enum CodingKeys: String, CodingKey {
            case episodeId = "episode_id"
            case reason = "reason"
        }

        public init(
            episodeId: String = "",
            reason: String = ""
        ) {
            self.episodeId = episodeId
            self.reason = reason
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.episodeId = try container.decodeIfPresent(String.self, forKey: .episodeId) ?? ""
            self.reason = try container.decodeIfPresent(String.self, forKey: .reason) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.episodeId, forKey: .episodeId)
            try container.encode(self.reason, forKey: .reason)
        }
    }

    /// Wire type `internal/downloads.SkippedManifest`. Direction: response. Dialect: bloem.
    public struct SkippedManifest: Codable, Hashable, Sendable {
        public let downloadId: String
        public let reason: String

        public enum CodingKeys: String, CodingKey {
            case downloadId = "download_id"
            case reason = "reason"
        }

        public init(
            downloadId: String = "",
            reason: String = ""
        ) {
            self.downloadId = downloadId
            self.reason = reason
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.downloadId = try container.decodeIfPresent(String.self, forKey: .downloadId) ?? ""
            self.reason = try container.decodeIfPresent(String.self, forKey: .reason) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.downloadId, forKey: .downloadId)
            try container.encode(self.reason, forKey: .reason)
        }
    }
}
