// Code generated by cmd/clientdtogen from bloem-server internal/downloads. DO NOT EDIT.
// Server revision: 8c612bd9 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding is exact: every initializer reads an absent or null key as the documented
// default, so a server that omits a key still decodes, and encoding omits a nil value
// rather than writing null. Requires the client-owned BloemJSONValue (a Codable, Hashable,
// Sendable JSON value) and Indirect (a box for self-referential fields).

/// Wire types of the Go package `internal/downloads`.
public enum Downloads {
    /// Wire type `internal/downloads.SkippedDownload`. Direction: response. Dialect: upstream-compat.
    public struct SkippedDownload: Codable, Hashable, Sendable {
        public let episodeId: String
        public let reason: String

        public enum CodingKeys: String, CodingKey {
            case episodeId = "episode_id"
            case reason = "reason"
        }

        public init(
            episodeId: String = "",
            reason: String = ""
        ) {
            self.episodeId = episodeId
            self.reason = reason
        }

        public init(from decoder: any Decoder) throws {
            let container = try decoder.container(keyedBy: CodingKeys.self)
            self.episodeId = try container.decodeIfPresent(String.self, forKey: .episodeId) ?? ""
            self.reason = try container.decodeIfPresent(String.self, forKey: .reason) ?? ""
        }

        public func encode(to encoder: any Encoder) throws {
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(self.episodeId, forKey: .episodeId)
            try container.encode(self.reason, forKey: .reason)
        }
    }
}
