// Code generated by cmd/clientdtogen from bloem-server internal/promotions. DO NOT EDIT.
// Server revision: 8c612bd9 (generator v1, registry contracts/client/v1/registry.json)
// Regenerate in the server repo with: make client-dtos
//
// Decoding requires the shared Json configuration: ignoreUnknownKeys, coerceInputValues,
// explicitNulls = false, encodeDefaults (see network/BloemHttpClient.kt).

package org.bloemserver.bloem.contract.promotions

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Wire type `internal/promotions.CTA`. Direction: response. Dialect: upstream-compat. */
@Serializable
public data class CTA(
    @SerialName("label")
    public val label: String = "",
    @SerialName("url")
    public val url: String = "",
)

/** Wire type `internal/promotions.Card`. Direction: response. Dialect: upstream-compat. Registered root. */
@Serializable
public data class Card(
    @SerialName("duration_seconds")
    public val durationSeconds: Int = 0,
    @SerialName("video_url")
    public val videoUrl: String = "",
    @SerialName("playback_style")
    public val playbackStyle: String = "",
    @SerialName("expires_at")
    public val expiresAt: String = "",
    @SerialName("id")
    public val id: String = "",
    @SerialName("kicker")
    public val kicker: String = "",
    @SerialName("headline")
    public val headline: String = "",
    @SerialName("subtitle")
    public val subtitle: String = "",
    @SerialName("image_url")
    public val imageUrl: String = "",
    @SerialName("deeplink")
    public val deeplink: String = "",
    @SerialName("cta")
    public val cta: CTA? = null,
    @SerialName("dismissible")
    public val dismissible: Boolean = false,
)
